% Cox proportional hazards model for response timing during RT
%
% Primary time-varying predictor:
%   activeIEDWindowCount(t) = number of individual IEDs whose 500 ms
%                             post-IED windows are active at time t
%
% Every IED row is retained. IEDs are not collapsed with unique(), even
% when they occur at the same sample or in the same channel. Therefore,
% two active IED windows contribute a predictor value of 2, three contribute
% a value of 3, and so on. The model estimates the hazard change per
% additional active IED while adjusting for balloon color.
%
% Participant ID is used as a stratum, so each participant has a separate
% baseline hazard. Participant-clustered robust standard errors are saved.
%
% Only non-control yellow, orange, and red balloon trials are included.
% Trials with RT > 10 seconds are excluded.
% Trials with no IEDs are included and remain unexposed throughout.
%
% Author: Nill

clear;
clc;
close all;

%% paths and analysis settings

inputFolderName_LFPIED = ...
    'D:\Nill\data\BART\0_0_new_IED\IED1_find_number_of_IEDs\';

outputFolderName = ...
    'D:\Nill\code\BART\IED\0_0_new_IED\IED6_Cox_RT_postIED\';

if ~exist(outputFolderName, 'dir')
    mkdir(outputFolderName);
end

% Save all Command Window output from this script in a text file.
textOutputFile = fullfile( ...
    outputFolderName, 'RT_postIED500ms_console_output.txt');

% Start a fresh text output file for every run.
diary off;
if exist(textOutputFile, 'file')
    delete(textOutputFile);
end
diary(textOutputFile);
diaryCleanup = onCleanup(@() diary('off'));

% If LFPIED.Fs exists, the saved value is used.
% Otherwise, the sampling frequency is silently set to 1000 Hz.
defaultSamplingFrequencyHz = 1000;

% Primary post-IED exposure window.
postIEDWindowMilliseconds = 500;
postIEDWindowSeconds = postIEDWindowMilliseconds / 1000;

maximumRTSeconds = 20;

fileList = dir(fullfile(inputFolderName_LFPIED, '*.LFPIED.mat'));

countingProcessData = table();
trialSummary = table();

%% build counting-process data across all participants

for pt = 1:length(fileList)

    fileName = fileList(pt).name;
    fileNameParts = strsplit(fileName, '.');
    patientID = string(fileNameParts{1});

    fprintf('\nprocessing patient: %s\n', patientID);

    loadedData = load(fullfile(inputFolderName_LFPIED, fileName));

    if ~isfield(loadedData, 'LFPIED')
        fprintf('skipped: lfpied structure was not found.\n');
        continue;
    end

    LFPIED = loadedData.LFPIED;

    requiredFields = {'RTs', 'isControl', 'balloonType', 'IED_occurance_RT'};

    missingField = false;

    for ff = 1:length(requiredFields)
        if ~isfield(LFPIED, requiredFields{ff})
            fprintf('skipped: missing field %s.\n', requiredFields{ff});
            missingField = true;
        end
    end

    if missingField
        continue;
    end

    RTs = LFPIED.RTs(:);
    isControl = LFPIED.isControl(:);
    balloonType = LFPIED.balloonType(:);

    nTrials = determineNumberOfTrials( ...
        LFPIED, RTs, isControl, balloonType);

    RTs = RTs(1:nTrials);
    isControl = isControl(1:nTrials);
    balloonType = balloonType(1:nTrials);

    balloonColorCode = mapBalloonColorCode(balloonType);

    samplingFrequencyHz = getSamplingFrequency( ...
        LFPIED, defaultSamplingFrequencyHz);

    IEDoccurrence = LFPIED.IED_occurance_RT;

    for trial = 1:nTrials

        durationSeconds = RTs(trial);
        finalEventObserved = true;

        % Include only non-control yellow, orange, and red balloon trials.
        keepTrial = ...
            isControl(trial) == 0 && ...
            isfinite(RTs(trial)) && ...
            RTs(trial) > 0 && ...
            RTs(trial) <= maximumRTSeconds && ...
            isfinite(durationSeconds) && ...
            durationSeconds > 0 && ...
            isfinite(balloonColorCode(trial)) && ...
            ismember(balloonColorCode(trial), [1 2 3]);

        if ~keepTrial
            continue;
        end

        trialRows = makePostIEDWindowRows( ...
            patientID, ...
            trial, ...
            durationSeconds, ...
            IEDoccurrence, ...
            samplingFrequencyHz, ...
            balloonColorCode(trial), ...
            finalEventObserved, ...
            postIEDWindowSeconds);

        countingProcessData = [countingProcessData; trialRows];

        if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 1
            nIEDsInTrial = 0;
        else
            nIEDsInTrial = sum( ...
                isfinite(IEDoccurrence(:, 1)) & ...
                round(IEDoccurrence(:, 1)) == trial);
        end

        totalPostIEDExposureSeconds = sum( ...
            (trialRows.tStop - trialRows.tStart) .* ...
            trialRows.post_ied_500ms, ...
            'omitnan');

        eventInPostIEDWindow = ...
            double(finalEventObserved && ...
            trialRows.post_ied_500ms(end) == 1);

        newTrialSummaryRow = table( ...
            patientID, ...
            trial, ...
            durationSeconds, ...
            double(finalEventObserved), ...
            eventInPostIEDWindow, ...
            nIEDsInTrial, ...
            totalPostIEDExposureSeconds, ...
            balloonColorCode(trial), ...
            samplingFrequencyHz, ...
            'VariableNames', { ...
                'patientID', ...
                'trialNumber', ...
                'durationSeconds', ...
                'eventObserved', ...
                'eventInPostIEDWindow', ...
                'nIEDsInFullDuration', ...
                'postIEDExposureSeconds', ...
                'balloonColorCode', ...
                'samplingFrequencyHz' ...
            });

        trialSummary = [trialSummary; newTrialSummaryRow];

    end

end

if isempty(countingProcessData)
    error('no valid counting-process rows were created.');
end

%% create predictors

[countingProcessData.patientStratum, patientLevels] = ...
    findgroups(countingProcessData.patientID);

if any(~ismember(countingProcessData.balloonColorCode, [1 2 3]))
    error('unexpected balloon color found. only yellow, orange, and red are allowed.');
end

observedColorLevels = unique( ...
    countingProcessData.balloonColorCode, 'sorted');

if ~all(ismember([1; 2; 3], observedColorLevels))
    error('yellow, orange, and red trials must all be present in the final data.');
end

% Predictor 1 is the number of individual IED windows active at each time.
% Each IED contributes separately, including multiple IEDs in one channel.
% Yellow is the reference balloon color.
X = countingProcessData.activeIEDWindowCount;
predictorNames = "active_ied_count_within_500ms";

X = [X, double(countingProcessData.balloonColorCode == 2)];
predictorNames(end + 1, 1) = "orange_vs_yellow";

X = [X, double(countingProcessData.balloonColorCode == 3)];
predictorNames(end + 1, 1) = "red_vs_yellow";

T = [countingProcessData.tStart, countingProcessData.tStop];
censoring = logical(countingProcessData.censored);
strata = countingProcessData.patientStratum;

validRows = ...
    all(isfinite(X), 2) & ...
    all(isfinite(T), 2) & ...
    T(:, 1) >= 0 & ...
    T(:, 2) > T(:, 1) & ...
    isfinite(strata);

X = X(validRows, :);
T = T(validRows, :);
censoring = censoring(validRows);
strata = strata(validRows);
countingProcessData = countingProcessData(validRows, :);

nEventsOutsideWindow = sum( ...
    countingProcessData.eventAtStop == 1 & ...
    countingProcessData.post_ied_500ms == 0);

nEventsInsideWindow = sum( ...
    countingProcessData.eventAtStop == 1 & ...
    countingProcessData.post_ied_500ms == 1);

timeOutsideWindowSeconds = sum( ...
    (countingProcessData.tStop - countingProcessData.tStart) .* ...
    (countingProcessData.post_ied_500ms == 0), ...
    'omitnan');

timeInsideWindowSeconds = sum( ...
    (countingProcessData.tStop - countingProcessData.tStart) .* ...
    (countingProcessData.post_ied_500ms == 1), ...
    'omitnan');

if timeInsideWindowSeconds <= 0
    error('no post-ied exposure time was available.');
end

if nEventsInsideWindow == 0 || nEventsOutsideWindow == 0
    fprintf(['note: one exposure state has zero observed endpoint events. ' ...
        'the cox estimate may be unstable.\n']);
end

%% fit participant-stratified cox proportional hazards model

coxOptions = statset('coxphfit');
coxOptions.Display = 'final';
coxOptions.MaxIter = 1000;
coxOptions.MaxFunEvals = 5000;

[beta, logLikelihood, baselineCumulativeHazard, stats] = ...
    coxphfit( ...
        X, ...
        T, ...
        'Censoring', censoring, ...
        'Strata', strata, ...
        'Ties', 'efron', ...
        'Baseline', 0, ...
        'Options', coxOptions);

%% participant-clustered robust inference

[clusterRobustCovariance, clusterRobustSE, ...
    clusterRobustZ, clusterRobustP] = ...
    computeClusterRobustInference( ...
        stats, ...
        beta, ...
        countingProcessData.patientStratum);

%% create results table

ciLowBeta = beta - 1.96 .* clusterRobustSE;
ciHighBeta = beta + 1.96 .* clusterRobustSE;

hazardRatio = exp(beta);
hazardRatioCILow = exp(ciLowBeta);
hazardRatioCIHigh = exp(ciHighBeta);

interpretation = strings(length(beta), 1);

for ii = 1:length(beta)

    if ii == 1
        interpretation(ii) = ...
            "hazard ratio is per additional active ied window; hr > 1 means " + ...
            "higher response hazard and shorter rt for each additional ied; " + ...
            "hr < 1 means lower response hazard and longer rt.";
    else
        interpretation(ii) = ...
            "balloon color effect relative to yellow";
    end

end

coxResults = table( ...
    predictorNames(:), ...
    beta(:), ...
    stats.se(:), ...
    stats.z(:), ...
    stats.p(:), ...
    clusterRobustSE(:), ...
    clusterRobustZ(:), ...
    clusterRobustP(:), ...
    ciLowBeta(:), ...
    ciHighBeta(:), ...
    hazardRatio(:), ...
    hazardRatioCILow(:), ...
    hazardRatioCIHigh(:), ...
    interpretation(:), ...
    'VariableNames', { ...
        'predictor', ...
        'beta_logHazard', ...
        'modelBasedSE', ...
        'modelBasedZ', ...
        'modelBasedPValue', ...
        'clusterRobustSE', ...
        'clusterRobustZ', ...
        'pValue', ...
        'betaCILow', ...
        'betaCIHigh', ...
        'hazardRatio', ...
        'hazardRatioCILow', ...
        'hazardRatioCIHigh', ...
        'interpretation' ...
    });

fprintf('\n============================================================\n');
fprintf('500 ms post-ied rt cox model\n');
fprintf('============================================================\n');
fprintf('post-ied window: %d ms\n', postIEDWindowMilliseconds);
fprintf('participants: %d\n', length(patientLevels));
fprintf('trials: %d\n', height(trialSummary));
fprintf('counting-process rows: %d\n', height(countingProcessData));
fprintf('events outside window: %d\n', nEventsOutsideWindow);
fprintf('events inside window: %d\n', nEventsInsideWindow);
fprintf('at-risk time outside window: %.3f s\n', timeOutsideWindowSeconds);
fprintf('at-risk time inside window: %.3f s\n', timeInsideWindowSeconds);
fprintf('log likelihood: %.6f\n\n', logLikelihood);

disp(coxResults);

primaryRow = coxResults(1, :);

fprintf('\neffect per additional active ied window:\n');
fprintf('beta = %.6f\n', primaryRow.beta_logHazard);
fprintf('hazard ratio per additional ied = %.6f\n', primaryRow.hazardRatio);
fprintf('95%% ci = [%.6f, %.6f]\n', ...
    primaryRow.hazardRatioCILow, ...
    primaryRow.hazardRatioCIHigh);
fprintf('p = %.6g\n', primaryRow.pValue);

if primaryRow.pValue < 0.05

    if primaryRow.hazardRatio > 1
        fprintf('conclusion: each additional active ied window is associated with a significantly higher response hazard and shorter rt.\n');
    else
        fprintf('conclusion: each additional active ied window is associated with a significantly lower response hazard and longer rt.\n');
    end

else
    fprintf('conclusion: the response hazard does not significantly change per additional active ied window.\n');
end

%% participant-level descriptive event rates

patientEventRates = calculatePatientEventRates( ...
    countingProcessData);

%% create model visualizations

observedIEDCounts = unique( ...
    countingProcessData.activeIEDWindowCount, 'sorted');

[visualizationFigure, modelEffectTable] = ...
    plotPostIEDVisualization( ...
        coxResults, ...
        patientEventRates, ...
        postIEDWindowMilliseconds, ...
        observedIEDCounts);

figurePDFOutputFile = fullfile( ...
    outputFolderName, 'RT_postIED500ms_cox_visualization.pdf');

modelEffectOutputFile = fullfile( ...
    outputFolderName, 'RT_postIED500ms_model_effect.csv');

patientRatesOutputFile = fullfile( ...
    outputFolderName, 'RT_postIED500ms_patient_event_rates.csv');

exportgraphics( ...
    visualizationFigure, ...
    figurePDFOutputFile, ...
    'ContentType', 'vector');

writetable(modelEffectTable, modelEffectOutputFile);
writetable(patientEventRates, patientRatesOutputFile);

close(visualizationFigure);

%% save numerical outputs

countingProcessOutputFile = fullfile( ...
    outputFolderName, 'RT_postIED500ms_counting_process_data.csv');

trialSummaryOutputFile = fullfile( ...
    outputFolderName, 'RT_postIED500ms_trial_summary.csv');

coxResultsOutputFile = fullfile( ...
    outputFolderName, 'RT_postIED500ms_cox_results.csv');

baselineHazardOutputFile = fullfile( ...
    outputFolderName, 'RT_postIED500ms_baseline_cumulative_hazard.csv');

modelOutputFile = fullfile( ...
    outputFolderName, 'RT_postIED500ms_cox_model.mat');

writetable(countingProcessData, countingProcessOutputFile);
writetable(trialSummary, trialSummaryOutputFile);
writetable(coxResults, coxResultsOutputFile);
writematrix(baselineCumulativeHazard, baselineHazardOutputFile);

save( ...
    modelOutputFile, ...
    'beta', ...
    'logLikelihood', ...
    'baselineCumulativeHazard', ...
    'stats', ...
    'clusterRobustCovariance', ...
    'clusterRobustSE', ...
    'clusterRobustZ', ...
    'clusterRobustP', ...
    'predictorNames', ...
    'patientLevels', ...
    'postIEDWindowMilliseconds', ...
    'postIEDWindowSeconds', ...
    'defaultSamplingFrequencyHz', ...
    'nEventsOutsideWindow', ...
    'nEventsInsideWindow', ...
    'timeOutsideWindowSeconds', ...
    'timeInsideWindowSeconds', ...
    'patientEventRates', ...
    'modelEffectTable', ...
    'observedIEDCounts');

fprintf('\nsaved:\n');
fprintf('%s\n', countingProcessOutputFile);
fprintf('%s\n', trialSummaryOutputFile);
fprintf('%s\n', coxResultsOutputFile);
fprintf('%s\n', baselineHazardOutputFile);
fprintf('%s\n', patientRatesOutputFile);
fprintf('%s\n', modelEffectOutputFile);
fprintf('%s\n', modelOutputFile);
fprintf('%s\n', figurePDFOutputFile);
fprintf('%s\n', textOutputFile);

% Stop writing to the text file now that all output has been printed.
diary off;
clear diaryCleanup;

%% local functions

function nTrials = determineNumberOfTrials( ...
    LFPIED, RTs, isControl, balloonType)

    vectorLengths = [ ...
        length(RTs), ...
        length(isControl), ...
        length(balloonType) ...
    ];

    if isfield(LFPIED, 'nTrials') && ...
            isscalar(LFPIED.nTrials) && ...
            isfinite(LFPIED.nTrials)

        vectorLengths(end + 1) = LFPIED.nTrials;

    end

    nTrials = floor(min(vectorLengths));

end

function samplingFrequencyHz = getSamplingFrequency( ...
    LFPIED, defaultSamplingFrequencyHz)

    if isfield(LFPIED, 'Fs') && ...
            isscalar(LFPIED.Fs) && ...
            isfinite(LFPIED.Fs) && ...
            LFPIED.Fs > 0

        samplingFrequencyHz = double(LFPIED.Fs);

    else

        samplingFrequencyHz = defaultSamplingFrequencyHz;

    end

end

function balloonColorCode = mapBalloonColorCode(balloonType)

    balloonType = double(balloonType(:));

    balloonColorCode = NaN(size(balloonType));

    validRows = ...
        isfinite(balloonType) & ...
        ismember(round(balloonType), [1 2 3 11 12 13]);

    balloonColorCode(validRows) = ...
        mod(round(balloonType(validRows)) - 1, 10) + 1;

end

function [robustCovariance, robustSE, robustZ, robustP] = ...
    computeClusterRobustInference(stats, beta, clusterID)

    beta = beta(:);
    nPredictors = length(beta);

    clusterID = clusterID(:);
    uniqueClusters = unique(clusterID(isfinite(clusterID)));
    nClusters = length(uniqueClusters);

    canUseClusterScores = ...
        isfield(stats, 'scores') && ...
        size(stats.scores, 1) == length(clusterID) && ...
        size(stats.scores, 2) == nPredictors;

    if nClusters < 2 || ~canUseClusterScores

        robustCovariance = stats.covb;
        robustSE = stats.se(:);
        robustZ = stats.z(:);
        robustP = stats.p(:);
        return;

    end

    clusterScoreSums = zeros(nClusters, nPredictors);

    for gg = 1:nClusters

        rows = clusterID == uniqueClusters(gg);

        thisClusterScores = stats.scores(rows, :);
        thisClusterScores(~isfinite(thisClusterScores)) = 0;

        clusterScoreSums(gg, :) = sum(thisClusterScores, 1);

    end

    meat = clusterScoreSums' * clusterScoreSums;
    bread = stats.covb;

    robustCovariance = bread * meat * bread;

    robustCovariance = ...
        (nClusters / (nClusters - 1)) .* robustCovariance;

    robustSE = sqrt(max(diag(robustCovariance), 0));

    zeroSERows = robustSE <= 0 | ~isfinite(robustSE);
    robustSE(zeroSERows) = stats.se(zeroSERows);

    robustZ = beta ./ robustSE;
    robustP = 2 .* normcdf(-abs(robustZ), 0, 1);

end

function trialRows = makePostIEDWindowRows( ...
    patientID, ...
    trialNumber, ...
    durationSeconds, ...
    IEDoccurrence, ...
    samplingFrequencyHz, ...
    balloonColorCode, ...
    finalEventObserved, ...
    postIEDWindowSeconds)

    % IEDoccurrence columns:
    %   1 = trial
    %   2 = channel
    %   3 = sample index inside the RT or IT interval

    if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 3

        IEDtimes = [];

    else

        validIEDRows = ...
            isfinite(IEDoccurrence(:, 1)) & ...
            isfinite(IEDoccurrence(:, 3)) & ...
            round(IEDoccurrence(:, 1)) == trialNumber & ...
            IEDoccurrence(:, 3) >= 1;

        sampleIndices = double(IEDoccurrence(validIEDRows, 3));

        IEDtimes = sampleIndices ./ samplingFrequencyHz;

        IEDtimes = IEDtimes( ...
            isfinite(IEDtimes) & ...
            IEDtimes > 0 & ...
            IEDtimes < durationSeconds);

        % Keep every IED occurrence; do not collapse duplicate times.
        IEDtimes = sort(IEDtimes);

    end

    if isempty(IEDtimes)

        breakTimes = [0; durationSeconds];

    else

        windowEndTimes = min( ...
            IEDtimes + postIEDWindowSeconds, ...
            durationSeconds);

        breakTimes = unique([ ...
            0; ...
            IEDtimes(:); ...
            windowEndTimes(:); ...
            durationSeconds ...
        ], 'sorted');

    end

    breakTimes = breakTimes( ...
        isfinite(breakTimes) & ...
        breakTimes >= 0 & ...
        breakTimes <= durationSeconds);

    breakTimes = unique(breakTimes, 'sorted');

    if length(breakTimes) < 2
        breakTimes = [0; durationSeconds];
    end

    tStart = breakTimes(1:end-1);
    tStop = breakTimes(2:end);

    validIntervals = tStop > tStart;

    tStart = tStart(validIntervals);
    tStop = tStop(validIntervals);

    intervalMidpoint = (tStart + tStop) ./ 2;

    postIED500ms = zeros(length(tStart), 1);
    activeIEDWindowCount = zeros(length(tStart), 1);
    timeSinceMostRecentIED = NaN(length(tStart), 1);

    for kk = 1:length(tStart)

        if isempty(IEDtimes)
            continue;
        end

        activeWindows = ...
            intervalMidpoint(kk) >= IEDtimes & ...
            intervalMidpoint(kk) <= ...
                (IEDtimes + postIEDWindowSeconds);

        activeIEDWindowCount(kk) = sum(activeWindows);
        postIED500ms(kk) = double(any(activeWindows));

        priorIEDtimes = IEDtimes(IEDtimes < intervalMidpoint(kk));

        if ~isempty(priorIEDtimes)
            timeSinceMostRecentIED(kk) = ...
                intervalMidpoint(kk) - max(priorIEDtimes);
        end

    end

    censored = true(length(tStart), 1);
    eventAtStop = false(length(tStart), 1);

    if finalEventObserved
        censored(end) = false;
        eventAtStop(end) = true;
    end

    trialRows = table( ...
        repmat(patientID, length(tStart), 1), ...
        repmat(trialNumber, length(tStart), 1), ...
        tStart, ...
        tStop, ...
        censored, ...
        eventAtStop, ...
        postIED500ms, ...
        activeIEDWindowCount, ...
        timeSinceMostRecentIED, ...
        repmat(balloonColorCode, length(tStart), 1), ...
        repmat(samplingFrequencyHz, length(tStart), 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'tStart', ...
            'tStop', ...
            'censored', ...
            'eventAtStop', ...
            'post_ied_500ms', ...
            'activeIEDWindowCount', ...
            'timeSinceMostRecentIED_seconds', ...
            'balloonColorCode', ...
            'samplingFrequencyHz' ...
        });

end

function patientEventRates = calculatePatientEventRates( ...
    countingProcessData)

    patientList = unique( ...
        countingProcessData.patientID, ...
        'stable');

    patientEventRates = table();

    for pp = 1:length(patientList)

        patientID = patientList(pp);

        rows = countingProcessData( ...
            countingProcessData.patientID == patientID, :);

        duration = rows.tStop - rows.tStart;

        outsideRows = rows.post_ied_500ms == 0;
        insideRows = rows.post_ied_500ms == 1;

        outsideTime = sum(duration(outsideRows), 'omitnan');
        insideTime = sum(duration(insideRows), 'omitnan');

        outsideEvents = sum( ...
            rows.eventAtStop(outsideRows) == 1);

        insideEvents = sum( ...
            rows.eventAtStop(insideRows) == 1);

        outsideRatePer100s = NaN;
        insideRatePer100s = NaN;

        if outsideTime > 0
            outsideRatePer100s = ...
                100 .* outsideEvents ./ outsideTime;
        end

        if insideTime > 0
            insideRatePer100s = ...
                100 .* insideEvents ./ insideTime;
        end

        crudeRateRatio = NaN;

        if isfinite(outsideRatePer100s) && ...
                isfinite(insideRatePer100s) && ...
                outsideRatePer100s > 0

            crudeRateRatio = ...
                insideRatePer100s ./ outsideRatePer100s;

        end

        newRow = table( ...
            patientID, ...
            outsideTime, ...
            insideTime, ...
            outsideEvents, ...
            insideEvents, ...
            outsideRatePer100s, ...
            insideRatePer100s, ...
            crudeRateRatio, ...
            'VariableNames', { ...
                'patientID', ...
                'outsideWindowTime_seconds', ...
                'postIEDWindowTime_seconds', ...
                'outsideWindowEvents', ...
                'postIEDWindowEvents', ...
                'outsideWindowRate_per100s', ...
                'postIEDWindowRate_per100s', ...
                'crudeRateRatio' ...
            });

        patientEventRates = [patientEventRates; newRow];

    end

end

function [fig, modelEffectTable] = plotPostIEDVisualization( ...
    coxResults, ...
    patientEventRates, ...
    postIEDWindowMilliseconds, ...
    observedIEDCounts)

    colorRT = [0.204  0.459  0.702];   % requested color
    lightColor = 0.75 .* [1 1 1] + 0.25 .* colorRT;

    fig = figure('Visible', 'off');
    set(fig, 'Position', [100 100 1150 520]);
    set(fig, 'Color', 'w');

    tiledlayout(1, 2, ...
        'Padding', 'compact', ...
        'TileSpacing', 'compact');

    %% panel 1: hazard-ratio forest plot

    nexttile;
    hold on;

    nPredictors = height(coxResults);
    yPositions = (1:nPredictors)';

    hazardRatio = coxResults.hazardRatio;
    lowerError = hazardRatio - coxResults.hazardRatioCILow;
    upperError = coxResults.hazardRatioCIHigh - hazardRatio;

    errorbar( ...
        hazardRatio, ...
        yPositions, ...
        lowerError, ...
        upperError, ...
        'horizontal', ...
        'o', ...
        'LineWidth', 1.2, ...
        'MarkerSize', 6, ...
        'MarkerFaceColor', colorRT, ...
        'MarkerEdgeColor', colorRT, ...
        'Color', colorRT, ...
        'CapSize', 7);

    xline(1, '--', ...
        'Color', colorRT, ...
        'LineWidth', 1);

    predictorLabels = [ ...
        "active ied count within 500 ms"; ...
        "orange vs yellow"; ...
        "red vs yellow" ...
    ];

    set(gca, ...
        'YTick', yPositions, ...
        'YTickLabel', predictorLabels, ...
        'YDir', 'reverse', ...
        'XScale', 'log', ...
        'FontSize', 10, ...
        'FontName', 'Arial', ...
        'XColor', 'k', ...
        'YColor', 'k');

    xlabel('hazard ratio with robust 95% ci', 'Color', 'k');
    title('cox model estimates', 'Color', 'k');

    xLimits = calculatePositiveLogLimits( ...
        coxResults.hazardRatioCILow, ...
        coxResults.hazardRatioCIHigh);

    % Add one asterisk beside estimates that are significant according to
    % the participant-clustered robust Wald test (p < 0.05).
    significantRows = ...
        isfinite(coxResults.pValue) & ...
        coxResults.pValue < 0.05 & ...
        isfinite(coxResults.hazardRatioCIHigh) & ...
        coxResults.hazardRatioCIHigh > 0;

    significanceX = NaN(nPredictors, 1);
    significanceX(significantRows) = ...
        1.10 .* coxResults.hazardRatioCIHigh(significantRows);

    % Leave enough room on the logarithmic x-axis for the asterisks.
    if any(significantRows)
        xLimits(2) = max( ...
            xLimits(2), ...
            1.15 .* max(significanceX(significantRows)));
    end

    xlim(xLimits);
    ylim([0.5, nPredictors + 0.5]);

    for ii = 1:nPredictors
        if significantRows(ii)
            text( ...
                significanceX(ii), ...
                yPositions(ii), ...
                '*', ...
                'Color', 'k', ...
                'FontSize', 16, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', 'left', ...
                'VerticalAlignment', 'middle');
        end
    end

    grid off;
    box off;
    hold off;

    %% panel 2: adjusted 500 ms post-IED effect

    nexttile;
    hold on;

    primaryRow = coxResults(1, :);

    exposureState = observedIEDCounts(:);
    exposureState = exposureState(isfinite(exposureState) & exposureState >= 0);
    exposureState = unique(exposureState, 'sorted');

    if isempty(exposureState)
        exposureState = [0; 1];
    elseif ~ismember(0, exposureState)
        exposureState = [0; exposureState];
    end

    relativeHazard = primaryRow.hazardRatio .^ exposureState;
    relativeHazardCILow = primaryRow.hazardRatioCILow .^ exposureState;
    relativeHazardCIHigh = primaryRow.hazardRatioCIHigh .^ exposureState;

    % Show the robust 95% CI as a shaded band rather than drawing an
    % error bar at every active-IED count. This keeps the panel readable
    % when the maximum observed count is large.
    fill( ...
        [exposureState; flipud(exposureState)], ...
        [relativeHazardCILow; flipud(relativeHazardCIHigh)], ...
        lightColor, ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.55);

    yline(1, '--', ...
        'Color', [0.45 0.45 0.45], ...
        'LineWidth', 1);

    plot( ...
        exposureState, ...
        relativeHazard, ...
        '-', ...
        'LineWidth', 2.2, ...
        'Color', colorRT);

    % Put markers only at a small set of representative observed counts.
    % The same values are used as x-axis ticks.
    xTickValues = chooseSparseObservedTicks(exposureState, 6);
    markerRows = ismember(exposureState, xTickValues);

    plot( ...
        exposureState(markerRows), ...
        relativeHazard(markerRows), ...
        'o', ...
        'LineStyle', 'none', ...
        'MarkerSize', 6, ...
        'MarkerFaceColor', colorRT, ...
        'MarkerEdgeColor', colorRT);

    xMinimum = min(exposureState);
    xMaximum = max(exposureState);

    if xMaximum == xMinimum
        xlim([xMinimum - 0.5, xMaximum + 0.5]);
    else
        xPadding = max(0.25, 0.02 .* (xMaximum - xMinimum));
        xlim([xMinimum - xPadding, xMaximum + xPadding]);
    end

    xticks(xTickValues);
    xticklabels(compose('%g', xTickValues));

    set(gca, ...
        'YScale', 'log', ...
        'FontSize', 10, ...
        'FontName', 'Arial', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'TickDir', 'out');

    xlabel('number of simultaneously active ied windows', 'Color', 'k');
    ylabel('relative response hazard vs 0 active ieds', 'Color', 'k');
    title('adjusted ied-count effect', 'Color', 'k');
    subtitle('line = estimate; shaded band = robust 95% ci');

    yLimits = calculatePositiveLogLimits( ...
        relativeHazardCILow, ...
        relativeHazardCIHigh);

    ylim(yLimits);

    resultText = sprintf( ...
        'hr per additional ied = %.3f\n95%% ci [%.3f, %.3f]\np = %.3g', ...
        primaryRow.hazardRatio, ...
        primaryRow.hazardRatioCILow, ...
        primaryRow.hazardRatioCIHigh, ...
        primaryRow.pValue);

    text( ...
        0.96, ...
        0.95, ...
        resultText, ...
        'Units', 'normalized', ...
        'VerticalAlignment', 'top', ...
        'HorizontalAlignment', 'right', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'Color', 'k', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', [0.80 0.80 0.80], ...
        'Margin', 5);

    grid off;
    box off;
    hold off;

    modelEffectTable = table( ...
        exposureState, ...
        relativeHazard, ...
        relativeHazardCILow, ...
        relativeHazardCIHigh, ...
        repmat(postIEDWindowMilliseconds, length(exposureState), 1), ...
        'VariableNames', { ...
            'activeIEDWindowCount', ...
            'relativeHazard', ...
            'relativeHazardCILow', ...
            'relativeHazardCIHigh', ...
            'postIEDWindowMilliseconds' ...
        });

end

function tickValues = chooseSparseObservedTicks(xValues, maximumNumberOfTicks)

    xValues = xValues(:);
    xValues = xValues(isfinite(xValues));
    xValues = unique(xValues, 'sorted');

    if isempty(xValues)
        tickValues = [0; 1];
        return;
    end

    if length(xValues) <= maximumNumberOfTicks
        tickValues = xValues;
        return;
    end

    targetValues = linspace( ...
        min(xValues), ...
        max(xValues), ...
        maximumNumberOfTicks);

    tickValues = NaN(maximumNumberOfTicks, 1);

    for tt = 1:maximumNumberOfTicks

        [~, closestRow] = min(abs(xValues - targetValues(tt)));
        tickValues(tt) = xValues(closestRow);

    end

    tickValues = unique([xValues(1); tickValues; xValues(end)], 'sorted');

end

function axisLimits = calculatePositiveLogLimits( ...
    lowerValues, ...
    upperValues)

    lowerValues = lowerValues(:);
    upperValues = upperValues(:);

    positiveLower = lowerValues( ...
        isfinite(lowerValues) & ...
        lowerValues > 0);

    positiveUpper = upperValues( ...
        isfinite(upperValues) & ...
        upperValues > 0);

    if isempty(positiveLower) || isempty(positiveUpper)
        axisLimits = [0.5 2];
        return;
    end

    minimumValue = min([positiveLower; positiveUpper; 1]);
    maximumValue = max([positiveLower; positiveUpper; 1]);

    logMinimum = log10(minimumValue);
    logMaximum = log10(maximumValue);

    if logMaximum == logMinimum

        logMinimum = logMinimum - 0.2;
        logMaximum = logMaximum + 0.2;

    else

        padding = 0.10 .* (logMaximum - logMinimum);

        logMinimum = logMinimum - padding;
        logMaximum = logMaximum + padding;

    end

    axisLimits = [10^logMinimum, 10^logMaximum];

end
