% Combined participant-stratified Cox analyses for IT, RT, and BR

%
% Author: Nill

clear;
clc;
close all;

%% Paths and shared analysis settings

inputFolderName_LFPIED = ...
    'D:\Nill\data\BART\0_0_new_IED\IED1_find_number_of_IEDs\';

outputFolderName = ...
    'D:\Nill\code\BART\IED\0_0_new_IED\IED7_2_Cox_IT_RT_BR_postIED_count\';

if ~exist(outputFolderName, 'dir')
    mkdir(outputFolderName);
end

textOutputFile = fullfile( ...
    outputFolderName, ...
    'IT_RT_BR_postIED_RT500ms_IT_BR1000ms_console_output.txt');

% Start a fresh console-output text file for every run.
diary off;
if exist(textOutputFile, 'file')
    delete(textOutputFile);
end
diary(textOutputFile);
diaryCleanup = onCleanup(@() diary('off'));

defaultSamplingFrequencyHz = 1000;
maximumRTSeconds = 20;

% Requested plotting colors.
colorIT = [0.847  0.333  0.153];
colorRT = [0.204  0.459  0.702];
colorBR = [0.250  0.600  0.250];

%% Analysis definitions

analysisConfigs(1) = struct( ...
    'code', "IT", ...
    'displayName', "Inflation time", ...
    'durationField', "ITs", ...
    'iedField', "IED_occurance_IT", ...
    'eventMode', "allEndpoints", ...
    'postIEDWindowMilliseconds', 1000, ...
    'color', colorIT, ...
    'hazardLabel', "action", ...
    'durationLabel', "IT");

analysisConfigs(2) = struct( ...
    'code', "RT", ...
    'displayName', "Response time", ...
    'durationField', "RTs", ...
    'iedField', "IED_occurance_RT", ...
    'eventMode', "allEndpoints", ...
    'postIEDWindowMilliseconds', 500, ...
    'color', colorRT, ...
    'hazardLabel', "response", ...
    'durationLabel', "RT");

analysisConfigs(3) = struct( ...
    'code', "BR", ...
    'displayName', "Banking response", ...
    'durationField', "ITs", ...
    'iedField', "IED_occurance_IT", ...
    'eventMode', "bankedOnly", ...
    'postIEDWindowMilliseconds', 1000, ...
    'color', colorBR, ...
    'hazardLabel', "banking", ...
    'durationLabel', "IT");

%% Run all three analyses

analysisResults = struct();

for aa = 1:length(analysisConfigs)

    fprintf('\n\n');
    fprintf('############################################################\n');
    fprintf('RUNNING %s ANALYSIS\n', char(analysisConfigs(aa).code));
    fprintf('############################################################\n');

    currentResult = runPostIEDCoxAnalysis( ...
        inputFolderName_LFPIED, ...
        analysisConfigs(aa), ...
        defaultSamplingFrequencyHz, ...
        maximumRTSeconds);

    % The first returned structure defines the fields of the structure array.
    % Direct assignment avoids MATLAB's "dissimilar structures" error that
    % occurs when assigning a populated structure into struct([]).
    if aa == 1
        analysisResults = currentResult;
    else
        analysisResults(aa) = currentResult; 
    end

end

%% Save numerical outputs for each analysis
% No individual visualization PDFs are created.

for aa = 1:length(analysisConfigs)

    code = char(analysisConfigs(aa).code);
    result = analysisResults(aa);
    windowMilliseconds = ...
        analysisConfigs(aa).postIEDWindowMilliseconds;

    writetable( ...
        result.countingProcessData, ...
        fullfile(outputFolderName, ...
            sprintf('%s_postIED%dms_counting_process_data.csv', ...
            code, windowMilliseconds)));

    writetable( ...
        result.trialSummary, ...
        fullfile(outputFolderName, ...
            sprintf('%s_postIED%dms_trial_summary.csv', ...
            code, windowMilliseconds)));

    writetable( ...
        result.coxResults, ...
        fullfile(outputFolderName, ...
            sprintf('%s_postIED%dms_cox_results.csv', ...
            code, windowMilliseconds)));

    writematrix( ...
        result.baselineCumulativeHazard, ...
        fullfile(outputFolderName, ...
            sprintf('%s_postIED%dms_baseline_cumulative_hazard.csv', ...
            code, windowMilliseconds)));

    writetable( ...
        result.patientEventRates, ...
        fullfile(outputFolderName, ...
            sprintf('%s_postIED%dms_patient_event_rates.csv', ...
            code, windowMilliseconds)));

    writetable( ...
        result.modelEffectTable, ...
        fullfile(outputFolderName, ...
            sprintf('%s_postIED%dms_model_effect.csv', ...
            code, windowMilliseconds)));

end

combinedModelOutputFile = fullfile( ...
    outputFolderName, ...
    'IT_RT_BR_postIED_RT500ms_IT_BR1000ms_combined_results.mat');

save( ...
    combinedModelOutputFile, ...
    'analysisResults', ...
    'analysisConfigs', ...
    'defaultSamplingFrequencyHz', ...
    'maximumRTSeconds', ...
    '-v7.3');

%% Create one 3-by-2 visualization PDF

combinedFigure = createCombinedVisualization( ...
    analysisResults, ...
    analysisConfigs);

combinedPDFOutputFile = fullfile( ...
    outputFolderName, ...
    'IT_RT_BR_postIED_RT500ms_IT_BR1000ms_cox_visualization_3x2.pdf');

exportgraphics( ...
    combinedFigure, ...
    combinedPDFOutputFile, ...
    'ContentType', 'vector');

close(combinedFigure);

fprintf('\n============================================================\n');
fprintf('COMBINED ANALYSIS COMPLETE\n');
fprintf('============================================================\n');
fprintf('One visualization PDF saved:\n%s\n', combinedPDFOutputFile);
fprintf('Combined MAT file saved:\n%s\n', combinedModelOutputFile);
fprintf('Console output saved:\n%s\n', textOutputFile);

% Stop writing to the diary after all paths have been printed.
diary off;
clear diaryCleanup;

%% Local functions

function result = runPostIEDCoxAnalysis( ...
    inputFolderName_LFPIED, ...
    config, ...
    defaultSamplingFrequencyHz, ...
    maximumRTSeconds)

    codeChar = char(config.code);
    hazardLabelChar = char(config.hazardLabel);
    postIEDWindowMilliseconds = config.postIEDWindowMilliseconds;
    postIEDWindowSeconds = postIEDWindowMilliseconds / 1000;

    fileList = dir(fullfile( ...
        inputFolderName_LFPIED, '*.LFPIED.mat'));

    countingProcessData = table();
    trialSummary = table();

    requiredFields = { ...
        'RTs', ...
        'isControl', ...
        'balloonType', ...
        char(config.durationField), ...
        char(config.iedField) ...
    };

    if config.eventMode == "bankedOnly"
        requiredFields{end + 1} = 'BankedTrials';
    end

    requiredFields = unique(requiredFields, 'stable');

    %% Build counting-process data across all participants

    for pt = 1:length(fileList)

        fileName = fileList(pt).name;
        fileNameParts = strsplit(fileName, '.');
        patientID = string(fileNameParts{1});

        fprintf('\n%s: processing patient %s\n', ...
            codeChar, char(patientID));

        loadedData = load(fullfile( ...
            inputFolderName_LFPIED, fileName));

        if ~isfield(loadedData, 'LFPIED')
            fprintf('%s: skipped; LFPIED structure was not found.\n', ...
                codeChar);
            continue;
        end

        LFPIED = loadedData.LFPIED;

        missingField = false;

        for ff = 1:length(requiredFields)
            if ~isfield(LFPIED, requiredFields{ff})
                fprintf('%s: skipped; missing field %s.\n', ...
                    codeChar, requiredFields{ff});
                missingField = true;
            end
        end

        if missingField
            continue;
        end

        RTs = LFPIED.RTs(:);
        durationValues = LFPIED.(char(config.durationField));
        durationValues = durationValues(:);
        isControl = LFPIED.isControl(:);
        balloonType = LFPIED.balloonType(:);

        if config.eventMode == "bankedOnly"
            bankedTrials = LFPIED.BankedTrials(:);
        else
            bankedTrials = NaN(size(durationValues));
        end

        vectorLengths = [ ...
            length(RTs), ...
            length(durationValues), ...
            length(isControl), ...
            length(balloonType) ...
        ];

        if config.eventMode == "bankedOnly"
            vectorLengths(end + 1) = length(bankedTrials);
        end

        if isfield(LFPIED, 'nTrials') && ...
                isscalar(LFPIED.nTrials) && ...
                isfinite(LFPIED.nTrials)
            vectorLengths(end + 1) = double(LFPIED.nTrials);
        end

        nTrials = floor(min(vectorLengths));

        RTs = RTs(1:nTrials);
        durationValues = durationValues(1:nTrials);
        isControl = isControl(1:nTrials);
        balloonType = balloonType(1:nTrials);
        bankedTrials = bankedTrials(1:nTrials);

        balloonColorCode = mapBalloonColorCode(balloonType);

        samplingFrequencyHz = getSamplingFrequency( ...
            LFPIED, defaultSamplingFrequencyHz);

        IEDoccurrence = LFPIED.(char(config.iedField));

        for trial = 1:nTrials

            durationSeconds = durationValues(trial);

            if config.eventMode == "bankedOnly"
                finalEventObserved = bankedTrials(trial) == 1;
            else
                finalEventObserved = true;
            end

            keepTrial = ...
                isControl(trial) == 0 && ...
                isfinite(RTs(trial)) && ...
                RTs(trial) > 0 && ...
                RTs(trial) <= maximumRTSeconds && ...
                isfinite(durationSeconds) && ...
                durationSeconds > 0 && ...
                isfinite(balloonColorCode(trial)) && ...
                ismember(balloonColorCode(trial), [1 2 3]);

            if config.eventMode == "bankedOnly"
                keepTrial = keepTrial && ...
                    isfinite(bankedTrials(trial)) && ...
                    ismember(bankedTrials(trial), [0 1]);
            end

            if ~keepTrial
                continue;
            end

            trialRows = makePostIEDWindowRows( ...
                patientID, ...
                trial, ...
                durationSeconds, ...
                IEDoccurrence, ...
                samplingFrequencyHz, ...
                balloonColorCode(trial), ...
                finalEventObserved, ...
                postIEDWindowSeconds);

            countingProcessData = [countingProcessData; trialRows]; 

            if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 1
                nIEDsInTrial = 0;
            else
                nIEDsInTrial = sum( ...
                    isfinite(IEDoccurrence(:, 1)) & ...
                    round(IEDoccurrence(:, 1)) == trial);
            end

            totalPostIEDExposureSeconds = sum( ...
                (trialRows.tStop - trialRows.tStart) .* ...
                trialRows.postIED, ...
                'omitnan');

            eventInPostIEDWindow = ...
                double(finalEventObserved && ...
                trialRows.postIED(end) == 1);

            if config.eventMode == "bankedOnly"
                bankedTrialValue = bankedTrials(trial);
            else
                bankedTrialValue = NaN;
            end

            newTrialSummaryRow = table( ...
                patientID, ...
                trial, ...
                durationSeconds, ...
                bankedTrialValue, ...
                double(finalEventObserved), ...
                eventInPostIEDWindow, ...
                nIEDsInTrial, ...
                totalPostIEDExposureSeconds, ...
                balloonColorCode(trial), ...
                samplingFrequencyHz, ...
                'VariableNames', { ...
                    'patientID', ...
                    'trialNumber', ...
                    'durationSeconds', ...
                    'bankedTrial', ...
                    'eventObserved', ...
                    'eventInPostIEDWindow', ...
                    'nIEDsInFullDuration', ...
                    'postIEDExposureSeconds', ...
                    'balloonColorCode', ...
                    'samplingFrequencyHz' ...
                });

            trialSummary = [trialSummary; newTrialSummaryRow]; 

        end

    end

    if isempty(countingProcessData)
        error('%s: no valid counting-process rows were created.', ...
            codeChar);
    end

    %% Create predictors

    [countingProcessData.patientStratum, patientLevels] = ...
        findgroups(countingProcessData.patientID);

    if any(~ismember(countingProcessData.balloonColorCode, [1 2 3]))
        error('%s: unexpected balloon color found.', codeChar);
    end

    observedColorLevels = unique( ...
        countingProcessData.balloonColorCode, 'sorted');

    if ~all(ismember([1; 2; 3], observedColorLevels))
        error('%s: yellow, orange, and red must all be present.', ...
            codeChar);
    end

    % Yellow is the reference balloon color.
    X = countingProcessData.activeIEDWindowCount;
    predictorNames = "active_ied_count_within_" + ...
        string(postIEDWindowMilliseconds) + "ms";

    X = [X, double(countingProcessData.balloonColorCode == 2)];
    predictorNames(end + 1, 1) = "orange_vs_yellow";

    X = [X, double(countingProcessData.balloonColorCode == 3)];
    predictorNames(end + 1, 1) = "red_vs_yellow";

    T = [countingProcessData.tStart, countingProcessData.tStop];
    censoring = logical(countingProcessData.censored);
    strata = countingProcessData.patientStratum;

    validRows = ...
        all(isfinite(X), 2) & ...
        all(isfinite(T), 2) & ...
        T(:, 1) >= 0 & ...
        T(:, 2) > T(:, 1) & ...
        isfinite(strata);

    X = X(validRows, :);
    T = T(validRows, :);
    censoring = censoring(validRows);
    strata = strata(validRows);
    countingProcessData = countingProcessData(validRows, :);

    nEventsOutsideWindow = sum( ...
        countingProcessData.eventAtStop == 1 & ...
        countingProcessData.postIED == 0);

    nEventsInsideWindow = sum( ...
        countingProcessData.eventAtStop == 1 & ...
        countingProcessData.postIED == 1);

    timeOutsideWindowSeconds = sum( ...
        (countingProcessData.tStop - countingProcessData.tStart) .* ...
        (countingProcessData.postIED == 0), ...
        'omitnan');

    timeInsideWindowSeconds = sum( ...
        (countingProcessData.tStop - countingProcessData.tStart) .* ...
        (countingProcessData.postIED == 1), ...
        'omitnan');

    if timeInsideWindowSeconds <= 0
        error('%s: no post-IED exposure time was available.', ...
            codeChar);
    end

    if nEventsInsideWindow == 0 || nEventsOutsideWindow == 0
        fprintf(['%s note: one exposure state has zero observed endpoint ' ...
            'events; the Cox estimate may be unstable.\n'], codeChar);
    end

    %% Fit participant-stratified Cox proportional hazards model

    coxOptions = statset('coxphfit');
    coxOptions.Display = 'final';
    coxOptions.MaxIter = 1000;
    coxOptions.MaxFunEvals = 5000;

    [beta, logLikelihood, baselineCumulativeHazard, stats] = ...
        coxphfit( ...
            X, ...
            T, ...
            'Censoring', censoring, ...
            'Strata', strata, ...
            'Ties', 'efron', ...
            'Baseline', 0, ...
            'Options', coxOptions);

    %% Participant-clustered robust inference

    [clusterRobustCovariance, clusterRobustSE, ...
        clusterRobustZ, clusterRobustP] = ...
        computeClusterRobustInference( ...
            stats, ...
            beta, ...
            countingProcessData.patientStratum);

    %% Create results table

    ciLowBeta = beta - 1.96 .* clusterRobustSE;
    ciHighBeta = beta + 1.96 .* clusterRobustSE;

    hazardRatio = exp(beta);
    hazardRatioCILow = exp(ciLowBeta);
    hazardRatioCIHigh = exp(ciHighBeta);

    interpretation = strings(length(beta), 1);

    if config.code == "IT"
        primaryInterpretation = ...
            "HR is per additional active IED window; HR > 1 means " + ...
            "higher action hazard and shorter IT; HR < 1 means " + ...
            "lower action hazard and longer IT.";
    elseif config.code == "RT"
        primaryInterpretation = ...
            "HR is per additional active IED window; HR > 1 means " + ...
            "higher response hazard and shorter RT; HR < 1 means " + ...
            "lower response hazard and longer RT.";
    else
        primaryInterpretation = ...
            "HR is per additional active IED window; HR > 1 means " + ...
            "higher instantaneous banking hazard; HR < 1 means lower " + ...
            "banking hazard. Non-banked or popped trials are censored.";
    end

    interpretation(1) = primaryInterpretation;
    interpretation(2:end) = "Balloon-color effect relative to yellow.";

    coxResults = table( ...
        predictorNames(:), ...
        beta(:), ...
        stats.se(:), ...
        stats.z(:), ...
        stats.p(:), ...
        clusterRobustSE(:), ...
        clusterRobustZ(:), ...
        clusterRobustP(:), ...
        ciLowBeta(:), ...
        ciHighBeta(:), ...
        hazardRatio(:), ...
        hazardRatioCILow(:), ...
        hazardRatioCIHigh(:), ...
        interpretation(:), ...
        'VariableNames', { ...
            'predictor', ...
            'beta_logHazard', ...
            'modelBasedSE', ...
            'modelBasedZ', ...
            'modelBasedPValue', ...
            'clusterRobustSE', ...
            'clusterRobustZ', ...
            'pValue', ...
            'betaCILow', ...
            'betaCIHigh', ...
            'hazardRatio', ...
            'hazardRatioCILow', ...
            'hazardRatioCIHigh', ...
            'interpretation' ...
        });

    %% Print summary

    fprintf('\n============================================================\n');
    fprintf('%s: %d-ms post-IED Cox model\n', ...
        codeChar, postIEDWindowMilliseconds);
    fprintf('============================================================\n');
    fprintf('post-IED window: %d ms\n', postIEDWindowMilliseconds);
    fprintf('participants: %d\n', length(patientLevels));
    fprintf('trials: %d\n', height(trialSummary));
    fprintf('counting-process rows: %d\n', height(countingProcessData));
    fprintf('events outside window: %d\n', nEventsOutsideWindow);
    fprintf('events inside window: %d\n', nEventsInsideWindow);
    fprintf('at-risk time outside window: %.3f s\n', ...
        timeOutsideWindowSeconds);
    fprintf('at-risk time inside window: %.3f s\n', ...
        timeInsideWindowSeconds);
    fprintf('log likelihood: %.6f\n\n', logLikelihood);

    disp(coxResults);

    primaryRow = coxResults(1, :);

    fprintf('\n%s effect per additional active IED window:\n', ...
        codeChar);
    fprintf('beta = %.6f\n', primaryRow.beta_logHazard);
    fprintf('hazard ratio = %.6f\n', primaryRow.hazardRatio);
    fprintf('95%% CI = [%.6f, %.6f]\n', ...
        primaryRow.hazardRatioCILow, ...
        primaryRow.hazardRatioCIHigh);
    fprintf('p = %.6g\n', primaryRow.pValue);

    if primaryRow.pValue < 0.05
        if primaryRow.hazardRatio > 1
            fprintf('conclusion: significantly higher %s hazard.\n', ...
                hazardLabelChar);
        else
            fprintf('conclusion: significantly lower %s hazard.\n', ...
                hazardLabelChar);
        end
    else
        fprintf('conclusion: no significant change in %s hazard.\n', ...
            hazardLabelChar);
    end

    %% Descriptive participant event rates and adjusted effect curve

    patientEventRates = calculatePatientEventRates( ...
        countingProcessData);

    observedIEDCounts = unique( ...
        countingProcessData.activeIEDWindowCount, 'sorted');

    modelEffectTable = createModelEffectTable( ...
        coxResults, ...
        postIEDWindowMilliseconds, ...
        observedIEDCounts);

    %% Return all analysis outputs

    result = struct();
    result.code = config.code;
    result.countingProcessData = countingProcessData;
    result.trialSummary = trialSummary;
    result.coxResults = coxResults;
    result.beta = beta;
    result.logLikelihood = logLikelihood;
    result.baselineCumulativeHazard = baselineCumulativeHazard;
    result.stats = stats;
    result.clusterRobustCovariance = clusterRobustCovariance;
    result.clusterRobustSE = clusterRobustSE;
    result.clusterRobustZ = clusterRobustZ;
    result.clusterRobustP = clusterRobustP;
    result.predictorNames = predictorNames;
    result.patientLevels = patientLevels;
    result.nEventsOutsideWindow = nEventsOutsideWindow;
    result.nEventsInsideWindow = nEventsInsideWindow;
    result.timeOutsideWindowSeconds = timeOutsideWindowSeconds;
    result.timeInsideWindowSeconds = timeInsideWindowSeconds;
    result.patientEventRates = patientEventRates;
    result.observedIEDCounts = observedIEDCounts;
    result.modelEffectTable = modelEffectTable;
    result.postIEDWindowMilliseconds = postIEDWindowMilliseconds;

end

function samplingFrequencyHz = getSamplingFrequency( ...
    LFPIED, defaultSamplingFrequencyHz)

    if isfield(LFPIED, 'Fs') && ...
            isscalar(LFPIED.Fs) && ...
            isfinite(LFPIED.Fs) && ...
            LFPIED.Fs > 0

        samplingFrequencyHz = double(LFPIED.Fs);

    else

        samplingFrequencyHz = defaultSamplingFrequencyHz;

    end

end

function balloonColorCode = mapBalloonColorCode(balloonType)

    balloonType = double(balloonType(:));
    balloonColorCode = NaN(size(balloonType));

    validRows = ...
        isfinite(balloonType) & ...
        ismember(round(balloonType), [1 2 3 11 12 13]);

    balloonColorCode(validRows) = ...
        mod(round(balloonType(validRows)) - 1, 10) + 1;

end

function [robustCovariance, robustSE, robustZ, robustP] = ...
    computeClusterRobustInference(stats, beta, clusterID)

    beta = beta(:);
    nPredictors = length(beta);

    clusterID = clusterID(:);
    uniqueClusters = unique(clusterID(isfinite(clusterID)));
    nClusters = length(uniqueClusters);

    canUseClusterScores = ...
        isfield(stats, 'scores') && ...
        size(stats.scores, 1) == length(clusterID) && ...
        size(stats.scores, 2) == nPredictors;

    if nClusters < 2 || ~canUseClusterScores

        robustCovariance = stats.covb;
        robustSE = stats.se(:);
        robustZ = stats.z(:);
        robustP = stats.p(:);
        return;

    end

    clusterScoreSums = zeros(nClusters, nPredictors);

    for gg = 1:nClusters

        rows = clusterID == uniqueClusters(gg);

        thisClusterScores = stats.scores(rows, :);
        thisClusterScores(~isfinite(thisClusterScores)) = 0;

        clusterScoreSums(gg, :) = sum(thisClusterScores, 1);

    end

    meat = clusterScoreSums' * clusterScoreSums;
    bread = stats.covb;

    robustCovariance = bread * meat * bread;
    robustCovariance = ...
        (nClusters / (nClusters - 1)) .* robustCovariance;

    robustSE = sqrt(max(diag(robustCovariance), 0));

    zeroSERows = robustSE <= 0 | ~isfinite(robustSE);
    robustSE(zeroSERows) = stats.se(zeroSERows);

    robustZ = beta ./ robustSE;
    robustP = 2 .* normcdf(-abs(robustZ), 0, 1);

end

function trialRows = makePostIEDWindowRows( ...
    patientID, ...
    trialNumber, ...
    durationSeconds, ...
    IEDoccurrence, ...
    samplingFrequencyHz, ...
    balloonColorCode, ...
    finalEventObserved, ...
    postIEDWindowSeconds)

    % IEDoccurrence columns:
    %   1 = trial
    %   2 = channel
    %   3 = sample index inside the RT or IT interval

    if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 3

        IEDtimes = [];

    else

        validIEDRows = ...
            isfinite(IEDoccurrence(:, 1)) & ...
            isfinite(IEDoccurrence(:, 3)) & ...
            round(IEDoccurrence(:, 1)) == trialNumber & ...
            IEDoccurrence(:, 3) >= 1;

        sampleIndices = double(IEDoccurrence(validIEDRows, 3));
        IEDtimes = sampleIndices ./ samplingFrequencyHz;

        IEDtimes = IEDtimes( ...
            isfinite(IEDtimes) & ...
            IEDtimes > 0 & ...
            IEDtimes < durationSeconds);

        % Keep every IED occurrence; do not collapse duplicate times.
        IEDtimes = sort(IEDtimes);

    end

    if isempty(IEDtimes)

        breakTimes = [0; durationSeconds];

    else

        windowEndTimes = min( ...
            IEDtimes + postIEDWindowSeconds, ...
            durationSeconds);

        breakTimes = unique([ ...
            0; ...
            IEDtimes(:); ...
            windowEndTimes(:); ...
            durationSeconds ...
        ], 'sorted');

    end

    breakTimes = breakTimes( ...
        isfinite(breakTimes) & ...
        breakTimes >= 0 & ...
        breakTimes <= durationSeconds);

    breakTimes = unique(breakTimes, 'sorted');

    if length(breakTimes) < 2
        breakTimes = [0; durationSeconds];
    end

    tStart = breakTimes(1:end-1);
    tStop = breakTimes(2:end);

    validIntervals = tStop > tStart;
    tStart = tStart(validIntervals);
    tStop = tStop(validIntervals);

    intervalMidpoint = (tStart + tStop) ./ 2;

    postIED = zeros(length(tStart), 1);
    activeIEDWindowCount = zeros(length(tStart), 1);
    timeSinceMostRecentIED = NaN(length(tStart), 1);

    for kk = 1:length(tStart)

        if isempty(IEDtimes)
            continue;
        end

        activeWindows = ...
            intervalMidpoint(kk) >= IEDtimes & ...
            intervalMidpoint(kk) <= ...
                (IEDtimes + postIEDWindowSeconds);

        activeIEDWindowCount(kk) = sum(activeWindows);
        postIED(kk) = double(any(activeWindows));

        priorIEDtimes = IEDtimes(IEDtimes < intervalMidpoint(kk));

        if ~isempty(priorIEDtimes)
            timeSinceMostRecentIED(kk) = ...
                intervalMidpoint(kk) - max(priorIEDtimes);
        end

    end

    censored = true(length(tStart), 1);
    eventAtStop = false(length(tStart), 1);

    if finalEventObserved
        censored(end) = false;
        eventAtStop(end) = true;
    end

    trialRows = table( ...
        repmat(patientID, length(tStart), 1), ...
        repmat(trialNumber, length(tStart), 1), ...
        tStart, ...
        tStop, ...
        censored, ...
        eventAtStop, ...
        postIED, ...
        activeIEDWindowCount, ...
        timeSinceMostRecentIED, ...
        repmat(balloonColorCode, length(tStart), 1), ...
        repmat(samplingFrequencyHz, length(tStart), 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'tStart', ...
            'tStop', ...
            'censored', ...
            'eventAtStop', ...
            'postIED', ...
            'activeIEDWindowCount', ...
            'timeSinceMostRecentIED_seconds', ...
            'balloonColorCode', ...
            'samplingFrequencyHz' ...
        });

end

function patientEventRates = calculatePatientEventRates( ...
    countingProcessData)

    patientList = unique( ...
        countingProcessData.patientID, ...
        'stable');

    patientEventRates = table();

    for pp = 1:length(patientList)

        patientID = patientList(pp);

        rows = countingProcessData( ...
            countingProcessData.patientID == patientID, :);

        duration = rows.tStop - rows.tStart;

        outsideRows = rows.postIED == 0;
        insideRows = rows.postIED == 1;

        outsideTime = sum(duration(outsideRows), 'omitnan');
        insideTime = sum(duration(insideRows), 'omitnan');

        outsideEvents = sum(rows.eventAtStop(outsideRows) == 1);
        insideEvents = sum(rows.eventAtStop(insideRows) == 1);

        outsideRatePer100s = NaN;
        insideRatePer100s = NaN;

        if outsideTime > 0
            outsideRatePer100s = ...
                100 .* outsideEvents ./ outsideTime;
        end

        if insideTime > 0
            insideRatePer100s = ...
                100 .* insideEvents ./ insideTime;
        end

        crudeRateRatio = NaN;

        if isfinite(outsideRatePer100s) && ...
                isfinite(insideRatePer100s) && ...
                outsideRatePer100s > 0

            crudeRateRatio = ...
                insideRatePer100s ./ outsideRatePer100s;

        end

        newRow = table( ...
            patientID, ...
            outsideTime, ...
            insideTime, ...
            outsideEvents, ...
            insideEvents, ...
            outsideRatePer100s, ...
            insideRatePer100s, ...
            crudeRateRatio, ...
            'VariableNames', { ...
                'patientID', ...
                'outsideWindowTime_seconds', ...
                'postIEDWindowTime_seconds', ...
                'outsideWindowEvents', ...
                'postIEDWindowEvents', ...
                'outsideWindowRate_per100s', ...
                'postIEDWindowRate_per100s', ...
                'crudeRateRatio' ...
            });

        patientEventRates = [patientEventRates; newRow]; 

    end

end

function modelEffectTable = createModelEffectTable( ...
    coxResults, ...
    postIEDWindowMilliseconds, ...
    observedIEDCounts)

    primaryRow = coxResults(1, :);

    exposureState = observedIEDCounts(:);
    exposureState = exposureState( ...
        isfinite(exposureState) & exposureState >= 0);
    exposureState = unique(exposureState, 'sorted');

    if isempty(exposureState)
        exposureState = [0; 1];
    elseif ~ismember(0, exposureState)
        exposureState = [0; exposureState];
    end

    relativeHazard = primaryRow.hazardRatio .^ exposureState;
    relativeHazardCILow = primaryRow.hazardRatioCILow .^ exposureState;
    relativeHazardCIHigh = primaryRow.hazardRatioCIHigh .^ exposureState;

    modelEffectTable = table( ...
        exposureState, ...
        relativeHazard, ...
        relativeHazardCILow, ...
        relativeHazardCIHigh, ...
        repmat(postIEDWindowMilliseconds, length(exposureState), 1), ...
        'VariableNames', { ...
            'activeIEDWindowCount', ...
            'relativeHazard', ...
            'relativeHazardCILow', ...
            'relativeHazardCIHigh', ...
            'postIEDWindowMilliseconds' ...
        });

end

function fig = createCombinedVisualization( ...
    analysisResults, ...
    analysisConfigs)

    fig = figure('Visible', 'off');
    set(fig, 'Position', [80 40 1450 1550]);
    set(fig, 'Color', 'w');

    layout = tiledlayout(fig, 3, 2, ...
        'Padding', 'compact', ...
        'TileSpacing', 'compact');

    sgtitle(layout, ...
        ['Participant-stratified Cox models: RT 500-ms; ' ...
        'IT and BR 1000-ms post-IED windows'], ...
        'FontName', 'Arial', ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Color', 'k');

    for aa = 1:length(analysisConfigs)

        forestAxis = nexttile(layout, (aa - 1) * 2 + 1);
        plotForestPanel( ...
            forestAxis, ...
            analysisResults(aa).coxResults, ...
            analysisConfigs(aa));

        effectAxis = nexttile(layout, (aa - 1) * 2 + 2);
        plotAdjustedEffectPanel( ...
            effectAxis, ...
            analysisResults(aa).coxResults, ...
            analysisResults(aa).modelEffectTable, ...
            analysisConfigs(aa));

    end

end

function plotForestPanel(ax, coxResults, config)

    hold(ax, 'on');

    nPredictors = height(coxResults);
    yPositions = (1:nPredictors)';

    hazardRatio = coxResults.hazardRatio;
    lowerError = hazardRatio - coxResults.hazardRatioCILow;
    upperError = coxResults.hazardRatioCIHigh - hazardRatio;

    errorbar( ...
        ax, ...
        hazardRatio, ...
        yPositions, ...
        lowerError, ...
        upperError, ...
        'horizontal', ...
        'o', ...
        'LineWidth', 1.2, ...
        'MarkerSize', 6, ...
        'MarkerFaceColor', config.color, ...
        'MarkerEdgeColor', config.color, ...
        'Color', config.color, ...
        'CapSize', 7);

    xline(ax, 1, '--', ...
        'Color', config.color, ...
        'LineWidth', 1);

    predictorLabels = [ ...
        "active IED count within " + ...
            string(config.postIEDWindowMilliseconds) + " ms"; ...
        "orange vs yellow"; ...
        "red vs yellow" ...
    ];

    set(ax, ...
        'YTick', yPositions, ...
        'YTickLabel', predictorLabels, ...
        'YDir', 'reverse', ...
        'XScale', 'log', ...
        'FontSize', 10, ...
        'FontName', 'Arial', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'TickDir', 'out');

    xlabel(ax, 'hazard ratio with robust 95% CI', 'Color', 'k');
    title(ax, sprintf('%s: Cox model estimates', char(config.code)), ...
        'Color', 'k', 'FontWeight', 'bold');

    xLimits = calculatePositiveLogLimits( ...
        coxResults.hazardRatioCILow, ...
        coxResults.hazardRatioCIHigh);

    significantRows = ...
        isfinite(coxResults.pValue) & ...
        coxResults.pValue < 0.05 & ...
        isfinite(coxResults.hazardRatioCIHigh) & ...
        coxResults.hazardRatioCIHigh > 0;

    significanceX = NaN(nPredictors, 1);
    significanceX(significantRows) = ...
        1.10 .* coxResults.hazardRatioCIHigh(significantRows);

    if any(significantRows)
        xLimits(2) = max( ...
            xLimits(2), ...
            1.15 .* max(significanceX(significantRows)));
    end

    xlim(ax, xLimits);
    ylim(ax, [0.5, nPredictors + 0.5]);

    for ii = 1:nPredictors
        if significantRows(ii)
            text( ...
                ax, ...
                significanceX(ii), ...
                yPositions(ii), ...
                '*', ...
                'Color', 'k', ...
                'FontSize', 16, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', 'left', ...
                'VerticalAlignment', 'middle');
        end
    end

    grid(ax, 'off');
    box(ax, 'off');
    hold(ax, 'off');

end

function plotAdjustedEffectPanel( ...
    ax, ...
    coxResults, ...
    modelEffectTable, ...
    config)

    hold(ax, 'on');

    lightColor = 0.75 .* [1 1 1] + 0.25 .* config.color;

    exposureState = modelEffectTable.activeIEDWindowCount;
    relativeHazard = modelEffectTable.relativeHazard;
    relativeHazardCILow = modelEffectTable.relativeHazardCILow;
    relativeHazardCIHigh = modelEffectTable.relativeHazardCIHigh;

    fill( ...
        ax, ...
        [exposureState; flipud(exposureState)], ...
        [relativeHazardCILow; flipud(relativeHazardCIHigh)], ...
        lightColor, ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.55);

    yline(ax, 1, '--', ...
        'Color', [0.45 0.45 0.45], ...
        'LineWidth', 1);

    plot( ...
        ax, ...
        exposureState, ...
        relativeHazard, ...
        '-', ...
        'LineWidth', 2.2, ...
        'Color', config.color);

    xTickValues = chooseSparseObservedTicks(exposureState, 6);
    markerRows = ismember(exposureState, xTickValues);

    plot( ...
        ax, ...
        exposureState(markerRows), ...
        relativeHazard(markerRows), ...
        'o', ...
        'LineStyle', 'none', ...
        'MarkerSize', 6, ...
        'MarkerFaceColor', config.color, ...
        'MarkerEdgeColor', config.color);

    xMinimum = min(exposureState);
    xMaximum = max(exposureState);

    if xMaximum == xMinimum
        xlim(ax, [xMinimum - 0.5, xMaximum + 0.5]);
    else
        xPadding = max(0.25, 0.02 .* (xMaximum - xMinimum));
        xlim(ax, [xMinimum - xPadding, xMaximum + xPadding]);
    end

    xticks(ax, xTickValues);
    xticklabels(ax, compose('%g', xTickValues));

    set(ax, ...
        'YScale', 'log', ...
        'FontSize', 10, ...
        'FontName', 'Arial', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'TickDir', 'out');

    xlabel(ax, ...
        'number of simultaneously active IED windows', ...
        'Color', 'k');

    ylabel(ax, ...
        sprintf('relative %s hazard vs 0 active IEDs', ...
            char(config.hazardLabel)), ...
        'Color', 'k');

    title(ax, sprintf('%s: adjusted IED-count effect', char(config.code)), ...
        'Color', 'k', 'FontWeight', 'bold');

    yLimits = calculatePositiveLogLimits( ...
        relativeHazardCILow, ...
        relativeHazardCIHigh);

    ylim(ax, yLimits);

    primaryRow = coxResults(1, :);

    resultText = sprintf( ...
        'HR per additional IED = %.3f\n95%% CI [%.3f, %.3f]\np = %.3g', ...
        primaryRow.hazardRatio, ...
        primaryRow.hazardRatioCILow, ...
        primaryRow.hazardRatioCIHigh, ...
        primaryRow.pValue);

    text( ...
        ax, ...
        0.96, ...
        0.95, ...
        resultText, ...
        'Units', 'normalized', ...
        'VerticalAlignment', 'top', ...
        'HorizontalAlignment', 'right', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'Color', 'k', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', [0.80 0.80 0.80], ...
        'Margin', 5);

    grid(ax, 'off');
    box(ax, 'off');
    hold(ax, 'off');

end

function tickValues = chooseSparseObservedTicks( ...
    xValues, maximumNumberOfTicks)

    xValues = xValues(:);
    xValues = xValues(isfinite(xValues));
    xValues = unique(xValues, 'sorted');

    if isempty(xValues)
        tickValues = [0; 1];
        return;
    end

    if length(xValues) <= maximumNumberOfTicks
        tickValues = xValues;
        return;
    end

    targetValues = linspace( ...
        min(xValues), ...
        max(xValues), ...
        maximumNumberOfTicks);

    tickValues = NaN(maximumNumberOfTicks, 1);

    for tt = 1:maximumNumberOfTicks

        [~, closestRow] = min(abs(xValues - targetValues(tt)));
        tickValues(tt) = xValues(closestRow);

    end

    tickValues = unique( ...
        [xValues(1); tickValues; xValues(end)], ...
        'sorted');

end

function axisLimits = calculatePositiveLogLimits( ...
    lowerValues, ...
    upperValues)

    lowerValues = lowerValues(:);
    upperValues = upperValues(:);

    positiveLower = lowerValues( ...
        isfinite(lowerValues) & lowerValues > 0);

    positiveUpper = upperValues( ...
        isfinite(upperValues) & upperValues > 0);

    if isempty(positiveLower) || isempty(positiveUpper)
        axisLimits = [0.5 2];
        return;
    end

    minimumValue = min([positiveLower; positiveUpper; 1]);
    maximumValue = max([positiveLower; positiveUpper; 1]);

    logMinimum = log10(minimumValue);
    logMaximum = log10(maximumValue);

    if logMaximum == logMinimum

        logMinimum = logMinimum - 0.2;
        logMaximum = logMaximum + 0.2;

    else

        padding = 0.10 .* (logMaximum - logMinimum);
        logMinimum = logMinimum - padding;
        logMaximum = logMaximum + padding;

    end

    axisLimits = [10^logMinimum, 10^logMaximum];

end
