% Overall participant-stratified mechanistic Cox analyses with expected reward
%
% This script analyzes ALL IEDs across all channels. It is NOT specific to
% anatomical brain areas.

% Author: Nill

clear;
clc;
close all;

%% Paths

inputFolderName_LFPIED = ...
    'D:\Nill\data\BART\0_0_new_IED\IED1_find_number_of_IEDs\';

inputFolderName_modeling = ...
    'D:\Nill\data\BART\0_0_new_IED\context_modeling\param_recovery_1_modeling\';

outputFolderName = ...
    'D:\Nill\code\BART\IED\0_0_new_IED\IED8_cox_expected_reward_counts\';

if ~exist(outputFolderName, 'dir')
    mkdir(outputFolderName);
end

%% Shared settings

settings.postIEDWindowMillisecondsIT = 1000;
settings.postIEDWindowMillisecondsRT = 500;
settings.postIEDWindowMillisecondsBR = 1000;
settings.maximumRTSeconds = 20;
settings.defaultSamplingFrequencyHz = 1000;
settings.useOnlyNonControlTrials = true;

% Standard colors used in the other IED analyses.
colorIT = [0.847  0.333  0.153];
colorRT = [0.204  0.459  0.702];
colorBR = [0.250  0.600  0.250];

%% Analysis definitions

analysisConfigs(1) = struct( ...
    'code', "IT", ...
    'displayName', "Inflation time", ...
    'durationField', "ITs", ...
    'iedField', "IED_occurance_IT", ...
    'eventMode', "allEndpoints", ...
    'postIEDWindowMilliseconds', ...
        settings.postIEDWindowMillisecondsIT, ...
    'color', colorIT, ...
    'hazardLabel', "action");

analysisConfigs(2) = struct( ...
    'code', "RT", ...
    'displayName', "Response time", ...
    'durationField', "RTs", ...
    'iedField', "IED_occurance_RT", ...
    'eventMode', "allEndpoints", ...
    'postIEDWindowMilliseconds', ...
        settings.postIEDWindowMillisecondsRT, ...
    'color', colorRT, ...
    'hazardLabel', "response");

analysisConfigs(3) = struct( ...
    'code', "BR", ...
    'displayName', "Banking response", ...
    'durationField', "ITs", ...
    'iedField', "IED_occurance_IT", ...
    'eventMode', "bankedOnly", ...
    'postIEDWindowMilliseconds', ...
        settings.postIEDWindowMillisecondsBR, ...
    'color', colorBR, ...
    'hazardLabel', "banking");

%% Start one combined text log

textOutputFile = fullfile( ...
    outputFolderName, ...
    'IT_RT_BR_expected_reward_overall_console_output.txt');

diary off;
if exist(textOutputFile, 'file')
    delete(textOutputFile);
end
diary(textOutputFile);
diaryCleanup = onCleanup(@() diary('off'));

%% Run IT, RT, and BR

analysisResultCells = cell(1, length(analysisConfigs));

for aa = 1:length(analysisConfigs)

    fprintf('\n\n');
    fprintf('############################################################\n');
    fprintf('RUNNING OVERALL %s EXPECTED-REWARD ANALYSIS\n', ...
        char(analysisConfigs(aa).code));
    fprintf('############################################################\n');

    analysisResultCells{aa} = runOverallMechanisticCoxAnalysis( ...
        inputFolderName_LFPIED, ...
        inputFolderName_modeling, ...
        analysisConfigs(aa), ...
        settings);

end

% Every call returns exactly the same fields, so this creates a stable
% structure array without the dissimilar-structure assignment problem.
analysisResults = [analysisResultCells{:}];

%% Save numerical outputs

for aa = 1:length(analysisConfigs)

    code = char(analysisConfigs(aa).code);
    result = analysisResults(aa);

    writetable( ...
        result.countingProcessData, ...
        fullfile(outputFolderName, ...
            sprintf('%s_expected_reward_counting_process_data.csv', code)));

    writetable( ...
        result.trialSummary, ...
        fullfile(outputFolderName, ...
            sprintf('%s_expected_reward_trial_summary.csv', code)));

    writetable( ...
        result.coxResults, ...
        fullfile(outputFolderName, ...
            sprintf('%s_expected_reward_cox_results.csv', code)));

    writetable( ...
        result.modelEffectTable, ...
        fullfile(outputFolderName, ...
            sprintf('%s_expected_reward_adjusted_effect.csv', code)));

    writematrix( ...
        result.baselineCumulativeHazard, ...
        fullfile(outputFolderName, ...
            sprintf('%s_expected_reward_baseline_cumulative_hazard.csv', ...
            code)));

end

combinedModelOutputFile = fullfile( ...
    outputFolderName, ...
    'IT_RT_BR_expected_reward_overall_results.mat');

save( ...
    combinedModelOutputFile, ...
    'analysisResults', ...
    'analysisConfigs', ...
    'settings', ...
    'colorIT', ...
    'colorRT', ...
    'colorBR', ...
    '-v7.3');

%% Create ONE 3-by-2 PDF

combinedFigure = createCombinedExpectedRewardVisualization( ...
    analysisResults, analysisConfigs);

combinedPDFOutputFile = fullfile( ...
    outputFolderName, ...
    'IT_RT_BR_expected_reward_overall_cox_visualization_3x2.pdf');

exportgraphics( ...
    combinedFigure, ...
    combinedPDFOutputFile, ...
    'ContentType', 'vector');

close(combinedFigure);

fprintf('\n============================================================\n');
fprintf('OVERALL EXPECTED-REWARD ANALYSIS COMPLETE\n');
fprintf('============================================================\n');
fprintf('One 3x2 visualization PDF saved:\n%s\n', ...
    combinedPDFOutputFile);
fprintf('Combined MAT file saved:\n%s\n', ...
    combinedModelOutputFile);
fprintf('Console output saved:\n%s\n', ...
    textOutputFile);

diary off;
clear diaryCleanup;

%% Local functions

function result = runOverallMechanisticCoxAnalysis( ...
    inputFolderName_LFPIED, ...
    inputFolderName_modeling, ...
    config, ...
    settings)

    codeChar = char(config.code);
    postIEDWindowMilliseconds = config.postIEDWindowMilliseconds;
    postIEDWindowSeconds = postIEDWindowMilliseconds / 1000;

    fileList = dir(fullfile( ...
        inputFolderName_LFPIED, '*.LFPIED.mat'));

    modelFileList = dir(fullfile( ...
        inputFolderName_modeling, '*TDdataParamRecovery.mat'));

    if isempty(fileList)
        error('%s: no .LFPIED.mat files were found.', codeChar);
    end

    if isempty(modelFileList)
        error('%s: no *TDdataParamRecovery.mat files were found.', ...
            codeChar);
    end

    countingProcessData = emptyMechanisticCountingProcessTable();
    trialSummary = emptyMechanisticTrialSummaryTable();

    nSkippedMissingModelFile = 0;
    nSkippedInvalidModelFile = 0;
    nLoadedParticipants = 0;
    totalIEDsRetained = 0;

    %% Build overall counting-process data

    for pt = 1:length(fileList)

        fileName = fileList(pt).name;
        fileNameParts = strsplit(fileName, '.');
        patientID = string(fileNameParts{1});

        fprintf('\n%s: processing patient %s\n', ...
            codeChar, char(patientID));

        loadedData = load(fullfile( ...
            inputFolderName_LFPIED, fileName));

        if ~isfield(loadedData, 'LFPIED')
            fprintf('%s: skipped; LFPIED structure was not found.\n', ...
                codeChar);
            continue;
        end

        modelFilePath = findModelFileForPatient( ...
            inputFolderName_modeling, modelFileList, patientID);

        if strlength(modelFilePath) == 0
            fprintf(['%s: skipped; no unique expected-reward model file ' ...
                'was found for %s.\n'], codeChar, char(patientID));
            nSkippedMissingModelFile = nSkippedMissingModelFile + 1;
            continue;
        end

        modelData = load(char(modelFilePath));

        [expectedRewardsRaw, expectedRewardReadStatus] = ...
            readExpectedReward(modelData);

        if expectedRewardReadStatus ~= "ok"
            fprintf('%s: skipped; %s\n', ...
                codeChar, char(expectedRewardReadStatus));
            nSkippedInvalidModelFile = nSkippedInvalidModelFile + 1;
            continue;
        end

        LFPIED = loadedData.LFPIED;

        requiredFields = { ...
            'RTs', ...
            'isControl', ...
            'balloonType', ...
            char(config.durationField), ...
            char(config.iedField)};

        if config.eventMode == "bankedOnly"
            requiredFields{end + 1} = 'BankedTrials';
        end

        requiredFields = unique(requiredFields, 'stable');
        missingField = false;

        for ff = 1:length(requiredFields)
            if ~isfield(LFPIED, requiredFields{ff})
                fprintf('%s: skipped; missing field %s.\n', ...
                    codeChar, requiredFields{ff});
                missingField = true;
            end
        end

        if missingField
            continue;
        end

        RTs = double(LFPIED.RTs(:));
        durationValues = LFPIED.(char(config.durationField));
        durationValues = double(durationValues(:));
        isControl = double(LFPIED.isControl(:));
        balloonType = double(LFPIED.balloonType(:));

        if config.eventMode == "bankedOnly"
            bankedTrials = double(LFPIED.BankedTrials(:));
        else
            bankedTrials = NaN(size(durationValues));
        end

        vectorLengths = [ ...
            length(RTs), ...
            length(durationValues), ...
            length(isControl), ...
            length(balloonType), ...
            length(expectedRewardsRaw)];

        if config.eventMode == "bankedOnly"
            vectorLengths(end + 1) = length(bankedTrials);
        end

        if isfield(LFPIED, 'nTrials') && ...
                isscalar(LFPIED.nTrials) && ...
                isfinite(LFPIED.nTrials)
            vectorLengths(end + 1) = double(LFPIED.nTrials);
        end

        nTrials = floor(min(vectorLengths));

        if nTrials < 1
            fprintf('%s: skipped; no aligned trials.\n', codeChar);
            continue;
        end

        RTs = RTs(1:nTrials);
        durationValues = durationValues(1:nTrials);
        isControl = isControl(1:nTrials);
        balloonType = balloonType(1:nTrials);
        bankedTrials = bankedTrials(1:nTrials);
        expectedRewards = double(expectedRewardsRaw(1:nTrials));

        balloonColorCode = mapBalloonColorCode(balloonType);
        samplingFrequencyHz = getSamplingFrequency( ...
            LFPIED, settings.defaultSamplingFrequencyHz);

        IEDoccurrence = LFPIED.(char(config.iedField));
        participantHadValidTrial = false;

        for trial = 1:nTrials

            durationSeconds = durationValues(trial);

            if config.eventMode == "bankedOnly"
                finalEventObserved = bankedTrials(trial) == 1;
            else
                finalEventObserved = true;
            end

            keepTrial = ...
                isfinite(RTs(trial)) && ...
                RTs(trial) > 0 && ...
                RTs(trial) <= settings.maximumRTSeconds && ...
                isfinite(durationSeconds) && ...
                durationSeconds > 0 && ...
                isfinite(balloonColorCode(trial)) && ...
                ismember(balloonColorCode(trial), [1 2 3]) && ...
                isfinite(expectedRewards(trial));

            if settings.useOnlyNonControlTrials
                keepTrial = keepTrial && isControl(trial) == 0;
            end

            if config.eventMode == "bankedOnly"
                keepTrial = keepTrial && ...
                    isfinite(bankedTrials(trial)) && ...
                    ismember(bankedTrials(trial), [0 1]);
            end

            if ~keepTrial
                continue;
            end

            participantHadValidTrial = true;

            trialRows = makeMechanisticPostIEDRows( ...
                patientID, ...
                trial, ...
                durationSeconds, ...
                IEDoccurrence, ...
                samplingFrequencyHz, ...
                balloonColorCode(trial), ...
                expectedRewards(trial), ...
                finalEventObserved, ...
                postIEDWindowSeconds);

            countingProcessData = [ ...
                countingProcessData; trialRows]; 

            nIEDsInTrial = countIEDsInTrial( ...
                IEDoccurrence, trial, durationSeconds, ...
                samplingFrequencyHz);

            totalIEDsRetained = totalIEDsRetained + nIEDsInTrial;

            postIEDExposureSeconds = sum( ...
                (trialRows.tStop - trialRows.tStart) .* ...
                trialRows.postIED, ...
                'omitnan');

            eventInPostIEDWindow = double( ...
                finalEventObserved && ...
                trialRows.postIED(end) == 1);

            if config.eventMode == "bankedOnly"
                bankedTrialValue = bankedTrials(trial);
            else
                bankedTrialValue = NaN;
            end

            newTrialSummaryRow = table( ...
                patientID, ...
                trial, ...
                durationSeconds, ...
                expectedRewards(trial), ...
                bankedTrialValue, ...
                double(finalEventObserved), ...
                eventInPostIEDWindow, ...
                nIEDsInTrial, ...
                postIEDExposureSeconds, ...
                balloonColorCode(trial), ...
                samplingFrequencyHz, ...
                'VariableNames', ...
                    trialSummary.Properties.VariableNames);

            trialSummary = [ ...
                trialSummary; newTrialSummaryRow]; 

        end

        if participantHadValidTrial
            nLoadedParticipants = nLoadedParticipants + 1;
            fprintf('%s: expected-reward file: %s\n', ...
                codeChar, char(modelFilePath));
        end

    end

    if isempty(countingProcessData)
        error('%s: no valid counting-process rows were created.', ...
            codeChar);
    end

    %% Build predictors

    [countingProcessData.patientStratum, patientLevels] = ...
        findgroups(countingProcessData.patientID);

    [X, predictorNames, referenceBalloonColor] = ...
        buildMechanisticPredictorMatrix(countingProcessData);

    T = [countingProcessData.tStart, countingProcessData.tStop];
    censoring = logical(countingProcessData.censored);
    strata = countingProcessData.patientStratum;

    validRows = ...
        all(isfinite(X), 2) & ...
        all(isfinite(T), 2) & ...
        T(:, 1) >= 0 & ...
        T(:, 2) > T(:, 1) & ...
        isfinite(strata);

    X = X(validRows, :);
    T = T(validRows, :);
    censoring = censoring(validRows);
    strata = strata(validRows);
    countingProcessData = countingProcessData(validRows, :);

    if size(X, 1) <= size(X, 2)
        error('%s: insufficient rows for the predictor matrix.', ...
            codeChar);
    end

    if length(unique(countingProcessData.patientID)) < 2
        error('%s: fewer than two participants remained.', codeChar);
    end

    if range(countingProcessData.activeIEDWindowCount) == 0
        error('%s: active IED count has no variation.', codeChar);
    end

    if range(countingProcessData.expectedReward) == 0
        error('%s: expected reward has no variation.', codeChar);
    end

    nEndpointEvents = sum(countingProcessData.eventAtStop == 1);

    nEventsOutsideWindow = sum( ...
        countingProcessData.eventAtStop == 1 & ...
        countingProcessData.postIED == 0);

    nEventsInsideWindow = sum( ...
        countingProcessData.eventAtStop == 1 & ...
        countingProcessData.postIED == 1);

    timeOutsideWindowSeconds = sum( ...
        (countingProcessData.tStop - countingProcessData.tStart) .* ...
        (countingProcessData.postIED == 0), ...
        'omitnan');

    timeInsideWindowSeconds = sum( ...
        (countingProcessData.tStop - countingProcessData.tStart) .* ...
        (countingProcessData.postIED == 1), ...
        'omitnan');

    if timeInsideWindowSeconds <= 0
        error('%s: no post-IED exposure time was available.', ...
            codeChar);
    end

    if nEventsInsideWindow < 1 || nEventsOutsideWindow < 1
        error(['%s: at least one endpoint event is required both inside ' ...
            'and outside post-IED windows.'], codeChar);
    end

    %% Fit participant-stratified Cox model

    coxOptions = statset('coxphfit');
    coxOptions.Display = 'final';
    coxOptions.MaxIter = 1000;
    coxOptions.MaxFunEvals = 5000;

    [beta, logLikelihood, baselineCumulativeHazard, stats] = ...
        coxphfit( ...
            X, ...
            T, ...
            'Censoring', censoring, ...
            'Strata', strata, ...
            'Ties', 'efron', ...
            'Baseline', 0, ...
            'Options', coxOptions);

    %% Participant-clustered robust inference

    [clusterRobustCovariance, clusterRobustSE, ...
        clusterRobustZ, clusterRobustP] = ...
        computeClusterRobustInference( ...
            stats, beta, countingProcessData.patientStratum);

    %% Results table

    betaCILow = beta - 1.96 .* clusterRobustSE;
    betaCIHigh = beta + 1.96 .* clusterRobustSE;

    hazardRatio = exp(beta);
    hazardRatioCILow = exp(betaCILow);
    hazardRatioCIHigh = exp(betaCIHigh);

    interpretation = createPredictorInterpretations( ...
        predictorNames, config);

    coxResults = table( ...
        predictorNames(:), ...
        beta(:), ...
        stats.se(:), ...
        stats.z(:), ...
        stats.p(:), ...
        clusterRobustSE(:), ...
        clusterRobustZ(:), ...
        clusterRobustP(:), ...
        betaCILow(:), ...
        betaCIHigh(:), ...
        hazardRatio(:), ...
        hazardRatioCILow(:), ...
        hazardRatioCIHigh(:), ...
        interpretation(:), ...
        'VariableNames', { ...
            'predictor', ...
            'beta_logHazard', ...
            'modelBasedSE', ...
            'modelBasedZ', ...
            'modelBasedPValue', ...
            'clusterRobustSE', ...
            'clusterRobustZ', ...
            'pValue', ...
            'betaCILow', ...
            'betaCIHigh', ...
            'hazardRatio', ...
            'hazardRatioCILow', ...
            'hazardRatioCIHigh', ...
            'interpretation'});

    %% Create adjusted expected-reward curves

    modelEffectTable = createExpectedRewardEffectTable( ...
        beta, ...
        clusterRobustCovariance, ...
        predictorNames, ...
        trialSummary.expectedReward);

    %% Print summary

    interactionIndex = find( ...
        predictorNames == "active_ied_count_x_expected_reward", 1);

    expectedRewardIndex = find( ...
        predictorNames == "expected_reward", 1);

    IEDIndex = find( ...
        predictorNames == "active_ied_count", 1);

    fprintf('\n============================================================\n');
    fprintf('%s OVERALL MECHANISTIC COX MODEL\n', codeChar);
    fprintf('============================================================\n');
    fprintf('post-IED window: %d ms\n', postIEDWindowMilliseconds);
    fprintf('participants: %d\n', length(patientLevels));
    fprintf('trials: %d\n', height(trialSummary));
    fprintf('counting-process rows: %d\n', ...
        height(countingProcessData));
    fprintf('all retained IED rows: %d\n', totalIEDsRetained);
    fprintf('endpoint events: %d\n', nEndpointEvents);
    fprintf('events outside post-IED window: %d\n', ...
        nEventsOutsideWindow);
    fprintf('events inside post-IED window: %d\n', ...
        nEventsInsideWindow);
    fprintf('at-risk time outside window: %.3f s\n', ...
        timeOutsideWindowSeconds);
    fprintf('at-risk time inside window: %.3f s\n', ...
        timeInsideWindowSeconds);
    fprintf('reference balloon color: %s\n', ...
        char(referenceBalloonColor));
    fprintf('log likelihood: %.6f\n', logLikelihood);
    fprintf('participants loaded: %d\n', nLoadedParticipants);
    fprintf('skipped for missing model file: %d\n', ...
        nSkippedMissingModelFile);
    fprintf('skipped for invalid model file: %d\n\n', ...
        nSkippedInvalidModelFile);

    disp(coxResults);

    fprintf('\n%s primary interaction result:\n', codeChar);
    fprintf('beta_IEDxExpectedReward = %.6f\n', ...
        beta(interactionIndex));
    fprintf('95%% beta CI = [%.6f, %.6f]\n', ...
        betaCILow(interactionIndex), ...
        betaCIHigh(interactionIndex));
    fprintf('interaction hazard ratio = %.6f\n', ...
        hazardRatio(interactionIndex));
    fprintf('95%% HR CI = [%.6f, %.6f]\n', ...
        hazardRatioCILow(interactionIndex), ...
        hazardRatioCIHigh(interactionIndex));
    fprintf('p = %.6g\n', clusterRobustP(interactionIndex));

    slopeOutsideIED = beta(expectedRewardIndex);
    slopeInsideIED = beta(expectedRewardIndex) + ...
        beta(interactionIndex);

    fprintf('expected-reward slope at 0 active IEDs = %.6f\n', ...
        slopeOutsideIED);
    fprintf('expected-reward slope at 1 active IED = %.6f\n', ...
        slopeInsideIED);
    fprintf('coefficient per additional active IED at expected reward = 0: %.6f\n', ...
        beta(IEDIndex));

    if clusterRobustP(interactionIndex) < 0.05
        if beta(interactionIndex) > 0
            fprintf(['conclusion: expected reward has a significantly ' ...
                'more positive per additional active IED.\n']);
        else
            fprintf(['conclusion: expected reward has a significantly ' ...
                'more negative per additional active IED.\n']);
        end
    else
        fprintf(['conclusion: no significant evidence that the ' ...
            'expected-reward slope changes with active IED count.\n']);
    end

    %% Return outputs with identical fields for IT, RT, and BR

    result = struct();
    result.code = config.code;
    result.displayName = config.displayName;
    result.postIEDWindowMilliseconds = postIEDWindowMilliseconds;
    result.countingProcessData = countingProcessData;
    result.trialSummary = trialSummary;
    result.coxResults = coxResults;
    result.beta = beta;
    result.logLikelihood = logLikelihood;
    result.baselineCumulativeHazard = baselineCumulativeHazard;
    result.stats = stats;
    result.clusterRobustCovariance = clusterRobustCovariance;
    result.clusterRobustSE = clusterRobustSE;
    result.clusterRobustZ = clusterRobustZ;
    result.clusterRobustP = clusterRobustP;
    result.predictorNames = predictorNames;
    result.patientLevels = patientLevels;
    result.referenceBalloonColor = referenceBalloonColor;
    result.nEndpointEvents = nEndpointEvents;
    result.nEventsOutsideWindow = nEventsOutsideWindow;
    result.nEventsInsideWindow = nEventsInsideWindow;
    result.timeOutsideWindowSeconds = timeOutsideWindowSeconds;
    result.timeInsideWindowSeconds = timeInsideWindowSeconds;
    result.totalIEDsRetained = totalIEDsRetained;
    result.modelEffectTable = modelEffectTable;
    result.expectedRewardSlopeOutsideIED = slopeOutsideIED;
    result.expectedRewardSlopeInsideIED = slopeInsideIED;

end

function modelFilePath = findModelFileForPatient( ...
    inputFolderName_modeling, modelFileList, patientID)

    modelFilePath = "";
    patientIDChar = char(patientID);
    escapedPatientID = regexptranslate('escape', patientIDChar);

    % The right-side boundary prevents patient 201902 from matching 201902r.
    patientPattern = [ ...
        '(^|[^A-Za-z0-9])', ...
        escapedPatientID, ...
        '([^A-Za-z0-9]|TDdataParamRecovery)'];

    matchedRows = false(length(modelFileList), 1);

    for ii = 1:length(modelFileList)
        matchedRows(ii) = ~isempty(regexpi( ...
            modelFileList(ii).name, patientPattern, 'once'));
    end

    matchedIndices = find(matchedRows);

    if isempty(matchedIndices)
        return;
    end

    if length(matchedIndices) > 1
        startsWithPatientID = false(length(matchedIndices), 1);
        for jj = 1:length(matchedIndices)
            startsWithPatientID(jj) = startsWith( ...
                string(modelFileList(matchedIndices(jj)).name), ...
                patientID, ...
                'IgnoreCase', true);
        end

        if sum(startsWithPatientID) == 1
            matchedIndices = matchedIndices(startsWithPatientID);
        else
            matchingNames = string({modelFileList(matchedIndices).name});
            [~, shortestRow] = min(strlength(matchingNames));
            matchedIndices = matchedIndices(shortestRow);
            fprintf(['Warning: multiple model files matched %s; ' ...
                'using %s.\n'], patientIDChar, ...
                modelFileList(matchedIndices).name);
        end
    end

    modelFilePath = string(fullfile( ...
        inputFolderName_modeling, ...
        modelFileList(matchedIndices).name));

end

function [expectedRewards, status] = readExpectedReward(modelData)

    expectedRewards = zeros(0, 1);
    status = "ok";

    if ~isfield(modelData, 'TDdataParamRecovery')
        status = "TDdataParamRecovery structure was not found";
        return;
    end

    TD = modelData.TDdataParamRecovery;

    requiredFields = {'bestApIdx', 'bestAnIdx', 'expectedReward'};

    for ff = 1:length(requiredFields)
        if ~isfield(TD, requiredFields{ff})
            status = "missing field " + string(requiredFields{ff});
            return;
        end
    end

    bestApIdx = double(TD.bestApIdx);
    bestAnIdx = double(TD.bestAnIdx);

    if ~isscalar(bestApIdx) || ~isscalar(bestAnIdx) || ...
            ~isfinite(bestApIdx) || ~isfinite(bestAnIdx)
        status = "bestApIdx or bestAnIdx is invalid";
        return;
    end

    bestApIdx = round(bestApIdx);
    bestAnIdx = round(bestAnIdx);

    expectedRewardArray = TD.expectedReward;

    if ndims(expectedRewardArray) < 3 || ...
            bestApIdx < 1 || ...
            bestAnIdx < 1 || ...
            bestApIdx > size(expectedRewardArray, 1) || ...
            bestAnIdx > size(expectedRewardArray, 2)
        status = "expectedReward array or best parameter indices are invalid";
        return;
    end

    expectedRewards = squeeze( ...
        expectedRewardArray(bestApIdx, bestAnIdx, :));
    expectedRewards = double(expectedRewards(:));

    if isempty(expectedRewards)
        status = "expectedReward vector is empty";
    end

end

function countingProcessData = emptyMechanisticCountingProcessTable()

    countingProcessData = table( ...
        strings(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        false(0, 1), ...
        false(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'tStart', ...
            'tStop', ...
            'censored', ...
            'eventAtStop', ...
            'postIED', ...
            'activeIEDWindowCount', ...
            'timeSinceMostRecentIED_seconds', ...
            'balloonColorCode', ...
            'expectedReward', ...
            'samplingFrequencyHz'});

end

function trialSummary = emptyMechanisticTrialSummaryTable()

    trialSummary = table( ...
        strings(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'durationSeconds', ...
            'expectedReward', ...
            'bankedTrial', ...
            'eventObserved', ...
            'eventInPostIEDWindow', ...
            'nIEDsInFullDuration', ...
            'postIEDExposureSeconds', ...
            'balloonColorCode', ...
            'samplingFrequencyHz'});

end

function trialRows = makeMechanisticPostIEDRows( ...
    patientID, ...
    trialNumber, ...
    durationSeconds, ...
    IEDoccurrence, ...
    samplingFrequencyHz, ...
    balloonColorCode, ...
    expectedReward, ...
    finalEventObserved, ...
    postIEDWindowSeconds)

    % IEDoccurrence columns:
    %   1 = trial number
    %   2 = channel index
    %   3 = sample index from the beginning of the RT or IT interval

    if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 3
        IEDtimes = [];
    else
        validIEDRows = ...
            isfinite(IEDoccurrence(:, 1)) & ...
            isfinite(IEDoccurrence(:, 3)) & ...
            round(IEDoccurrence(:, 1)) == trialNumber & ...
            IEDoccurrence(:, 3) >= 1;

        sampleIndices = double(IEDoccurrence(validIEDRows, 3));
        IEDtimes = sampleIndices ./ samplingFrequencyHz;

        IEDtimes = IEDtimes( ...
            isfinite(IEDtimes) & ...
            IEDtimes > 0 & ...
            IEDtimes < durationSeconds);

        % Keep every IED occurrence. Do not use unique() here.
        IEDtimes = sort(IEDtimes);
    end

    if isempty(IEDtimes)
        breakTimes = [0; durationSeconds];
    else
        windowEndTimes = min( ...
            IEDtimes + postIEDWindowSeconds, durationSeconds);

        % unique() is used only for interval boundaries. It does NOT remove
        % IEDs from activeIEDWindowCount because IEDtimes remains unchanged.
        breakTimes = unique([ ...
            0; ...
            IEDtimes(:); ...
            windowEndTimes(:); ...
            durationSeconds], ...
            'sorted');
    end

    breakTimes = breakTimes( ...
        isfinite(breakTimes) & ...
        breakTimes >= 0 & ...
        breakTimes <= durationSeconds);

    breakTimes = unique(breakTimes, 'sorted');

    if length(breakTimes) < 2
        breakTimes = [0; durationSeconds];
    end

    tStart = breakTimes(1:end-1);
    tStop = breakTimes(2:end);

    validIntervals = tStop > tStart;
    tStart = tStart(validIntervals);
    tStop = tStop(validIntervals);

    intervalMidpoint = (tStart + tStop) ./ 2;

    postIED = zeros(length(tStart), 1);
    activeIEDWindowCount = zeros(length(tStart), 1);
    timeSinceMostRecentIED = NaN(length(tStart), 1);

    for kk = 1:length(tStart)

        if isempty(IEDtimes)
            continue;
        end

        activeWindows = ...
            intervalMidpoint(kk) >= IEDtimes & ...
            intervalMidpoint(kk) <= ...
                (IEDtimes + postIEDWindowSeconds);

        activeIEDWindowCount(kk) = sum(activeWindows);
        postIED(kk) = double(any(activeWindows));

        priorIEDtimes = IEDtimes(IEDtimes < intervalMidpoint(kk));

        if ~isempty(priorIEDtimes)
            timeSinceMostRecentIED(kk) = ...
                intervalMidpoint(kk) - max(priorIEDtimes);
        end

    end

    censored = true(length(tStart), 1);
    eventAtStop = false(length(tStart), 1);

    if finalEventObserved
        censored(end) = false;
        eventAtStop(end) = true;
    end

    trialRows = table( ...
        repmat(patientID, length(tStart), 1), ...
        repmat(trialNumber, length(tStart), 1), ...
        tStart, ...
        tStop, ...
        censored, ...
        eventAtStop, ...
        postIED, ...
        activeIEDWindowCount, ...
        timeSinceMostRecentIED, ...
        repmat(balloonColorCode, length(tStart), 1), ...
        repmat(expectedReward, length(tStart), 1), ...
        repmat(samplingFrequencyHz, length(tStart), 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'tStart', ...
            'tStop', ...
            'censored', ...
            'eventAtStop', ...
            'postIED', ...
            'activeIEDWindowCount', ...
            'timeSinceMostRecentIED_seconds', ...
            'balloonColorCode', ...
            'expectedReward', ...
            'samplingFrequencyHz'});

end

function nIEDs = countIEDsInTrial( ...
    IEDoccurrence, trialNumber, durationSeconds, samplingFrequencyHz)

    nIEDs = 0;

    if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 3
        return;
    end

    IEDtimeSeconds = double(IEDoccurrence(:, 3)) ./ ...
        samplingFrequencyHz;

    validRows = ...
        isfinite(IEDoccurrence(:, 1)) & ...
        isfinite(IEDoccurrence(:, 3)) & ...
        round(IEDoccurrence(:, 1)) == trialNumber & ...
        IEDoccurrence(:, 3) >= 1 & ...
        IEDtimeSeconds > 0 & ...
        IEDtimeSeconds < durationSeconds;

    nIEDs = sum(validRows);

end

function [X, predictorNames, referenceColorName] = ...
    buildMechanisticPredictorMatrix(countingProcessData)

    activeIEDCount = double(countingProcessData.activeIEDWindowCount);
    expectedReward = double(countingProcessData.expectedReward);

    X = [activeIEDCount, expectedReward];
    predictorNames = [ ...
        "active_ied_count"; ...
        "expected_reward"];

    observedColors = unique( ...
        countingProcessData.balloonColorCode, 'sorted');
    observedColors = observedColors( ...
        ismember(observedColors, [1 2 3]));

    if isempty(observedColors)
        error('No valid balloon colors were found.');
    end

    if ismember(1, observedColors)
        referenceColor = 1;
    else
        referenceColor = observedColors(1);
    end

    colorNames = ["yellow", "orange", "red"];
    referenceColorName = colorNames(referenceColor);

    comparisonColors = observedColors( ...
        observedColors ~= referenceColor);

    for cc = 1:length(comparisonColors)
        colorCode = comparisonColors(cc);
        X(:, end + 1) = double( ...
            countingProcessData.balloonColorCode == colorCode); 
        predictorNames(end + 1, 1) = ...
            colorNames(colorCode) + "_vs_" + ...
            colorNames(referenceColor); 
    end

    X(:, end + 1) = activeIEDCount .* expectedReward;
    predictorNames(end + 1, 1) = ...
        "active_ied_count_x_expected_reward";

end

function interpretation = createPredictorInterpretations( ...
    predictorNames, config)

    interpretation = strings(length(predictorNames), 1);

    for ii = 1:length(predictorNames)
        switch predictorNames(ii)
            case "active_ied_count"
                interpretation(ii) = ...
                    "Hazard change per additional active IED when expected reward equals zero.";
            case "expected_reward"
                interpretation(ii) = ...
                    "Expected-reward log-hazard slope at zero active IEDs.";
            case "active_ied_count_x_expected_reward"
                interpretation(ii) = ...
                    "Change in the expected-reward log-hazard slope per additional active IED.";
            otherwise
                interpretation(ii) = ...
                    "Balloon-color effect relative to the reference color.";
        end
    end

    if config.code == "IT"
        interpretation(predictorNames == "expected_reward") = ...
            "Expected-reward effect on action hazard at zero active IEDs.";
    elseif config.code == "RT"
        interpretation(predictorNames == "expected_reward") = ...
            "Expected-reward effect on response hazard at zero active IEDs.";
    else
        interpretation(predictorNames == "expected_reward") = ...
            "Expected-reward effect on banking hazard at zero active IEDs.";
    end

end

function effectTable = createExpectedRewardEffectTable( ...
    beta, robustCovariance, predictorNames, observedExpectedReward)

    beta = beta(:);
    observedExpectedReward = double(observedExpectedReward(:));
    observedExpectedReward = observedExpectedReward( ...
        isfinite(observedExpectedReward));

    if isempty(observedExpectedReward)
        error('No finite expected-reward values were available.');
    end

    minimumExpectedReward = min(observedExpectedReward);
    maximumExpectedReward = max(observedExpectedReward);
    referenceExpectedReward = mean(observedExpectedReward, 'omitnan');

    if maximumExpectedReward == minimumExpectedReward
        expectedRewardGrid = minimumExpectedReward;
    else
        expectedRewardGrid = linspace( ...
            minimumExpectedReward, maximumExpectedReward, 120)';
    end

    IEDIndex = find( ...
        predictorNames == "active_ied_count", 1);
    expectedRewardIndex = find( ...
        predictorNames == "expected_reward", 1);
    interactionIndex = find( ...
        predictorNames == "active_ied_count_x_expected_reward", 1);

    if isempty(IEDIndex) || isempty(expectedRewardIndex) || ...
            isempty(interactionIndex)
        error('Required expected-reward predictors were not found.');
    end

    nGrid = length(expectedRewardGrid);
    logRelativeHazardNoIED = zeros(nGrid, 1);
    logRelativeHazardPostIED = zeros(nGrid, 1);
    seNoIED = zeros(nGrid, 1);
    sePostIED = zeros(nGrid, 1);

    for gg = 1:nGrid

        currentExpectedReward = expectedRewardGrid(gg);

        % Reference is: zero active IEDs at mean expected reward.
        noIEDContrast = zeros(length(beta), 1);
        noIEDContrast(expectedRewardIndex) = ...
            currentExpectedReward - referenceExpectedReward;

        postIEDContrast = zeros(length(beta), 1);
        postIEDContrast(IEDIndex) = 1;
        postIEDContrast(expectedRewardIndex) = ...
            currentExpectedReward - referenceExpectedReward;
        postIEDContrast(interactionIndex) = currentExpectedReward;

        logRelativeHazardNoIED(gg) = noIEDContrast' * beta;
        logRelativeHazardPostIED(gg) = postIEDContrast' * beta;

        varianceNoIED = noIEDContrast' * ...
            robustCovariance * noIEDContrast;
        variancePostIED = postIEDContrast' * ...
            robustCovariance * postIEDContrast;

        seNoIED(gg) = sqrt(max(varianceNoIED, 0));
        sePostIED(gg) = sqrt(max(variancePostIED, 0));

    end

    relativeHazardNoIED = exp(logRelativeHazardNoIED);
    relativeHazardNoIEDCILow = exp( ...
        logRelativeHazardNoIED - 1.96 .* seNoIED);
    relativeHazardNoIEDCIHigh = exp( ...
        logRelativeHazardNoIED + 1.96 .* seNoIED);

    relativeHazardPostIED = exp(logRelativeHazardPostIED);
    relativeHazardPostIEDCILow = exp( ...
        logRelativeHazardPostIED - 1.96 .* sePostIED);
    relativeHazardPostIEDCIHigh = exp( ...
        logRelativeHazardPostIED + 1.96 .* sePostIED);

    effectTable = table( ...
        expectedRewardGrid, ...
        relativeHazardNoIED, ...
        relativeHazardNoIEDCILow, ...
        relativeHazardNoIEDCIHigh, ...
        relativeHazardPostIED, ...
        relativeHazardPostIEDCILow, ...
        relativeHazardPostIEDCIHigh, ...
        repmat(referenceExpectedReward, nGrid, 1), ...
        'VariableNames', { ...
            'expectedReward', ...
            'relativeHazardNoIED', ...
            'relativeHazardNoIEDCILow', ...
            'relativeHazardNoIEDCIHigh', ...
            'relativeHazardPostIED', ...
            'relativeHazardPostIEDCILow', ...
            'relativeHazardPostIEDCIHigh', ...
            'referenceExpectedReward'});

end

function samplingFrequencyHz = getSamplingFrequency( ...
    LFPIED, defaultSamplingFrequencyHz)

    if isfield(LFPIED, 'Fs') && ...
            isscalar(LFPIED.Fs) && ...
            isfinite(LFPIED.Fs) && ...
            LFPIED.Fs > 0
        samplingFrequencyHz = double(LFPIED.Fs);
    else
        samplingFrequencyHz = defaultSamplingFrequencyHz;
    end

end

function balloonColorCode = mapBalloonColorCode(balloonType)

    balloonType = double(balloonType(:));
    balloonColorCode = NaN(size(balloonType));

    validRows = ...
        isfinite(balloonType) & ...
        ismember(round(balloonType), [1 2 3 11 12 13]);

    balloonColorCode(validRows) = ...
        mod(round(balloonType(validRows)) - 1, 10) + 1;

end

function [robustCovariance, robustSE, robustZ, robustP] = ...
    computeClusterRobustInference(stats, beta, clusterID)

    beta = beta(:);
    nPredictors = length(beta);
    clusterID = clusterID(:);

    uniqueClusters = unique(clusterID(isfinite(clusterID)));
    nClusters = length(uniqueClusters);

    canUseClusterScores = ...
        isfield(stats, 'scores') && ...
        size(stats.scores, 1) == length(clusterID) && ...
        size(stats.scores, 2) == nPredictors;

    if nClusters < 2 || ~canUseClusterScores
        robustCovariance = stats.covb;
        robustSE = stats.se(:);
        robustZ = stats.z(:);
        robustP = stats.p(:);
        return;
    end

    clusterScoreSums = zeros(nClusters, nPredictors);

    for gg = 1:nClusters
        rows = clusterID == uniqueClusters(gg);
        thisClusterScores = stats.scores(rows, :);
        thisClusterScores(~isfinite(thisClusterScores)) = 0;
        clusterScoreSums(gg, :) = sum(thisClusterScores, 1);
    end

    meat = clusterScoreSums' * clusterScoreSums;
    bread = stats.covb;

    robustCovariance = bread * meat * bread;
    robustCovariance = ...
        (nClusters / (nClusters - 1)) .* robustCovariance;

    robustSE = sqrt(max(diag(robustCovariance), 0));

    zeroSERows = robustSE <= 0 | ~isfinite(robustSE);
    robustSE(zeroSERows) = stats.se(zeroSERows);

    robustZ = beta ./ robustSE;
    robustP = 2 .* normcdf(-abs(robustZ), 0, 1);

end

function fig = createCombinedExpectedRewardVisualization( ...
    analysisResults, analysisConfigs)

    fig = figure('Visible', 'off', 'Color', 'w');
    set(fig, 'Position', [70 30 1500 1600]);

    layout = tiledlayout(fig, 3, 2, ...
        'Padding', 'compact', ...
        'TileSpacing', 'compact');

    sgtitle(layout, ...
        ['Overall participant-stratified Cox models: ' ...
        'IED x expected reward'], ...
        'FontName', 'Arial', ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Color', 'k');

    for aa = 1:length(analysisConfigs)

        forestAxis = nexttile(layout, (aa - 1) * 2 + 1);
        plotMechanisticForestPanel( ...
            forestAxis, ...
            analysisResults(aa).coxResults, ...
            analysisConfigs(aa));

        effectAxis = nexttile(layout, (aa - 1) * 2 + 2);
        plotExpectedRewardEffectPanel( ...
            effectAxis, ...
            analysisResults(aa), ...
            analysisConfigs(aa));

    end

end

function plotMechanisticForestPanel(ax, coxResults, config)

    hold(ax, 'on');

    nPredictors = height(coxResults);
    yPositions = (1:nPredictors)';

    beta = coxResults.beta_logHazard;
    lowerError = beta - coxResults.betaCILow;
    upperError = coxResults.betaCIHigh - beta;

    errorbar( ...
        ax, ...
        beta, ...
        yPositions, ...
        lowerError, ...
        upperError, ...
        'horizontal', ...
        'o', ...
        'LineWidth', 1.3, ...
        'MarkerSize', 6, ...
        'MarkerFaceColor', config.color, ...
        'MarkerEdgeColor', 'none', ...
        'Color', config.color, ...
        'CapSize', 7);

    xline(ax, 0, '--', ...
        'Color', [0.35 0.35 0.35], ...
        'LineWidth', 1);

    predictorLabels = humanReadablePredictorLabels( ...
        coxResults.predictor);

    set(ax, ...
        'YTick', yPositions, ...
        'YTickLabel', predictorLabels, ...
        'YDir', 'reverse', ...
        'FontSize', 10, ...
        'FontName', 'Arial', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'TickDir', 'out', ...
        'TickLabelInterpreter', 'none');

    xlabel(ax, ...
        'log-hazard coefficient with robust 95% CI', ...
        'Color', 'k');

    title(ax, sprintf('%s: mechanistic Cox estimates', ...
        char(config.code)), ...
        'Color', 'k', ...
        'FontWeight', 'bold');

    finiteLimits = [ ...
        coxResults.betaCILow(isfinite(coxResults.betaCILow)); ...
        coxResults.betaCIHigh(isfinite(coxResults.betaCIHigh)); ...
        0];

    if isempty(finiteLimits)
        xLimits = [-1 1];
    else
        xMinimum = min(finiteLimits);
        xMaximum = max(finiteLimits);
        xRange = xMaximum - xMinimum;
        if xRange <= 0
            xRange = 1;
        end
        xLimits = [ ...
            xMinimum - 0.12 * xRange, ...
            xMaximum + 0.20 * xRange];
    end

    significantRows = ...
        isfinite(coxResults.pValue) & ...
        coxResults.pValue < 0.05;

    for ii = 1:nPredictors
        if significantRows(ii)
            if coxResults.betaCIHigh(ii) >= 0
                significanceX = coxResults.betaCIHigh(ii) + ...
                    0.035 * diff(xLimits);
                alignment = 'left';
            else
                significanceX = coxResults.betaCILow(ii) - ...
                    0.035 * diff(xLimits);
                alignment = 'right';
            end

            text( ...
                ax, ...
                significanceX, ...
                yPositions(ii), ...
                '*', ...
                'Color', 'k', ...
                'FontSize', 15, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', alignment, ...
                'VerticalAlignment', 'middle');
        end
    end

    xlim(ax, xLimits);
    ylim(ax, [0.5, nPredictors + 0.5]);
    grid(ax, 'off');
    box(ax, 'off');
    hold(ax, 'off');

end

function labels = humanReadablePredictorLabels(predictorNames)

    labels = strings(length(predictorNames), 1);

    for ii = 1:length(predictorNames)
        switch predictorNames(ii)
            case "active_ied_count"
                labels(ii) = "active IED count";
            case "expected_reward"
                labels(ii) = "expected reward";
            case "active_ied_count_x_expected_reward"
                labels(ii) = "active IED count x expected reward";
            case "orange_vs_yellow"
                labels(ii) = "orange vs yellow";
            case "red_vs_yellow"
                labels(ii) = "red vs yellow";
            case "yellow_vs_orange"
                labels(ii) = "yellow vs orange";
            case "red_vs_orange"
                labels(ii) = "red vs orange";
            case "yellow_vs_red"
                labels(ii) = "yellow vs red";
            case "orange_vs_red"
                labels(ii) = "orange vs red";
            otherwise
                labels(ii) = replace(predictorNames(ii), "_", " ");
        end
    end

end

function plotExpectedRewardEffectPanel(ax, result, config)

    effectTable = result.modelEffectTable;
    x = effectTable.expectedReward;

    noIED = effectTable.relativeHazardNoIED;
    noIEDLow = effectTable.relativeHazardNoIEDCILow;
    noIEDHigh = effectTable.relativeHazardNoIEDCIHigh;

    postIED = effectTable.relativeHazardPostIED;
    postIEDLow = effectTable.relativeHazardPostIEDCILow;
    postIEDHigh = effectTable.relativeHazardPostIEDCIHigh;

    referenceExpectedReward = ...
        effectTable.referenceExpectedReward(1);

    hold(ax, 'on');

    lightPanelColor = 0.78 .* [1 1 1] + 0.22 .* config.color;

    fill( ...
        ax, ...
        [x; flipud(x)], ...
        [noIEDLow; flipud(noIEDHigh)], ...
        [0.78 0.78 0.78], ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.30, ...
        'HandleVisibility', 'off');

    fill( ...
        ax, ...
        [x; flipud(x)], ...
        [postIEDLow; flipud(postIEDHigh)], ...
        lightPanelColor, ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.45, ...
        'HandleVisibility', 'off');

    yline(ax, 1, '--', ...
        'Color', [0.45 0.45 0.45], ...
        'LineWidth', 1, ...
        'HandleVisibility', 'off');

    xline(ax, referenceExpectedReward, ':', ...
        'Color', [0.55 0.55 0.55], ...
        'LineWidth', 1, ...
        'HandleVisibility', 'off');

    noIEDLine = plot( ...
        ax, ...
        x, ...
        noIED, ...
        '--', ...
        'LineWidth', 2.0, ...
        'Color', [0.25 0.25 0.25], ...
        'DisplayName', '0 active IEDs');

    oneIEDLine = plot( ...
        ax, ...
        x, ...
        postIED, ...
        '-', ...
        'LineWidth', 2.3, ...
        'Color', config.color, ...
        'DisplayName', '1 active IED');

    set(ax, ...
        'YScale', 'log', ...
        'FontSize', 10, ...
        'FontName', 'Arial', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'TickDir', 'out');

    xlabel(ax, 'expected reward', 'Color', 'k');
    ylabel(ax, sprintf('relative %s hazard', ...
        char(config.hazardLabel)), 'Color', 'k');

    title(ax, sprintf('%s: adjusted expected-reward effect', ...
        char(config.code)), ...
        'Color', 'k', ...
        'FontWeight', 'bold');

    xMinimum = min(x);
    xMaximum = max(x);
    if xMaximum == xMinimum
        xlim(ax, [xMinimum - 0.5, xMaximum + 0.5]);
    else
        xPadding = 0.03 * (xMaximum - xMinimum);
        xlim(ax, [xMinimum - xPadding, xMaximum + xPadding]);
    end

    yLimits = calculatePositiveLogLimits( ...
        [noIEDLow; postIEDLow], ...
        [noIEDHigh; postIEDHigh]);
    ylim(ax, yLimits);

    interactionRow = result.coxResults( ...
        result.coxResults.predictor == ...
            "active_ied_count_x_expected_reward", :);

    resultText = sprintf([ ...
        '\\beta_{IEDxV} = %.3f\n' ...
        '95%% CI [%.3f, %.3f]\n' ...
        'p = %.3g\n' ...
        'slope at count 0 = %.3f\n' ...
        'slope at count 1 = %.3f'], ...
        interactionRow.beta_logHazard, ...
        interactionRow.betaCILow, ...
        interactionRow.betaCIHigh, ...
        interactionRow.pValue, ...
        result.expectedRewardSlopeOutsideIED, ...
        result.expectedRewardSlopeInsideIED);

    text( ...
        ax, ...
        0.97, ...
        0.96, ...
        resultText, ...
        'Units', 'normalized', ...
        'VerticalAlignment', 'top', ...
        'HorizontalAlignment', 'right', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'Interpreter', 'tex', ...
        'Color', 'k', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', [0.80 0.80 0.80], ...
        'Margin', 5);

    legend(ax, [noIEDLine, oneIEDLine], ...
        'Location', 'best', ...
        'Box', 'off', ...
        'FontSize', 8);

    grid(ax, 'off');
    box(ax, 'off');
    hold(ax, 'off');

end

function axisLimits = calculatePositiveLogLimits( ...
    lowerValues, upperValues)

    lowerValues = lowerValues(:);
    upperValues = upperValues(:);

    positiveLower = lowerValues( ...
        isfinite(lowerValues) & lowerValues > 0);

    positiveUpper = upperValues( ...
        isfinite(upperValues) & upperValues > 0);

    if isempty(positiveLower) || isempty(positiveUpper)
        axisLimits = [0.5 2];
        return;
    end

    minimumValue = min([positiveLower; positiveUpper; 1]);
    maximumValue = max([positiveLower; positiveUpper; 1]);

    logMinimum = log10(minimumValue);
    logMaximum = log10(maximumValue);

    if logMaximum == logMinimum
        logMinimum = logMinimum - 0.2;
        logMaximum = logMaximum + 0.2;
    else
        padding = 0.10 .* (logMaximum - logMinimum);
        logMinimum = logMinimum - padding;
        logMaximum = logMaximum + padding;
    end

    axisLimits = [10^logMinimum, 10^logMaximum];

end
