% Whole-IED participant-stratified Cox analyses for IT, RT, and BR

%
% Author: Nill

clear;
clc;
close all;

%% Paths

inputFolderName_LFPIED = ...
    'D:\Nill\data\BART\0_0_new_IED\IED1_find_number_of_IEDs\';

% Required CSV columns:
%   ptID, fit_alpha_plus, fit_alpha_minus
inputFolderName_Niv = ...
    'D:\Nill\code\BART\IED\0_0_new_IED\context_modeling\param_recovery_4_param_recovery\';

nivParameterFile = fullfile( ...
    inputFolderName_Niv, 'alpha_comparison.csv');

outputFolderName = ...
    'D:\Nill\code\BART\IED\0_0_new_IED\IED9_1_Cox_niv_param_occurrence\';

if ~exist(outputFolderName, 'dir')
    mkdir(outputFolderName);
end

%% Save Command Window output

textOutputFile = fullfile( ...
    outputFolderName, 'IT_RT_BR_whole_IED_x_Niv_console_output.txt');

diary off;
if exist(textOutputFile, 'file')
    delete(textOutputFile);
end

diary(textOutputFile);
diaryCleanup = onCleanup(@() diary('off'));

%% Shared settings

% Outcome-specific post-IED windows.
settings.postIEDWindowMillisecondsRT = 500;
settings.postIEDWindowMillisecondsIT = 1000;
settings.postIEDWindowMillisecondsBR = 1000;

settings.maximumRTSeconds = 20;
settings.defaultSamplingFrequencyHz = 1000;
settings.minimumParticipantsWithIED = 2;
settings.minimumEndpointEventsInsideWindow = 1;
settings.minimumEndpointEventsOutsideWindow = 1;
settings.numberOfNivCurvePoints = 200;

% Requested colors.
colorIT = [0.847  0.333  0.153];
colorRT = [0.204  0.459  0.702];
colorBR = [0.250  0.600  0.250];
markerAlpha = 0.5;

%% Read Niv parameters

[nivTable, nivSummary] = readNivParameterTable(nivParameterFile);

nivOutputFile = fullfile(outputFolderName, ...
    'niv_parameters_used.csv');
writetable(nivTable, nivOutputFile);

fprintf('============================================================\n');
fprintf('Loaded valid Niv parameters for %d participants.\n', ...
    height(nivTable));
fprintf('Niv file: %s\n', nivParameterFile);
fprintf('Mean raw Niv asymmetry: %.6f\n', nivSummary.mean);
fprintf('SD raw Niv asymmetry: %.6f\n', nivSummary.sd);
fprintf('============================================================\n');

%% Create participant-level Niv visualization

nivFigure = plotNivParameterVisualization(nivTable);

nivFigureOutputFile = fullfile( ...
    outputFolderName, ...
    'Niv_alpha_plus_alpha_minus_participant_visualization.pdf');

exportgraphics( ...
    nivFigure, ...
    nivFigureOutputFile, ...
    'ContentType', 'vector');

close(nivFigure);

fprintf('Niv visualization: %s\n', nivFigureOutputFile);

%% Run whole-IED analyses

IT = runWholeIEDOutcomeAnalysis( ...
    inputFolderName_LFPIED, "IT", settings, nivTable, nivSummary);

RT = runWholeIEDOutcomeAnalysis( ...
    inputFolderName_LFPIED, "RT", settings, nivTable, nivSummary);

BR = runWholeIEDOutcomeAnalysis( ...
    inputFolderName_LFPIED, "BR", settings, nivTable, nivSummary);

%% Save outcome-specific numerical outputs

saveOutcomeOutputs(IT, outputFolderName);
saveOutcomeOutputs(RT, outputFolderName);
saveOutcomeOutputs(BR, outputFolderName);

%% Create one combined 3 x 2 figure

combinedFigure = plotCombinedThreeByTwoFigure( ...
    IT, RT, BR, colorIT, colorRT, colorBR, markerAlpha);

combinedFigureOutputFile = fullfile(outputFolderName, ...
    'IT_RT_BR_whole_IED_x_Niv_3x2.pdf');

exportgraphics( ...
    combinedFigure, ...
    combinedFigureOutputFile, ...
    'ContentType', 'vector');

close(combinedFigure);

%% Save combined model file

combinedModelOutputFile = fullfile(outputFolderName, ...
    'IT_RT_BR_whole_IED_x_Niv_all_results.mat');

save( ...
    combinedModelOutputFile, ...
    'IT', 'RT', 'BR', ...
    'nivTable', 'nivSummary', 'nivParameterFile', ...
    'settings', 'colorIT', 'colorRT', 'colorBR', 'markerAlpha');

fprintf('\n============================================================\n');
fprintf('All whole-IED IED x Niv analyses finished.\n');
fprintf('Post-IED windows: IT = %d ms, RT = %d ms, BR = %d ms.\n', ...
    settings.postIEDWindowMillisecondsIT, ...
    settings.postIEDWindowMillisecondsRT, ...
    settings.postIEDWindowMillisecondsBR);
fprintf('Combined figure: %s\n', combinedFigureOutputFile);
fprintf('Combined model file: %s\n', combinedModelOutputFile);
fprintf('Niv table: %s\n', nivOutputFile);
fprintf('Niv visualization: %s\n', nivFigureOutputFile);
fprintf('Console output: %s\n', textOutputFile);
fprintf('============================================================\n');

diary off;
clear diaryCleanup;

%% Local functions

function result = runWholeIEDOutcomeAnalysis( ...
    inputFolderName_LFPIED, analysisType, settings, ...
    nivTable, nivSummary)

    [postIEDWindowMilliseconds, requiredFields] = ...
        getOutcomeSettings(analysisType, settings);

    postIEDWindowSeconds = postIEDWindowMilliseconds / 1000;

    fileList = dir(fullfile(inputFolderName_LFPIED, '*.LFPIED.mat'));

    if isempty(fileList)
        error('No .LFPIED.mat files were found in: %s', ...
            inputFolderName_LFPIED);
    end

    countingProcessData = emptyCountingProcessTable();
    trialSummary = emptyTrialSummaryTable();

    loadedParticipants = strings(0, 1);
    skippedNoNiv = strings(0, 1);
    skippedMissingData = strings(0, 1);

    fprintf('\n============================================================\n');
    fprintf('%s: building whole-IED counting-process data\n', analysisType);
    fprintf('Post-IED window: %d ms\n', postIEDWindowMilliseconds);
    fprintf('============================================================\n');

    for pt = 1:length(fileList)

        fileName = fileList(pt).name;
        fileNameParts = strsplit(fileName, '.');
        patientID = string(fileNameParts{1});

        fprintf('\nProcessing participant %s for %s\n', ...
            patientID, analysisType);

        [nivFound, alphaPlus, alphaMinus, ...
            nivAsymmetryRaw, nivAsymmetryZ] = ...
            getNivParametersForPatient(nivTable, patientID);

        if ~nivFound
            fprintf('Skipped: no matching valid Niv alpha parameters.\n');
            fprintf('Normalized LFPIED ID: %s\n', ...
                normalizeParticipantID(patientID));
            skippedNoNiv(end + 1, 1) = patientID;
            continue;
        end

        fprintf([ ...
            'Matched Niv values: alpha+ = %.4f, alpha- = %.4f, ' ...
            'raw Niv = %.4f, Niv z = %.4f\n'], ...
            alphaPlus, alphaMinus, nivAsymmetryRaw, nivAsymmetryZ);

        loadedData = load(fullfile(inputFolderName_LFPIED, fileName));

        if ~isfield(loadedData, 'LFPIED')
            fprintf('Skipped: LFPIED structure was not found.\n');
            skippedMissingData(end + 1, 1) = patientID;
            continue;
        end

        LFPIED = loadedData.LFPIED;

        missingField = false;

        for ff = 1:length(requiredFields)
            if ~isfield(LFPIED, requiredFields{ff})
                fprintf('Skipped: missing field %s.\n', requiredFields{ff});
                missingField = true;
            end
        end

        if missingField
            skippedMissingData(end + 1, 1) = patientID;
            continue;
        end

        RTs = double(LFPIED.RTs(:));
        isControl = double(LFPIED.isControl(:));
        balloonType = double(LFPIED.balloonType(:));
        balloonColorCode = mapBalloonColorCode(balloonType);

        switch analysisType
            case "RT"
                ITs = NaN(size(RTs));
                BankedTrials = NaN(size(RTs));
                vectorLengths = [ ...
                    length(RTs), ...
                    length(isControl), ...
                    length(balloonType)];
                IEDoccurrence = LFPIED.IED_occurance_RT;

            case "IT"
                ITs = double(LFPIED.ITs(:));
                BankedTrials = NaN(size(RTs));
                vectorLengths = [ ...
                    length(RTs), ...
                    length(ITs), ...
                    length(isControl), ...
                    length(balloonType)];
                IEDoccurrence = LFPIED.IED_occurance_IT;

            case "BR"
                ITs = double(LFPIED.ITs(:));
                BankedTrials = double(LFPIED.BankedTrials(:));
                vectorLengths = [ ...
                    length(RTs), ...
                    length(ITs), ...
                    length(BankedTrials), ...
                    length(isControl), ...
                    length(balloonType)];
                IEDoccurrence = LFPIED.IED_occurance_IT;

            otherwise
                error('Unknown analysis type: %s', analysisType);
        end

        if isfield(LFPIED, 'nTrials') && ...
                isscalar(LFPIED.nTrials) && ...
                isfinite(LFPIED.nTrials)
            vectorLengths(end + 1) = double(LFPIED.nTrials);
        end

        nTrials = floor(min(vectorLengths));

        if nTrials < 1
            fprintf('Skipped: no trials were available.\n');
            skippedMissingData(end + 1, 1) = patientID;
            continue;
        end

        RTs = RTs(1:nTrials);
        ITs = ITs(1:nTrials);
        BankedTrials = BankedTrials(1:nTrials);
        isControl = isControl(1:nTrials);
        balloonColorCode = balloonColorCode(1:nTrials);

        samplingFrequencyHz = getSamplingFrequency( ...
            LFPIED, settings.defaultSamplingFrequencyHz);

        participantTrialCountBefore = height(trialSummary);

        for trialNumber = 1:nTrials

            switch analysisType
                case "RT"
                    durationSeconds = RTs(trialNumber);
                    finalEventObserved = true;

                case "IT"
                    durationSeconds = ITs(trialNumber);
                    finalEventObserved = true;

                case "BR"
                    durationSeconds = ITs(trialNumber);
                    finalEventObserved = BankedTrials(trialNumber) == 1;
            end

            keepTrial = ...
                isControl(trialNumber) == 0 && ...
                isfinite(RTs(trialNumber)) && ...
                RTs(trialNumber) > 0 && ...
                RTs(trialNumber) <= settings.maximumRTSeconds && ...
                isfinite(durationSeconds) && ...
                durationSeconds > 0 && ...
                isfinite(balloonColorCode(trialNumber)) && ...
                ismember(balloonColorCode(trialNumber), [1 2 3]);

            if analysisType == "BR"
                keepTrial = keepTrial && ...
                    isfinite(BankedTrials(trialNumber)) && ...
                    ismember(BankedTrials(trialNumber), [0 1]);
            end

            if ~keepTrial
                continue;
            end

            trialRows = makePostIEDWindowRows( ...
                patientID, ...
                trialNumber, ...
                durationSeconds, ...
                IEDoccurrence, ...
                samplingFrequencyHz, ...
                balloonColorCode(trialNumber), ...
                finalEventObserved, ...
                postIEDWindowSeconds, ...
                alphaPlus, ...
                alphaMinus, ...
                nivAsymmetryRaw, ...
                nivAsymmetryZ);

            countingProcessData = [countingProcessData; trialRows]; 

            nIEDsInTrial = countValidIEDsInTrial( ...
                IEDoccurrence, trialNumber, durationSeconds, ...
                samplingFrequencyHz);

            intervalDuration = trialRows.tStop - trialRows.tStart;

            totalPostIEDExposureSeconds = sum( ...
                intervalDuration .* ...
                double(trialRows.postIED == 1), ...
                'omitnan');

            eventInPostIEDWindow = double( ...
                finalEventObserved && ...
                trialRows.postIED(end) == 1);

            newTrialSummaryRow = table( ...
                patientID, ...
                trialNumber, ...
                durationSeconds, ...
                double(finalEventObserved), ...
                eventInPostIEDWindow, ...
                nIEDsInTrial, ...
                totalPostIEDExposureSeconds, ...
                balloonColorCode(trialNumber), ...
                samplingFrequencyHz, ...
                alphaPlus, ...
                alphaMinus, ...
                nivAsymmetryRaw, ...
                nivAsymmetryZ, ...
                'VariableNames', trialSummary.Properties.VariableNames);

            trialSummary = [trialSummary; newTrialSummaryRow]; 

        end

        if height(trialSummary) > participantTrialCountBefore
            loadedParticipants(end + 1, 1) = patientID;
        else
            fprintf('No valid trials remained for this participant.\n');
        end

    end

    if isempty(countingProcessData)
        error('No valid counting-process rows were created for %s.', ...
            analysisType);
    end

    %% Build predictor matrix

    [countingProcessData.patientStratum, patientLevels] = ...
        findgroups(countingProcessData.patientID);

    iedOccurrence = countingProcessData.postIED;
    iedByNiv = iedOccurrence .* countingProcessData.nivAsymmetryZ;

    X = [iedOccurrence, iedByNiv];

    predictorNames = [ ...
        "any_ied_occurrence"; ...
        "any_ied_occurrence_x_niv_z"];

    predictorDisplayLabels = [ ...
        "Any IED occurrence"; ...
        "IED occurrence x Niv (1 SD)"];

    observedColors = unique( ...
        countingProcessData.balloonColorCode, 'sorted');
    observedColors = observedColors(ismember(observedColors, [1 2 3]));

    if isempty(observedColors)
        error('No valid balloon colors were found for %s.', analysisType);
    end

    if ismember(1, observedColors)
        referenceColor = 1;
    else
        referenceColor = observedColors(1);
    end

    colorNames = ["yellow", "orange", "red"];
    comparisonColors = observedColors(observedColors ~= referenceColor);

    for cc = 1:length(comparisonColors)
        colorCode = comparisonColors(cc);
        X(:, end + 1) = double( ...
            countingProcessData.balloonColorCode == colorCode); 

        predictorNames(end + 1, 1) = ...
            colorNames(colorCode) + "_vs_" + colorNames(referenceColor); 

        predictorDisplayLabels(end + 1, 1) = ...
            capitalizeFirst(colorNames(colorCode)) + ...
            " vs " + capitalizeFirst(colorNames(referenceColor)); 
    end

    T = [countingProcessData.tStart, countingProcessData.tStop];
    censoring = logical(countingProcessData.censored);
    strata = countingProcessData.patientStratum;

    validRows = ...
        all(isfinite(X), 2) & ...
        all(isfinite(T), 2) & ...
        T(:, 1) >= 0 & ...
        T(:, 2) > T(:, 1) & ...
        isfinite(strata);

    X = X(validRows, :);
    T = T(validRows, :);
    censoring = censoring(validRows);
    strata = strata(validRows);
    countingProcessData = countingProcessData(validRows, :);

    %% Model diagnostics before fitting

    nModelParticipants = length(unique(countingProcessData.patientID));

    participantsWithIED = unique( ...
        countingProcessData.patientID( ...
        countingProcessData.activeIEDWindowCount > 0));

    nParticipantsWithIED = length(participantsWithIED);

    nEndpointEvents = sum(countingProcessData.eventAtStop == 1);

    nEventsOutsideWindow = sum( ...
        countingProcessData.eventAtStop == 1 & ...
        countingProcessData.postIED == 0);

    nEventsInsideWindow = sum( ...
        countingProcessData.eventAtStop == 1 & ...
        countingProcessData.postIED == 1);

    intervalDuration = ...
        countingProcessData.tStop - countingProcessData.tStart;

    timeOutsideWindowSeconds = sum( ...
        intervalDuration .* ...
        double(countingProcessData.postIED == 0), ...
        'omitnan');

    timeInsideWindowSeconds = sum( ...
        intervalDuration .* ...
        double(countingProcessData.postIED == 1), ...
        'omitnan');

    if nParticipantsWithIED < settings.minimumParticipantsWithIED
        error([ ...
            '%s has only %d participants with IED exposure. ' ...
            'At least %d are required for the IED x Niv interaction.'], ...
            analysisType, nParticipantsWithIED, ...
            settings.minimumParticipantsWithIED);
    end

    if timeInsideWindowSeconds <= 0
        error('No post-IED exposure time was available for %s.', ...
            analysisType);
    end

    if nEventsInsideWindow < ...
            settings.minimumEndpointEventsInsideWindow
        warning('%s has no endpoint events inside post-IED windows.', ...
            analysisType);
    end

    if nEventsOutsideWindow < ...
            settings.minimumEndpointEventsOutsideWindow
        warning('%s has no endpoint events outside post-IED windows.', ...
            analysisType);
    end

    if size(X, 1) <= size(X, 2)
        error('Insufficient rows for the %s predictor matrix.', ...
            analysisType);
    end

    if std(X(:, 1), 0, 'omitnan') <= eps
        error('The IED occurrence indicator has no variation for %s.', ...
            analysisType);
    end

    if std(X(:, 2), 0, 'omitnan') <= eps
        error('The IED x Niv interaction has no variation for %s.', ...
            analysisType);
    end

    %% Fit participant-stratified Cox model

    coxOptions = statset('coxphfit');
    coxOptions.Display = 'final';
    coxOptions.MaxIter = 1000;
    coxOptions.MaxFunEvals = 5000;

    [beta, logLikelihood, baselineCumulativeHazard, stats] = ...
        coxphfit( ...
            X, ...
            T, ...
            'Censoring', censoring, ...
            'Strata', strata, ...
            'Ties', 'efron', ...
            'Baseline', 0, ...
            'Options', coxOptions);

    %% Participant-clustered robust inference

    [clusterRobustCovariance, clusterRobustSE, ...
        clusterRobustZ, clusterRobustP] = ...
        computeClusterRobustInference( ...
            stats, beta, countingProcessData.patientStratum);

    %% Results table

    ciLowBeta = beta - 1.96 .* clusterRobustSE;
    ciHighBeta = beta + 1.96 .* clusterRobustSE;

    hazardRatio = exp(beta);
    hazardRatioCILow = exp(ciLowBeta);
    hazardRatioCIHigh = exp(ciHighBeta);

    interpretation = strings(length(beta), 1);

    interpretation(1) = getIEDMainEffectInterpretation(analysisType);
    interpretation(2) = ...
        "Multiplicative change in the IED hazard ratio per 1-SD increase in Niv asymmetry.";

    if length(beta) > 2
        interpretation(3:end) = ...
            "Balloon-color effect relative to the reference color.";
    end

    coxResults = table( ...
        predictorNames(:), ...
        predictorDisplayLabels(:), ...
        beta(:), ...
        stats.se(:), ...
        stats.z(:), ...
        stats.p(:), ...
        clusterRobustSE(:), ...
        clusterRobustZ(:), ...
        clusterRobustP(:), ...
        ciLowBeta(:), ...
        ciHighBeta(:), ...
        hazardRatio(:), ...
        hazardRatioCILow(:), ...
        hazardRatioCIHigh(:), ...
        interpretation(:), ...
        'VariableNames', { ...
            'predictor', ...
            'displayLabel', ...
            'beta_logHazard', ...
            'modelBasedSE', ...
            'modelBasedZ', ...
            'modelBasedPValue', ...
            'clusterRobustSE', ...
            'clusterRobustZ', ...
            'pValue', ...
            'betaCILow', ...
            'betaCIHigh', ...
            'hazardRatio', ...
            'hazardRatioCILow', ...
            'hazardRatioCIHigh', ...
            'interpretation'});

    %% Create Niv moderation curve

    observedPatientRows = unique( ...
        countingProcessData(:, { ...
            'patientID', 'nivAsymmetryRaw', 'nivAsymmetryZ'}), ...
        'rows', 'stable');

    nivCurveTable = createNivModerationCurve( ...
        beta, clusterRobustCovariance, ...
        observedPatientRows.nivAsymmetryRaw, ...
        nivSummary, settings.numberOfNivCurvePoints);

    %% Print outcome summary

    fprintf('\n============================================================\n');
    fprintf('%s whole-IED Cox model with Niv moderation\n', analysisType);
    fprintf('============================================================\n');
    fprintf('Post-IED window: %d ms\n', postIEDWindowMilliseconds);
    fprintf('Participants in model: %d\n', nModelParticipants);
    fprintf('Participants with IED exposure: %d\n', ...
        nParticipantsWithIED);
    fprintf('Valid trials: %d\n', height(trialSummary));
    fprintf('Counting-process rows: %d\n', ...
        height(countingProcessData));
    fprintf('Endpoint events: %d\n', nEndpointEvents);
    fprintf('Events outside window: %d\n', ...
        nEventsOutsideWindow);
    fprintf('Events inside window: %d\n', ...
        nEventsInsideWindow);
    fprintf('At-risk time outside window: %.3f s\n', ...
        timeOutsideWindowSeconds);
    fprintf('At-risk time inside window: %.3f s\n', ...
        timeInsideWindowSeconds);
    fprintf('Log likelihood: %.6f\n\n', logLikelihood);

    disp(coxResults);

    mainIEDRow = coxResults(1, :);
    interactionRow = coxResults(2, :);

    fprintf('\nIED effect at mean Niv asymmetry:\n');
    fprintf('beta = %.6f\n', mainIEDRow.beta_logHazard);
    fprintf('HR for any IED occurrence versus none = %.6f\n', ...
        mainIEDRow.hazardRatio);
    fprintf('95%% CI = [%.6f, %.6f]\n', ...
        mainIEDRow.hazardRatioCILow, ...
        mainIEDRow.hazardRatioCIHigh);
    fprintf('p = %.6g\n', mainIEDRow.pValue);

    fprintf('\nIED x Niv interaction:\n');
    fprintf('beta = %.6f\n', interactionRow.beta_logHazard);
    fprintf('HR multiplier per 1-SD increase in Niv = %.6f\n', ...
        interactionRow.hazardRatio);
    fprintf('95%% CI = [%.6f, %.6f]\n', ...
        interactionRow.hazardRatioCILow, ...
        interactionRow.hazardRatioCIHigh);
    fprintf('p = %.6g\n', interactionRow.pValue);

    if interactionRow.pValue < 0.05
        if interactionRow.beta_logHazard > 0
            fprintf([ ...
                'Conclusion: the IED hazard effect becomes more positive ' ...
                'as Niv asymmetry increases.\n']);
        else
            fprintf([ ...
                'Conclusion: the IED hazard effect becomes more negative ' ...
                'as Niv asymmetry increases.\n']);
        end
    else
        fprintf([ ...
            'Conclusion: Niv asymmetry does not significantly moderate ' ...
            'the IED hazard effect.\n']);
    end

    %% Return all outputs

    result = struct();
    result.analysisType = analysisType;
    result.postIEDWindowMilliseconds = postIEDWindowMilliseconds;
    result.postIEDWindowSeconds = postIEDWindowSeconds;
    result.countingProcessData = countingProcessData;
    result.trialSummary = trialSummary;
    result.coxResults = coxResults;
    result.nivCurveTable = nivCurveTable;
    result.observedPatientNiv = observedPatientRows;
    result.beta = beta;
    result.logLikelihood = logLikelihood;
    result.baselineCumulativeHazard = baselineCumulativeHazard;
    result.stats = stats;
    result.clusterRobustCovariance = clusterRobustCovariance;
    result.clusterRobustSE = clusterRobustSE;
    result.clusterRobustZ = clusterRobustZ;
    result.clusterRobustP = clusterRobustP;
    result.predictorNames = predictorNames;
    result.predictorDisplayLabels = predictorDisplayLabels;
    result.patientLevels = patientLevels;
    result.loadedParticipants = unique(loadedParticipants, 'stable');
    result.skippedNoNiv = unique(skippedNoNiv, 'stable');
    result.skippedMissingData = unique(skippedMissingData, 'stable');
    result.referenceBalloonColor = colorNames(referenceColor);
    result.nModelParticipants = nModelParticipants;
    result.nParticipantsWithIED = nParticipantsWithIED;
    result.nEndpointEvents = nEndpointEvents;
    result.nEventsOutsideWindow = nEventsOutsideWindow;
    result.nEventsInsideWindow = nEventsInsideWindow;
    result.timeOutsideWindowSeconds = timeOutsideWindowSeconds;
    result.timeInsideWindowSeconds = timeInsideWindowSeconds;

end

function [postIEDWindowMilliseconds, requiredFields] = ...
    getOutcomeSettings(analysisType, settings)

    switch analysisType
        case "RT"
            postIEDWindowMilliseconds = ...
                settings.postIEDWindowMillisecondsRT;
            requiredFields = { ...
                'RTs', 'isControl', 'balloonType', ...
                'IED_occurance_RT'};

        case "IT"
            postIEDWindowMilliseconds = ...
                settings.postIEDWindowMillisecondsIT;
            requiredFields = { ...
                'RTs', 'ITs', 'isControl', 'balloonType', ...
                'IED_occurance_IT'};

        case "BR"
            postIEDWindowMilliseconds = ...
                settings.postIEDWindowMillisecondsBR;
            requiredFields = { ...
                'RTs', 'ITs', 'BankedTrials', ...
                'isControl', 'balloonType', ...
                'IED_occurance_IT'};

        otherwise
            error('Unknown analysis type: %s', analysisType);
    end

end

function saveOutcomeOutputs(result, outputFolderName)

    prefix = char(result.analysisType);

    countingProcessOutputFile = fullfile( ...
        outputFolderName, ...
        sprintf('%s_whole_IED_x_Niv_counting_process_data.csv', prefix));

    trialSummaryOutputFile = fullfile( ...
        outputFolderName, ...
        sprintf('%s_whole_IED_x_Niv_trial_summary.csv', prefix));

    coxResultsOutputFile = fullfile( ...
        outputFolderName, ...
        sprintf('%s_whole_IED_x_Niv_cox_results.csv', prefix));

    nivCurveOutputFile = fullfile( ...
        outputFolderName, ...
        sprintf('%s_whole_IED_x_Niv_moderation_curve.csv', prefix));

    patientNivOutputFile = fullfile( ...
        outputFolderName, ...
        sprintf('%s_whole_IED_x_Niv_patient_values.csv', prefix));

    baselineHazardOutputFile = fullfile( ...
        outputFolderName, ...
        sprintf('%s_whole_IED_x_Niv_baseline_cumulative_hazard.csv', prefix));

    modelOutputFile = fullfile( ...
        outputFolderName, ...
        sprintf('%s_whole_IED_x_Niv_model.mat', prefix));

    writetable(result.countingProcessData, countingProcessOutputFile);
    writetable(result.trialSummary, trialSummaryOutputFile);
    writetable(result.coxResults, coxResultsOutputFile);
    writetable(result.nivCurveTable, nivCurveOutputFile);
    writetable(result.observedPatientNiv, patientNivOutputFile);
    writematrix(result.baselineCumulativeHazard, ...
        baselineHazardOutputFile);

    outcomeResult = result; 
    save(modelOutputFile, 'outcomeResult');

    fprintf('\nSaved %s outputs:\n', prefix);
    fprintf('%s\n', countingProcessOutputFile);
    fprintf('%s\n', trialSummaryOutputFile);
    fprintf('%s\n', coxResultsOutputFile);
    fprintf('%s\n', nivCurveOutputFile);
    fprintf('%s\n', patientNivOutputFile);
    fprintf('%s\n', baselineHazardOutputFile);
    fprintf('%s\n', modelOutputFile);

end

function fig = plotCombinedThreeByTwoFigure( ...
    IT, RT, BR, colorIT, colorRT, colorBR, markerAlpha)

    fig = figure('Visible', 'off', 'Color', 'w');
    set(fig, 'Position', [60 40 1550 1500]);

    layout = tiledlayout(fig, 3, 2, ...
        'Padding', 'compact', ...
        'TileSpacing', 'compact');

    ax1 = nexttile(layout, 1);
    plotOutcomeForestPanel(ax1, IT, colorIT, markerAlpha, ...
        "Inflation time (IT)");

    ax2 = nexttile(layout, 2);
    plotNivModerationPanel(ax2, IT, colorIT, ...
        "Inflation time (IT)");

    ax3 = nexttile(layout, 3);
    plotOutcomeForestPanel(ax3, RT, colorRT, markerAlpha, ...
        "Response time (RT)");

    ax4 = nexttile(layout, 4);
    plotNivModerationPanel(ax4, RT, colorRT, ...
        "Response time (RT)");

    ax5 = nexttile(layout, 5);
    plotOutcomeForestPanel(ax5, BR, colorBR, markerAlpha, ...
        "Banking (BR)");

    ax6 = nexttile(layout, 6);
    plotNivModerationPanel(ax6, BR, colorBR, ...
        "Banking (BR)");

    title(layout, ...
        'Whole-IED effects moderated by Niv learning asymmetry', ...
        'FontWeight', 'bold', ...
        'FontSize', 16);

end

function plotOutcomeForestPanel( ...
    ax, result, panelColor, markerAlpha, descriptiveTitle)

    data = result.coxResults;
    nPredictors = height(data);
    yPositions = (1:nPredictors)';

    hold(ax, 'on');

    xline(ax, 1, '--', ...
        'Color', [0.35 0.35 0.35], ...
        'LineWidth', 1.1);

    for ii = 1:nPredictors
        plot(ax, ...
            [data.hazardRatioCILow(ii), ...
             data.hazardRatioCIHigh(ii)], ...
            [yPositions(ii), yPositions(ii)], ...
            '-', ...
            'Color', panelColor, ...
            'LineWidth', 1.6);
    end

    scatter(ax, ...
        data.hazardRatio, ...
        yPositions, ...
        64, ...
        panelColor, ...
        'filled', ...
        'MarkerFaceAlpha', markerAlpha, ...
        'MarkerEdgeColor', 'none');

    ax.XScale = 'log';
    ax.YDir = 'reverse';
    ax.YTick = yPositions;
    ax.YTickLabel = data.displayLabel;
    ax.TickLabelInterpreter = 'none';
    ax.TickDir = 'out';
    ax.FontName = 'Arial';
    ax.FontSize = 10;
    ax.XColor = 'k';
    ax.YColor = 'k';

    xLimits = calculatePositiveLogLimits( ...
        data.hazardRatioCILow, data.hazardRatioCIHigh);
    xlim(ax, xLimits);
    ylim(ax, [0.5, nPredictors + 0.5]);

    xlabel(ax, 'Hazard ratio with robust 95% CI');
    title(ax, {char(descriptiveTitle), ...
        sprintf('%d-ms post-IED Cox estimates', ...
        result.postIEDWindowMilliseconds)}, ...
        'FontWeight', 'bold');

    grid(ax, 'off');
    box(ax, 'off');
    hold(ax, 'off');

end

function plotNivModerationPanel( ...
    ax, result, panelColor, descriptiveTitle)

    curve = result.nivCurveTable;
    interactionRow = result.coxResults(2, :);

    lightColor = 0.78 .* [1 1 1] + 0.22 .* panelColor;

    hold(ax, 'on');

    fill(ax, ...
        [curve.nivAsymmetryRaw; ...
         flipud(curve.nivAsymmetryRaw)], ...
        [curve.hazardRatioCILow; ...
         flipud(curve.hazardRatioCIHigh)], ...
        lightColor, ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.60);

    yline(ax, 1, '--', ...
        'Color', [0.45 0.45 0.45], ...
        'LineWidth', 1.0);

    xline(ax, 0, ':', ...
        'Color', [0.55 0.55 0.55], ...
        'LineWidth', 1.0);

    plot(ax, ...
        curve.nivAsymmetryRaw, ...
        curve.hazardRatioPerAdditionalIED, ...
        '-', ...
        'Color', panelColor, ...
        'LineWidth', 2.3);

    participantNiv = result.observedPatientNiv.nivAsymmetryRaw;
    participantNiv = participantNiv(isfinite(participantNiv));

    yLimits = calculatePositiveLogLimits( ...
        curve.hazardRatioCILow, curve.hazardRatioCIHigh);

    rugY = repmat( ...
        10^(log10(yLimits(1)) + ...
        0.035 * (log10(yLimits(2)) - log10(yLimits(1)))), ...
        length(participantNiv), 1);

    scatter(ax, ...
        participantNiv, ...
        rugY, ...
        14, ...
        panelColor, ...
        'filled', ...
        'MarkerFaceAlpha', 0.35, ...
        'MarkerEdgeColor', 'none');

    ax.YScale = 'log';
    ax.TickDir = 'out';
    ax.FontName = 'Arial';
    ax.FontSize = 10;
    ax.XColor = 'k';
    ax.YColor = 'k';

    xMinimum = min(curve.nivAsymmetryRaw);
    xMaximum = max(curve.nivAsymmetryRaw);
    xPadding = max(0.03, 0.04 * (xMaximum - xMinimum));
    xlim(ax, [xMinimum - xPadding, xMaximum + xPadding]);
    ylim(ax, yLimits);

    xlabel(ax, ...
        'Niv asymmetry: (\alpha^- - \alpha^+) / (\alpha^- + \alpha^+)');
    ylabel(ax, 'HR for any IED occurrence vs none');

    title(ax, {char(descriptiveTitle), ...
        'IED effect across Niv asymmetry'}, ...
        'FontWeight', 'bold');

    resultText = sprintf([ ...
        'IED x Niv beta = %.3f\n' ...
        'HR multiplier per 1 SD = %.3f\n' ...
        '95%% CI [%.3f, %.3f]\n' ...
        'p = %.3g'], ...
        interactionRow.beta_logHazard, ...
        interactionRow.hazardRatio, ...
        interactionRow.hazardRatioCILow, ...
        interactionRow.hazardRatioCIHigh, ...
        interactionRow.pValue);

    text(ax, ...
        0.97, 0.96, resultText, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'top', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'BackgroundColor', 'w', ...
        'EdgeColor', [0.82 0.82 0.82], ...
        'Margin', 5);

    grid(ax, 'off');
    box(ax, 'off');
    hold(ax, 'off');

end

function curveTable = createNivModerationCurve( ...
    beta, robustCovariance, observedNivRaw, ...
    nivSummary, numberOfCurvePoints)

    observedNivRaw = observedNivRaw(:);
    observedNivRaw = observedNivRaw(isfinite(observedNivRaw));

    if isempty(observedNivRaw)
        error('No observed participant Niv values were available.');
    end

    minimumNiv = min(observedNivRaw);
    maximumNiv = max(observedNivRaw);

    if minimumNiv == maximumNiv
        minimumNiv = minimumNiv - 0.01;
        maximumNiv = maximumNiv + 0.01;
    end

    nivAsymmetryRaw = linspace( ...
        minimumNiv, maximumNiv, numberOfCurvePoints)';

    nivAsymmetryZ = ...
        (nivAsymmetryRaw - nivSummary.mean) ./ nivSummary.sd;

    betaIED = beta(1);
    betaInteraction = beta(2);

    logHazardRatio = ...
        betaIED + betaInteraction .* nivAsymmetryZ;

    varianceLogHazardRatio = ...
        robustCovariance(1, 1) + ...
        (nivAsymmetryZ .^ 2) .* robustCovariance(2, 2) + ...
        2 .* nivAsymmetryZ .* robustCovariance(1, 2);

    varianceLogHazardRatio = max(varianceLogHazardRatio, 0);
    standardErrorLogHazardRatio = sqrt(varianceLogHazardRatio);

    logHazardRatioCILow = ...
        logHazardRatio - 1.96 .* standardErrorLogHazardRatio;

    logHazardRatioCIHigh = ...
        logHazardRatio + 1.96 .* standardErrorLogHazardRatio;

    hazardRatioPerAdditionalIED = exp(logHazardRatio);
    hazardRatioCILow = exp(logHazardRatioCILow);
    hazardRatioCIHigh = exp(logHazardRatioCIHigh);

    curveTable = table( ...
        nivAsymmetryRaw, ...
        nivAsymmetryZ, ...
        logHazardRatio, ...
        standardErrorLogHazardRatio, ...
        logHazardRatioCILow, ...
        logHazardRatioCIHigh, ...
        hazardRatioPerAdditionalIED, ...
        hazardRatioCILow, ...
        hazardRatioCIHigh, ...
        'VariableNames', { ...
            'nivAsymmetryRaw', ...
            'nivAsymmetryZ', ...
            'logHazardRatioPerAdditionalIED', ...
            'standardErrorLogHazardRatio', ...
            'logHazardRatioCILow', ...
            'logHazardRatioCIHigh', ...
            'hazardRatioPerAdditionalIED', ...
            'hazardRatioCILow', ...
            'hazardRatioCIHigh'});

end

function fig = plotNivParameterVisualization(nivTable)

    patientID = string(nivTable.patientID);
    alphaPlus = double(nivTable.alphaPlus);
    alphaMinus = double(nivTable.alphaMinus);
    nivRaw = double(nivTable.nivAsymmetryRaw);

    validRows = ...
        ~ismissing(patientID) & ...
        isfinite(alphaPlus) & ...
        isfinite(alphaMinus) & ...
        isfinite(nivRaw);

    patientID = patientID(validRows);
    alphaPlus = alphaPlus(validRows);
    alphaMinus = alphaMinus(validRows);
    nivRaw = nivRaw(validRows);

    nParticipants = length(patientID);

    if nParticipants < 1
        error('No valid participant-level Niv values were available.');
    end

    [nivSorted, sortOrder] = sort(nivRaw, 'ascend');
    patientIDSorted = patientID(sortOrder);

    maximumAbsoluteNiv = max(abs(nivRaw));

    if ~isfinite(maximumAbsoluteNiv) || maximumAbsoluteNiv <= eps
        maximumAbsoluteNiv = 1;
    end

    colorLimits = [-maximumAbsoluteNiv, maximumAbsoluteNiv];
    divergingColorMap = createBlueWhiteRedColorMap(256);

    fig = figure( ...
        'Visible', 'off', ...
        'Color', 'w', ...
        'Position', [40 40 1800 1250]);

    layout = tiledlayout( ...
        fig, 1, 2, ...
        'Padding', 'compact', ...
        'TileSpacing', 'compact');

    % Older MATLAB-compatible syntax.
    set(fig, 'Colormap', divergingColorMap);

    %% Panel A: alpha+ versus alpha-

    ax1 = nexttile(layout, 1);
    hold(ax1, 'on');

    allAlphaValues = [alphaPlus; alphaMinus];

    alphaMinimum = min(allAlphaValues);
    alphaMaximum = max(allAlphaValues);
    alphaRange = alphaMaximum - alphaMinimum;

    if ~isfinite(alphaRange) || alphaRange <= eps
        alphaRange = max(abs(alphaMaximum), 1);
    end

    alphaPadding = 0.08 * alphaRange;
    alphaAxisMinimum = max(0, alphaMinimum - alphaPadding);
    alphaAxisMaximum = alphaMaximum + alphaPadding;

    if alphaAxisMaximum <= alphaAxisMinimum
        alphaAxisMaximum = alphaAxisMinimum + 1;
    end

    % Light shading above the equality line.
    fill(ax1, ...
        [alphaAxisMinimum, alphaAxisMaximum, ...
         alphaAxisMaximum, alphaAxisMinimum], ...
        [alphaAxisMinimum, alphaAxisMaximum, ...
         alphaAxisMaximum, alphaAxisMaximum], ...
        [0.96 0.96 0.96], ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.45);

    % Equality line: alpha- = alpha+.
    plot(ax1, ...
        [alphaAxisMinimum, alphaAxisMaximum], ...
        [alphaAxisMinimum, alphaAxisMaximum], ...
        '--', ...
        'Color', [0.35 0.35 0.35], ...
        'LineWidth', 1.4);

    scatter(ax1, ...
        alphaPlus, ...
        alphaMinus, ...
        92, ...
        nivRaw, ...
        'filled', ...
        'MarkerFaceAlpha', 0.75, ...
        'MarkerEdgeColor', 'none');

    % Set color limits directly to avoid clim/caxis handle compatibility issues.
    set(ax1, 'CLim', colorLimits);

    % Label the participants with the most extreme Niv values.
    numberToLabelPerSide = min(4, floor(nParticipants / 2));

    if numberToLabelPerSide > 0
        [~, ascendingOrder] = sort(nivRaw, 'ascend');

        negativeExtremeRows = ...
            ascendingOrder(1:numberToLabelPerSide);

        positiveExtremeRows = ...
            ascendingOrder(end-numberToLabelPerSide+1:end);

        rowsToLabel = unique([ ...
            negativeExtremeRows(:); ...
            positiveExtremeRows(:)]);

        xOffset = 0.012 * ...
            (alphaAxisMaximum - alphaAxisMinimum);

        yOffset = 0.012 * ...
            (alphaAxisMaximum - alphaAxisMinimum);

        for ii = 1:length(rowsToLabel)

            rowNumber = rowsToLabel(ii);

            text(ax1, ...
                alphaPlus(rowNumber) + xOffset, ...
                alphaMinus(rowNumber) + yOffset, ...
                patientID(rowNumber), ...
                'FontName', 'Arial', ...
                'FontSize', 8, ...
                'Interpreter', 'none', ...
                'Color', [0.20 0.20 0.20]);

        end
    end

    xlim(ax1, [alphaAxisMinimum, alphaAxisMaximum]);
    ylim(ax1, [alphaAxisMinimum, alphaAxisMaximum]);
    axis(ax1, 'square');

    xlabel(ax1, ...
        'Fitted positive learning rate, \alpha^+', ...
        'Interpreter', 'tex');

    ylabel(ax1, ...
        'Fitted negative learning rate, \alpha^-', ...
        'Interpreter', 'tex');

    title(ax1, { ...
        '\alpha^+ versus \alpha^- by participant', ...
        'Distance from the equality line determines Niv asymmetry'}, ...
        'FontWeight', 'bold');

    ax1.TickDir = 'out';
    ax1.FontName = 'Arial';
    ax1.FontSize = 11;
    ax1.Layer = 'top';

    grid(ax1, 'off');
    box(ax1, 'off');

    colorBar = colorbar(ax1);
    colorBar.Label.String = ...
        'Niv = (\alpha^- - \alpha^+) / (\alpha^- + \alpha^+)';
    colorBar.Label.Interpreter = 'tex';
    colorBar.TickDirection = 'out';

    text(ax1, ...
        0.04, 0.95, ...
        {'Above line:', '\alpha^- > \alpha^+', 'Niv > 0'}, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'Color', [0.45 0.10 0.10], ...
        'BackgroundColor', 'w', ...
        'Margin', 4);

    text(ax1, ...
        0.96, 0.05, ...
        {'Below line:', '\alpha^+ > \alpha^-', 'Niv < 0'}, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'bottom', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'Color', [0.10 0.20 0.50], ...
        'BackgroundColor', 'w', ...
        'Margin', 4);

    hold(ax1, 'off');

    %% Panel B: sorted participant Niv values

    ax2 = nexttile(layout, 2);
    hold(ax2, 'on');

    participantPositions = (1:nParticipants)';

    xline(ax2, ...
        0, ...
        '--', ...
        'Color', [0.25 0.25 0.25], ...
        'LineWidth', 1.3);

    for ii = 1:nParticipants

        lineColor = mapValueToDivergingColor( ...
            nivSorted(ii), ...
            colorLimits, ...
            divergingColorMap);

        plot(ax2, ...
            [0, nivSorted(ii)], ...
            [participantPositions(ii), ...
             participantPositions(ii)], ...
            '-', ...
            'Color', lineColor, ...
            'LineWidth', 2.2);

    end

    scatter(ax2, ...
        nivSorted, ...
        participantPositions, ...
        62, ...
        nivSorted, ...
        'filled', ...
        'MarkerFaceAlpha', 0.85, ...
        'MarkerEdgeColor', 'none');

    % Set color limits directly to avoid clim/caxis handle compatibility issues.
    set(ax2, 'CLim', colorLimits);

    ax2.YDir = 'reverse';
    ax2.YTick = participantPositions;
    ax2.YTickLabel = patientIDSorted;
    ax2.TickLabelInterpreter = 'none';

    ylim(ax2, [0.3, nParticipants + 0.7]);

    nivPadding = 0.12 * ...
        max(max(nivSorted) - min(nivSorted), 0.1);

    xlim(ax2, [ ...
        min([nivSorted; 0]) - nivPadding, ...
        max([nivSorted; 0]) + nivPadding]);

    xlabel(ax2, 'Niv learning-rate asymmetry');

    ylabel(ax2, ...
        sprintf('Participants sorted by Niv, n = %d', ...
        nParticipants));

    title(ax2, { ...
        'Participant-level Niv asymmetry', ...
        'Negative: \alpha^+ dominant   |   Positive: \alpha^- dominant'}, ...
        'FontWeight', 'bold');

    ax2.TickDir = 'out';
    ax2.FontName = 'Arial';

    if nParticipants <= 40
        ax2.FontSize = 9;
    elseif nParticipants <= 70
        ax2.FontSize = 7.5;
    else
        ax2.FontSize = 6.5;
    end

    grid(ax2, 'off');
    box(ax2, 'off');

    medianNiv = median(nivRaw, 'omitnan');
    meanNiv = mean(nivRaw, 'omitnan');

    numberPositive = sum(nivRaw > 0);
    numberNegative = sum(nivRaw < 0);
    numberApproximatelyZero = sum(abs(nivRaw) <= 1e-12);

    summaryText = sprintf([ ...
        'Mean = %.3f\n' ...
        'Median = %.3f\n' ...
        'Niv > 0: %d\n' ...
        'Niv < 0: %d\n' ...
        'Niv = 0: %d'], ...
        meanNiv, ...
        medianNiv, ...
        numberPositive, ...
        numberNegative, ...
        numberApproximatelyZero);

    text(ax2, ...
        0.97, 0.98, ...
        summaryText, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'top', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'BackgroundColor', 'w', ...
        'EdgeColor', [0.82 0.82 0.82], ...
        'Margin', 6);

    hold(ax2, 'off');

    title(layout, { ...
        'Fitted learning rates and Niv asymmetry', ...
        '\rmNiv = (\alpha^- - \alpha^+) / (\alpha^- + \alpha^+)'}, ...
        'Interpreter', 'tex', ...
        'FontWeight', 'bold', ...
        'FontSize', 17);

end

function colorMap = createBlueWhiteRedColorMap(numberOfColors)

    if nargin < 1
        numberOfColors = 256;
    end

    numberOfColors = max(round(numberOfColors), 3);

    numberLower = floor(numberOfColors / 2);
    numberUpper = numberOfColors - numberLower;

    blueColor = [0.12 0.35 0.75];
    whiteColor = [0.97 0.97 0.97];
    redColor = [0.78 0.18 0.18];

    lowerHalf = [ ...
        linspace(blueColor(1), whiteColor(1), numberLower)', ...
        linspace(blueColor(2), whiteColor(2), numberLower)', ...
        linspace(blueColor(3), whiteColor(3), numberLower)'];

    upperHalf = [ ...
        linspace(whiteColor(1), redColor(1), numberUpper)', ...
        linspace(whiteColor(2), redColor(2), numberUpper)', ...
        linspace(whiteColor(3), redColor(3), numberUpper)'];

    colorMap = [lowerHalf; upperHalf];

end

function outputColor = mapValueToDivergingColor( ...
    value, colorLimits, colorMap)

    minimumValue = colorLimits(1);
    maximumValue = colorLimits(2);

    if maximumValue <= minimumValue
        outputColor = colorMap( ...
            round(size(colorMap, 1) / 2), :);
        return;
    end

    normalizedValue = ...
        (value - minimumValue) / ...
        (maximumValue - minimumValue);

    normalizedValue = min(max(normalizedValue, 0), 1);

    colorIndex = 1 + round( ...
        normalizedValue * (size(colorMap, 1) - 1));

    colorIndex = min(max(colorIndex, 1), ...
        size(colorMap, 1));

    outputColor = colorMap(colorIndex, :);

end

function trialRows = makePostIEDWindowRows( ...
    patientID, trialNumber, durationSeconds, IEDoccurrence, ...
    samplingFrequencyHz, balloonColorCode, finalEventObserved, ...
    postIEDWindowSeconds, alphaPlus, alphaMinus, ...
    nivAsymmetryRaw, nivAsymmetryZ)

    % IEDoccurrence columns:
    %   1 = trial number
    %   2 = channel
    %   3 = sample index from the beginning of RT or IT

    if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 3
        IEDtimes = [];
    else
        validIEDRows = ...
            isfinite(IEDoccurrence(:, 1)) & ...
            isfinite(IEDoccurrence(:, 3)) & ...
            round(IEDoccurrence(:, 1)) == trialNumber & ...
            IEDoccurrence(:, 3) >= 1;

        sampleIndices = double(IEDoccurrence(validIEDRows, 3));
        IEDtimes = sampleIndices ./ samplingFrequencyHz;

        IEDtimes = IEDtimes( ...
            isfinite(IEDtimes) & ...
            IEDtimes > 0 & ...
            IEDtimes < durationSeconds);

        % Keep every IED occurrence. Duplicate times are retained.
        IEDtimes = sort(IEDtimes);
    end

    if isempty(IEDtimes)
        breakTimes = [0; durationSeconds];
    else
        windowEndTimes = min( ...
            IEDtimes + postIEDWindowSeconds, durationSeconds);

        breakTimes = unique([ ...
            0; ...
            IEDtimes(:); ...
            windowEndTimes(:); ...
            durationSeconds], ...
            'sorted');
    end

    breakTimes = breakTimes( ...
        isfinite(breakTimes) & ...
        breakTimes >= 0 & ...
        breakTimes <= durationSeconds);

    breakTimes = unique(breakTimes, 'sorted');

    if length(breakTimes) < 2
        breakTimes = [0; durationSeconds];
    end

    tStart = breakTimes(1:end-1);
    tStop = breakTimes(2:end);

    validIntervals = tStop > tStart;
    tStart = tStart(validIntervals);
    tStop = tStop(validIntervals);

    intervalMidpoint = (tStart + tStop) ./ 2;

    postIED = zeros(length(tStart), 1);
    activeIEDWindowCount = zeros(length(tStart), 1);
    timeSinceMostRecentIED = NaN(length(tStart), 1);

    for kk = 1:length(tStart)

        if isempty(IEDtimes)
            continue;
        end

        activeWindows = ...
            intervalMidpoint(kk) >= IEDtimes & ...
            intervalMidpoint(kk) <= ...
                (IEDtimes + postIEDWindowSeconds);

        activeIEDWindowCount(kk) = sum(activeWindows);
        postIED(kk) = double(any(activeWindows));

        priorIEDtimes = IEDtimes(IEDtimes < intervalMidpoint(kk));

        if ~isempty(priorIEDtimes)
            timeSinceMostRecentIED(kk) = ...
                intervalMidpoint(kk) - max(priorIEDtimes);
        end

    end

    censored = true(length(tStart), 1);
    eventAtStop = false(length(tStart), 1);

    if finalEventObserved
        censored(end) = false;
        eventAtStop(end) = true;
    end

    trialRows = table( ...
        repmat(patientID, length(tStart), 1), ...
        repmat(trialNumber, length(tStart), 1), ...
        tStart, ...
        tStop, ...
        censored, ...
        eventAtStop, ...
        postIED, ...
        activeIEDWindowCount, ...
        timeSinceMostRecentIED, ...
        repmat(balloonColorCode, length(tStart), 1), ...
        repmat(samplingFrequencyHz, length(tStart), 1), ...
        repmat(alphaPlus, length(tStart), 1), ...
        repmat(alphaMinus, length(tStart), 1), ...
        repmat(nivAsymmetryRaw, length(tStart), 1), ...
        repmat(nivAsymmetryZ, length(tStart), 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'tStart', ...
            'tStop', ...
            'censored', ...
            'eventAtStop', ...
            'postIED', ...
            'activeIEDWindowCount', ...
            'timeSinceMostRecentIED_seconds', ...
            'balloonColorCode', ...
            'samplingFrequencyHz', ...
            'alphaPlus', ...
            'alphaMinus', ...
            'nivAsymmetryRaw', ...
            'nivAsymmetryZ'});

end

function nIEDs = countValidIEDsInTrial( ...
    IEDoccurrence, trialNumber, durationSeconds, samplingFrequencyHz)

    nIEDs = 0;

    if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 3
        return;
    end

    validRows = ...
        isfinite(IEDoccurrence(:, 1)) & ...
        isfinite(IEDoccurrence(:, 3)) & ...
        round(IEDoccurrence(:, 1)) == trialNumber & ...
        IEDoccurrence(:, 3) >= 1;

    sampleIndices = double(IEDoccurrence(validRows, 3));
    IEDtimes = sampleIndices ./ samplingFrequencyHz;

    nIEDs = sum( ...
        isfinite(IEDtimes) & ...
        IEDtimes > 0 & ...
        IEDtimes < durationSeconds);

end

function countingProcessData = emptyCountingProcessTable()

    countingProcessData = table( ...
        strings(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        false(0, 1), ...
        false(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'tStart', ...
            'tStop', ...
            'censored', ...
            'eventAtStop', ...
            'postIED', ...
            'activeIEDWindowCount', ...
            'timeSinceMostRecentIED_seconds', ...
            'balloonColorCode', ...
            'samplingFrequencyHz', ...
            'alphaPlus', ...
            'alphaMinus', ...
            'nivAsymmetryRaw', ...
            'nivAsymmetryZ'});

end

function trialSummary = emptyTrialSummaryTable()

    trialSummary = table( ...
        strings(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'durationSeconds', ...
            'eventObserved', ...
            'eventInPostIEDWindow', ...
            'nIEDsInFullDuration', ...
            'postIEDExposureSeconds', ...
            'balloonColorCode', ...
            'samplingFrequencyHz', ...
            'alphaPlus', ...
            'alphaMinus', ...
            'nivAsymmetryRaw', ...
            'nivAsymmetryZ'});

end

function [nivTable, nivSummary] = ...
    readNivParameterTable(nivParameterFile)

    if ~exist(nivParameterFile, 'file')
        error('Niv parameter CSV was not found: %s', nivParameterFile);
    end

    % Read all columns as text so participant IDs containing suffixes such
    % as 202006u or 201902r are not converted to missing numeric values.
    fileID = fopen(nivParameterFile, 'r');

    if fileID == -1
        error('Could not open Niv parameter file: %s', nivParameterFile);
    end

    fileCleanup = onCleanup(@() fclose(fileID));
    headerLine = fgetl(fileID);

    if ~ischar(headerLine) || isempty(strtrim(headerLine))
        error('The Niv parameter file has no readable header row.');
    end

    % Support comma-, tab-, and semicolon-delimited files.
    if contains(headerLine, sprintf('	'))
        delimiter = sprintf('	');
    elseif contains(headerLine, ',')
        delimiter = ',';
    elseif contains(headerLine, ';')
        delimiter = ';';
    else
        error([ ...
            'Could not identify the delimiter in alpha_comparison.csv. ' ...
            'Expected commas, tabs, or semicolons.']);
    end

    headerCells = strsplit(headerLine, delimiter);
    headerNames = string(headerCells(:));

    normalizedHeaderNames = lower(strip(headerNames));
    normalizedHeaderNames = erase(normalizedHeaderNames, '"');
    normalizedHeaderNames = regexprep( ...
        normalizedHeaderNames, '[^a-z0-9]', '');

    idColumn = find(normalizedHeaderNames == "ptid", 1);
    alphaPlusColumn = find( ...
        normalizedHeaderNames == "fitalphaplus", 1);
    alphaMinusColumn = find( ...
        normalizedHeaderNames == "fitalphaminus", 1);

    if isempty(idColumn) || isempty(alphaPlusColumn) || ...
            isempty(alphaMinusColumn)
        error([ ...
            'alpha_comparison.csv must contain columns named: ' ...
            'ptID, fit_alpha_plus, and fit_alpha_minus.']);
    end

    numberOfColumns = length(headerCells);
    formatSpecification = repmat('%q', 1, numberOfColumns);

    rawColumns = textscan( ...
        fileID, ...
        formatSpecification, ...
        'Delimiter', delimiter, ...
        'ReturnOnError', false);

    clear fileCleanup;

    if isempty(rawColumns) || length(rawColumns) < numberOfColumns
        error('No readable data rows were found in: %s', nivParameterFile);
    end

    patientID = string(rawColumns{idColumn});
    alphaPlus = str2double(string(rawColumns{alphaPlusColumn}));
    alphaMinus = str2double(string(rawColumns{alphaMinusColumn}));

    patientID = patientID(:);
    alphaPlus = alphaPlus(:);
    alphaMinus = alphaMinus(:);

    patientID = strip(patientID);
    patientID = erase(patientID, '"');
    patientID = erase(patientID, char(39));

    denominator = alphaMinus + alphaPlus;
    nivAsymmetryRaw = NaN(size(denominator));

    validRows = ...
        ~ismissing(patientID) & ...
        strlength(strip(patientID)) > 0 & ...
        isfinite(alphaPlus) & ...
        isfinite(alphaMinus) & ...
        denominator > 0;

    nivAsymmetryRaw(validRows) = ...
        (alphaMinus(validRows) - alphaPlus(validRows)) ./ ...
        denominator(validRows);

    validRows = validRows & isfinite(nivAsymmetryRaw);

    patientID = strip(patientID(validRows));
    alphaPlus = alphaPlus(validRows);
    alphaMinus = alphaMinus(validRows);
    nivAsymmetryRaw = nivAsymmetryRaw(validRows);

    normalizedPatientID = normalizeParticipantID(patientID);

    nonemptyIDRows = strlength(normalizedPatientID) > 0;

    patientID = patientID(nonemptyIDRows);
    normalizedPatientID = normalizedPatientID(nonemptyIDRows);
    alphaPlus = alphaPlus(nonemptyIDRows);
    alphaMinus = alphaMinus(nonemptyIDRows);
    nivAsymmetryRaw = nivAsymmetryRaw(nonemptyIDRows);

    [~, uniqueRowIndices] = unique( ...
        normalizedPatientID, 'stable');

    if length(uniqueRowIndices) < length(normalizedPatientID)
        warning([ ...
            'Duplicate participant IDs were found in the Niv CSV. ' ...
            'Only the first row for each participant will be used.']);
    end

    patientID = patientID(uniqueRowIndices);
    normalizedPatientID = normalizedPatientID(uniqueRowIndices);
    alphaPlus = alphaPlus(uniqueRowIndices);
    alphaMinus = alphaMinus(uniqueRowIndices);
    nivAsymmetryRaw = nivAsymmetryRaw(uniqueRowIndices);

    nivMean = mean(nivAsymmetryRaw, 'omitnan');
    nivSD = std(nivAsymmetryRaw, 0, 'omitnan');

    if ~isfinite(nivSD) || nivSD <= eps
        error('Niv asymmetry has zero or invalid variance.');
    end

    nivAsymmetryZ = (nivAsymmetryRaw - nivMean) ./ nivSD;

    nivTable = table( ...
        patientID, ...
        normalizedPatientID, ...
        alphaPlus, ...
        alphaMinus, ...
        nivAsymmetryRaw, ...
        nivAsymmetryZ, ...
        'VariableNames', { ...
            'patientID', ...
            'normalizedPatientID', ...
            'alphaPlus', ...
            'alphaMinus', ...
            'nivAsymmetryRaw', ...
            'nivAsymmetryZ'});

    nivSummary = struct();
    nivSummary.mean = nivMean;
    nivSummary.sd = nivSD;
    nivSummary.nParticipants = height(nivTable);

    % Show suffix-bearing IDs immediately so their import can be verified.
    alphanumericRows = ~cellfun( ...
        @isempty, regexp(cellstr(patientID), '[a-zA-Z]', 'once'));

    if any(alphanumericRows)
        fprintf('\nAlphanumeric participant IDs preserved from Niv file:\n');
        disp(nivTable(alphanumericRows, { ...
            'patientID', ...
            'alphaPlus', ...
            'alphaMinus', ...
            'nivAsymmetryRaw'}));
    end

end

function values = convertTableColumnToDouble(rawValues)

    if isnumeric(rawValues) || islogical(rawValues)
        values = double(rawValues);
        return;
    end

    if isstring(rawValues)
        values = str2double(rawValues);
        return;
    end

    if ischar(rawValues)
        values = str2double(string(cellstr(rawValues)));
        return;
    end

    if iscell(rawValues)
        values = NaN(numel(rawValues), 1);

        for ii = 1:numel(rawValues)
            thisValue = rawValues{ii};

            if isnumeric(thisValue) && isscalar(thisValue)
                values(ii) = double(thisValue);
            else
                values(ii) = str2double(string(thisValue));
            end
        end

        return;
    end

    values = str2double(string(rawValues));

end

function [found, alphaPlus, alphaMinus, ...
    nivAsymmetryRaw, nivAsymmetryZ] = ...
    getNivParametersForPatient(nivTable, patientID)

    normalizedPatientID = normalizeParticipantID(patientID);

    matchingRows = ...
        nivTable.normalizedPatientID == normalizedPatientID;

    found = any(matchingRows);
    alphaPlus = NaN;
    alphaMinus = NaN;
    nivAsymmetryRaw = NaN;
    nivAsymmetryZ = NaN;

    if ~found
        return;
    end

    rowNumber = find(matchingRows, 1, 'first');

    alphaPlus = nivTable.alphaPlus(rowNumber);
    alphaMinus = nivTable.alphaMinus(rowNumber);
    nivAsymmetryRaw = nivTable.nivAsymmetryRaw(rowNumber);
    nivAsymmetryZ = nivTable.nivAsymmetryZ(rowNumber);

end

function normalizedID = normalizeParticipantID(patientID)

    normalizedID = lower(strip(string(patientID)));
    normalizedID = regexprep(normalizedID, '[^a-z0-9]', '');

end

function samplingFrequencyHz = getSamplingFrequency( ...
    LFPIED, defaultSamplingFrequencyHz)

    if isfield(LFPIED, 'Fs') && ...
            isscalar(LFPIED.Fs) && ...
            isfinite(LFPIED.Fs) && ...
            LFPIED.Fs > 0
        samplingFrequencyHz = double(LFPIED.Fs);
    else
        samplingFrequencyHz = defaultSamplingFrequencyHz;
    end

end

function balloonColorCode = mapBalloonColorCode(balloonType)

    balloonType = double(balloonType(:));
    balloonColorCode = NaN(size(balloonType));

    validRows = ...
        isfinite(balloonType) & ...
        ismember(round(balloonType), [1 2 3 11 12 13]);

    balloonColorCode(validRows) = ...
        mod(round(balloonType(validRows)) - 1, 10) + 1;

end

function [robustCovariance, robustSE, robustZ, robustP] = ...
    computeClusterRobustInference(stats, beta, clusterID)

    beta = beta(:);
    nPredictors = length(beta);

    clusterID = clusterID(:);
    uniqueClusters = unique(clusterID(isfinite(clusterID)));
    nClusters = length(uniqueClusters);

    canUseClusterScores = ...
        isfield(stats, 'scores') && ...
        size(stats.scores, 1) == length(clusterID) && ...
        size(stats.scores, 2) == nPredictors;

    if nClusters < 2 || ~canUseClusterScores
        robustCovariance = stats.covb;
        robustSE = stats.se(:);
        robustZ = stats.z(:);
        robustP = stats.p(:);
        return;
    end

    clusterScoreSums = zeros(nClusters, nPredictors);

    for gg = 1:nClusters
        rows = clusterID == uniqueClusters(gg);
        thisClusterScores = stats.scores(rows, :);
        thisClusterScores(~isfinite(thisClusterScores)) = 0;
        clusterScoreSums(gg, :) = sum(thisClusterScores, 1);
    end

    meat = clusterScoreSums' * clusterScoreSums;
    bread = stats.covb;

    robustCovariance = bread * meat * bread;
    robustCovariance = ...
        (nClusters / (nClusters - 1)) .* robustCovariance;

    robustCovariance = ...
        (robustCovariance + robustCovariance') ./ 2;

    robustSE = sqrt(max(diag(robustCovariance), 0));

    invalidSERows = robustSE <= 0 | ~isfinite(robustSE);
    robustSE(invalidSERows) = stats.se(invalidSERows);

    robustZ = beta ./ robustSE;
    robustP = 2 .* normcdf(-abs(robustZ), 0, 1);

end

function interpretation = ...
    getIEDMainEffectInterpretation(analysisType)

    switch analysisType
        case "IT"
            interpretation = ...
                "IED effect at mean Niv; HR > 1 means higher action hazard and shorter inflation time.";
        case "RT"
            interpretation = ...
                "IED effect at mean Niv; HR > 1 means higher response hazard and shorter response time.";
        case "BR"
            interpretation = ...
                "IED effect at mean Niv; HR > 1 means higher banking hazard.";
        otherwise
            interpretation = "IED effect at mean Niv asymmetry.";
    end

end

function output = capitalizeFirst(input)

    input = string(input);

    if strlength(input) == 0
        output = input;
        return;
    end

    firstCharacter = upper(extractBetween(input, 1, 1));
    remainingCharacters = extractAfter(input, 1);
    output = firstCharacter + remainingCharacters;

end

function axisLimits = calculatePositiveLogLimits( ...
    lowerValues, upperValues)

    lowerValues = lowerValues(:);
    upperValues = upperValues(:);

    positiveLower = lowerValues( ...
        isfinite(lowerValues) & lowerValues > 0);

    positiveUpper = upperValues( ...
        isfinite(upperValues) & upperValues > 0);

    if isempty(positiveLower) || isempty(positiveUpper)
        axisLimits = [0.5 2];
        return;
    end

    minimumValue = min([positiveLower; positiveUpper; 1]);
    maximumValue = max([positiveLower; positiveUpper; 1]);

    logMinimum = log10(minimumValue);
    logMaximum = log10(maximumValue);

    if logMaximum == logMinimum
        logMinimum = logMinimum - 0.2;
        logMaximum = logMaximum + 0.2;
    else
        padding = 0.10 .* (logMaximum - logMinimum);
        logMinimum = logMinimum - padding;
        logMaximum = logMaximum + padding;
    end

    axisLimits = [10^logMinimum, 10^logMaximum];

end
