function IED7_Cox_IT_RT_BR_postIED_by_brain_area_IEDtime_permutation


%
% Author: Nill

clear;
clc;
close all;

%% Paths
% this was done on veronica's computer
inputFolderName_LFPIED = ...
    'D:\Nill\data\0_0_new_IED_new_area_labels\IED1_find_number_of_IEDs\';

outputFolderName = ...
    'D:\Nill\code\BART\0_0_new_IED_new_area_labels\IED7_Cox_IT_RT_BR_postIED_by_brain_area\';

if ~exist(outputFolderName, 'dir')
    mkdir(outputFolderName);
end

%% Shared settings

% Outcome-specific post-IED windows: 1000 ms for all outcomes.
settings.postIEDWindowMillisecondsRT = 500;
settings.postIEDWindowMillisecondsIT = 1000;
settings.postIEDWindowMillisecondsBR = 1000;

% FDR family: IT, RT, BR (bank), and PR (pop), within each area.
settings.fdrAlphaAcrossOutcomes = 0.05;

settings.maximumRTSeconds = 20;
settings.defaultSamplingFrequencyHz = 1000;
settings.combineLeftAndRight = true;
settings.includeUnknownArea = false;

% Sparse-area safeguards
settings.minimumParticipantsWithCoverage = 10;
settings.minimumParticipantsWithIED = 1;
settings.minimumIEDsInArea = 1;
settings.minimumEndpointEventsInsideWindow = 1;
settings.minimumEndpointEventsOutsideWindow = 1;

% Within-trial IED-time permutation settings
settings.numberOfPermutations = 1000;
settings.minimumValidPermutations = 800;
settings.permutationRandomSeed = 1;
rng(settings.permutationRandomSeed, 'twister');

% Figure colors
colorRT = [0.204  0.459  0.702];   % blue
colorIT = [0.847  0.333  0.153];   % orange
colorBR = [0.250  0.600  0.250];   % green
colorPop = [0.494  0.184  0.556];  % purple
markerAlpha = 0.5;

%% Run IT, RT, and BR analyses

[ITResults, ~] = runBrainAreaAnalysis( ...
    inputFolderName_LFPIED, "IT", settings);

[RTResults, ~] = runBrainAreaAnalysis( ...
    inputFolderName_LFPIED, "RT", settings);

[BRResults, ~] = runBrainAreaAnalysis( ...
    inputFolderName_LFPIED, "BR", settings);

%% BH-FDR correction across IT, RT, BR, and PR within each area

[ITResults, RTResults, BRResults] = ...
    applyFDRWithinAreaAcrossOutcomes( ...
        ITResults, RTResults, BRResults, ...
        settings.fdrAlphaAcrossOutcomes);

saveCorrectedAreaCSV(outputFolderName, "IT", ITResults);
saveCorrectedAreaCSV(outputFolderName, "RT", RTResults);
saveCorrectedAreaCSV(outputFolderName, "BR", BRResults);

%% Save IT, RT, and BR forest-plot PDFs

itFigureOutputFile = fullfile(outputFolderName, ...
    'IT_brain_area_cox_forest_plot.pdf');

rtFigureOutputFile = fullfile(outputFolderName, ...
    'RT_brain_area_cox_forest_plot.pdf');

brFigureOutputFile = fullfile(outputFolderName, ...
    'BR_bank_pop_brain_area_cox_forest_plot.pdf');

plotSeparateAreaForestPlots( ...
    ITResults, RTResults, BRResults, ...
    colorIT, colorRT, colorBR, colorPop, markerAlpha, ...
    settings, ...
    itFigureOutputFile, ...
    rtFigureOutputFile, ...
    brFigureOutputFile);

fprintf('\n============================================================\n');
fprintf('All three analyses finished.\n');
fprintf('Post-IED windows: IT = %d ms, RT = %d ms, BR = %d ms.\n', ...
    settings.postIEDWindowMillisecondsIT, ...
    settings.postIEDWindowMillisecondsRT, ...
    settings.postIEDWindowMillisecondsBR);
fprintf('Permutation test: %d within-trial circular IED shifts.\n', ...
    settings.numberOfPermutations);
fprintf('Saved the three corrected CSV files and three forest-plot PDFs.\n');

end

%% Local functions

function [areaResults, areaModels] = runBrainAreaAnalysis( ...
    inputFolderName_LFPIED, analysisType, settings)

    analysisPrefix = analysisType;

    % Select the post-IED window for the current behavioral outcome.
    switch analysisType
        case "RT"
            postIEDWindowMilliseconds = ...
                settings.postIEDWindowMillisecondsRT;
        case "IT"
            postIEDWindowMilliseconds = ...
                settings.postIEDWindowMillisecondsIT;
        case "BR"
            postIEDWindowMilliseconds = ...
                settings.postIEDWindowMillisecondsBR;
        otherwise
            error('Unknown analysis type: %s', analysisType);
    end

    postIEDWindowSeconds = postIEDWindowMilliseconds / 1000;

    maximumRTSeconds = settings.maximumRTSeconds;
    defaultSamplingFrequencyHz = settings.defaultSamplingFrequencyHz;
    combineLeftAndRight = settings.combineLeftAndRight;
    includeUnknownArea = settings.includeUnknownArea;
    minimumParticipantsWithCoverage = ...
        settings.minimumParticipantsWithCoverage;
    minimumParticipantsWithIED = settings.minimumParticipantsWithIED;
    minimumIEDsInArea = settings.minimumIEDsInArea;
    minimumEndpointEventsInsideWindow = ...
        settings.minimumEndpointEventsInsideWindow;
    minimumEndpointEventsOutsideWindow = ...
        settings.minimumEndpointEventsOutsideWindow;

    fileList = dir(fullfile(inputFolderName_LFPIED, '*.LFPIED.mat'));

    if isempty(fileList)
        error('No .LFPIED.mat files were found.');
    end

    participants = struct( ...
        'patientID', {}, ...
        'RTs', {}, ...
        'ITs', {}, ...
        'BankedTrials', {}, ...
        'isControl', {}, ...
        'balloonColorCode', {}, ...
        'validTrials', {}, ...
        'durationSeconds', {}, ...
        'finalEventObserved', {}, ...
        'IEDoccurrence', {}, ...
        'samplingFrequencyHz', {}, ...
        'selectedAreaLabels', {});

    allAreas = strings(0, 1);

    %% Load and organize participant data

    for pt = 1:length(fileList)

        fileName = fileList(pt).name;
        fileNameParts = strsplit(fileName, '.');
        patientID = string(fileNameParts{1});

        fprintf('\nLoading patient for %s: %s\n', ...
            analysisPrefix, patientID);

        loadedData = load(fullfile(inputFolderName_LFPIED, fileName));

        if ~isfield(loadedData, 'LFPIED')
            fprintf('Skipped: LFPIED structure was not found.\n');
            continue;
        end

        LFPIED = loadedData.LFPIED;

        switch analysisType
            case "IT"
                requiredFields = { ...
                    'selectedChans', 'anatomicalLocs', 'RTs', 'ITs', ...
                    'isControl', 'balloonType', 'IED_occurance_IT'};
            case "RT"
                requiredFields = { ...
                    'selectedChans', 'anatomicalLocs', 'RTs', ...
                    'isControl', 'balloonType', 'IED_occurance_RT'};
            case "BR"
                requiredFields = { ...
                    'selectedChans', 'anatomicalLocs', 'RTs', 'ITs', ...
                    'BankedTrials', 'isControl', 'balloonType', ...
                    'IED_occurance_IT'};
            otherwise
                error('Unknown analysis type: %s', analysisType);
        end

        missingField = false;

        for ff = 1:length(requiredFields)
            if ~isfield(LFPIED, requiredFields{ff})
                fprintf('Skipped: missing field %s.\n', ...
                    requiredFields{ff});
                missingField = true;
            end
        end

        if missingField
            continue;
        end

        selectedChans = round(LFPIED.selectedChans(:));
        nSelectedChannels = length(selectedChans);

        if nSelectedChannels == 0
            fprintf('Skipped: no selected channels.\n');
            continue;
        end

        selectedAreaLabels = getSelectedChannelLabels( ...
            LFPIED.anatomicalLocs, selectedChans, nSelectedChannels);

        selectedAreaLabels = cleanAreaLabels( ...
            selectedAreaLabels, combineLeftAndRight);

        % Exclude all NaC/nucleus accumbens, white-matter, and lateral-ventricle channels.
        excludedAreaRows = isExcludedAreaLabel(selectedAreaLabels);
        selectedAreaLabels(excludedAreaRows) = "Excluded";

        RTs = double(LFPIED.RTs(:));
        isControl = double(LFPIED.isControl(:));
        balloonType = double(LFPIED.balloonType(:));

        switch analysisType
            case "RT"
                ITs = NaN(size(RTs));
                BankedTrials = NaN(size(RTs));
                vectorLengths = [ ...
                    length(RTs), length(isControl), length(balloonType)];
            case "IT"
                ITs = double(LFPIED.ITs(:));
                BankedTrials = NaN(size(RTs));
                vectorLengths = [ ...
                    length(RTs), length(ITs), ...
                    length(isControl), length(balloonType)];
            case "BR"
                ITs = double(LFPIED.ITs(:));
                BankedTrials = double(LFPIED.BankedTrials(:));
                vectorLengths = [ ...
                    length(RTs), length(ITs), length(BankedTrials), ...
                    length(isControl), length(balloonType)];
        end

        if isfield(LFPIED, 'nTrials') && ...
                isscalar(LFPIED.nTrials) && isfinite(LFPIED.nTrials)
            vectorLengths(end + 1) = LFPIED.nTrials;
        end

        nTrials = floor(min(vectorLengths));

        RTs = RTs(1:nTrials);
        isControl = isControl(1:nTrials);
        balloonType = balloonType(1:nTrials);
        balloonColorCode = mapBalloonColorCode(balloonType);
        ITs = ITs(1:nTrials);
        BankedTrials = BankedTrials(1:nTrials);

        switch analysisType
            case "RT"
                durationSeconds = RTs;
                finalEventObserved = true(nTrials, 1);
                IEDoccurrence = LFPIED.IED_occurance_RT;
            case "IT"
                durationSeconds = ITs;
                finalEventObserved = true(nTrials, 1);
                IEDoccurrence = LFPIED.IED_occurance_IT;
            case "BR"
                durationSeconds = ITs;
                finalEventObserved = BankedTrials == 1;
                IEDoccurrence = LFPIED.IED_occurance_IT;
        end

        validTrials = ...
            isControl == 0 & ...
            isfinite(RTs) & ...
            RTs > 0 & ...
            RTs <= maximumRTSeconds & ...
            isfinite(durationSeconds) & ...
            durationSeconds > 0 & ...
            isfinite(balloonColorCode) & ...
            ismember(balloonColorCode, [1 2 3]);

        if analysisType == "BR"
            validTrials = validTrials & ...
                isfinite(BankedTrials) & ...
                ismember(BankedTrials, [0 1]);
        end

        samplingFrequencyHz = getSamplingFrequency( ...
            LFPIED, defaultSamplingFrequencyHz);

        newParticipant.patientID = patientID;
        newParticipant.RTs = RTs;
        newParticipant.ITs = ITs;
        newParticipant.BankedTrials = BankedTrials;
        newParticipant.isControl = isControl;
        newParticipant.balloonColorCode = balloonColorCode;
        newParticipant.validTrials = validTrials;
        newParticipant.durationSeconds = durationSeconds;
        newParticipant.finalEventObserved = finalEventObserved;
        newParticipant.IEDoccurrence = IEDoccurrence;
        newParticipant.samplingFrequencyHz = samplingFrequencyHz;
        newParticipant.selectedAreaLabels = selectedAreaLabels;

        participants(end + 1) = newParticipant; 

        participantAreas = unique(selectedAreaLabels, 'stable');

        if ~includeUnknownArea
            participantAreas = participantAreas( ...
                participantAreas ~= "Unknown");
        end

        participantAreas = participantAreas( ...
            participantAreas ~= "Excluded");

        allAreas = unique([allAreas; participantAreas], 'stable');

    end

    if isempty(participants)
        error('No valid participant data were loaded for %s.', ...
            analysisPrefix);
    end

    % Hard safety filter before any model is fitted.
    allAreas = allAreas(~isExcludedAreaLabel(allAreas));

    if isempty(allAreas)
        error(['No anatomical areas were found after excluding NaC, ' ...
            'white matter, and lateral ventricle.']);
    end

    fprintf('\n============================================================\n');
    fprintf('%s area-specific %d-ms post-IED Cox analysis\n', ...
        analysisPrefix, postIEDWindowMilliseconds);
    fprintf('============================================================\n');
    fprintf('Loaded participants: %d\n', length(participants));
    fprintf('Anatomical areas: %d\n', length(allAreas));

    %% Fit one Cox model per anatomical area

    areaResults = initializeAreaResultsTable();
    areaModels = struct();

    for aa = 1:length(allAreas)

        anatomicalArea = allAreas(aa);

        fprintf('\n------------------------------------------------------------\n');
        fprintf('Area %d/%d: %s\n', ...
            aa, length(allAreas), anatomicalArea);

        countingProcessData = emptyCountingProcessTable();

        nParticipantsWithCoverage = 0;
        nParticipantsWithIED = 0;
        nIEDsInArea = 0;
        nValidTrials = 0;

        for pt = 1:length(participants)

            P = participants(pt);
            areaLocalChannels = find( ...
                P.selectedAreaLabels == anatomicalArea);

            if isempty(areaLocalChannels)
                continue;
            end

            nParticipantsWithCoverage = ...
                nParticipantsWithCoverage + 1;

            areaIEDoccurrence = filterIEDsToArea( ...
                P.IEDoccurrence, areaLocalChannels);

            validAreaIEDRows = getValidAreaIEDRows( ...
                areaIEDoccurrence, P.validTrials);

            thisParticipantIEDCount = sum(validAreaIEDRows);
            nIEDsInArea = nIEDsInArea + thisParticipantIEDCount;

            if thisParticipantIEDCount > 0
                nParticipantsWithIED = nParticipantsWithIED + 1;
            end

            validTrialNumbers = find(P.validTrials);
            nValidTrials = nValidTrials + length(validTrialNumbers);

            for tt = 1:length(validTrialNumbers)

                trialNumber = validTrialNumbers(tt);

                if analysisType == "BR"

                    % The same trial is represented in two transition
                    % strata inside one Cox fit. A banked trial is an
                    % observed bank event and a censored pop event. A
                    % popped trial is the reverse.
                    bankObserved = P.BankedTrials(trialNumber) == 1;
                    popObserved = P.BankedTrials(trialNumber) == 0;

                    bankRows = makePostIEDWindowRows( ...
                        P.patientID, ...
                        trialNumber, ...
                        P.durationSeconds(trialNumber), ...
                        areaIEDoccurrence, ...
                        P.samplingFrequencyHz, ...
                        P.balloonColorCode(trialNumber), ...
                        bankObserved, ...
                        postIEDWindowSeconds, ...
                        "bank");

                    popRows = makePostIEDWindowRows( ...
                        P.patientID, ...
                        trialNumber, ...
                        P.durationSeconds(trialNumber), ...
                        areaIEDoccurrence, ...
                        P.samplingFrequencyHz, ...
                        P.balloonColorCode(trialNumber), ...
                        popObserved, ...
                        postIEDWindowSeconds, ...
                        "pop");

                    trialRows = [bankRows; popRows];

                else

                    trialRows = makePostIEDWindowRows( ...
                        P.patientID, ...
                        trialNumber, ...
                        P.durationSeconds(trialNumber), ...
                        areaIEDoccurrence, ...
                        P.samplingFrequencyHz, ...
                        P.balloonColorCode(trialNumber), ...
                        P.finalEventObserved(trialNumber), ...
                        postIEDWindowSeconds, ...
                        "single");

                end

                countingProcessData = ...
                    [countingProcessData; trialRows]; 

            end

        end

        status = "fitted";

        if nParticipantsWithCoverage < minimumParticipantsWithCoverage
            status = "skipped: insufficient participants with coverage";
        elseif nParticipantsWithIED < minimumParticipantsWithIED
            status = "skipped: no participants with area IEDs";
        elseif nIEDsInArea < minimumIEDsInArea
            status = "skipped: insufficient area IEDs";
        elseif isempty(countingProcessData)
            status = "skipped: no counting-process rows";
        end

        nCountingRows = height(countingProcessData);
        nEndpointEvents = 0;
        nEventsInsideWindow = 0;
        nEventsOutsideWindow = 0;
        timeInsideWindowSeconds = 0;
        timeOutsideWindowSeconds = 0;
        nBankEvents = 0;
        nPopEvents = 0;
        nBankEventsOutsideWindow = 0;
        nBankEventsInsideWindow = 0;
        nPopEventsOutsideWindow = 0;
        nPopEventsInsideWindow = 0;

        betaPrimary = NaN;
        robustSEPrimary = NaN;
        robustZPrimary = NaN;
        pValuePrimary = NaN;
        permutationPValuePrimary = NaN;
        nValidPermutationsPrimary = 0;
        betaCILow = NaN;
        betaCIHigh = NaN;
        hazardRatio = NaN;
        hazardRatioCILow = NaN;
        hazardRatioCIHigh = NaN;

        betaPop = NaN;
        robustSEPop = NaN;
        robustZPop = NaN;
        pValuePop = NaN;
        permutationPValuePop = NaN;
        nValidPermutationsPop = 0;
        betaPopCILow = NaN;
        betaPopCIHigh = NaN;
        hazardRatioPop = NaN;
        hazardRatioPopCILow = NaN;
        hazardRatioPopCIHigh = NaN;

        betaBankMinusPop = NaN;
        robustSEBankMinusPop = NaN;
        robustZBankMinusPop = NaN;
        pValueBankVsPop = NaN;
        permutationPValueBankVsPop = NaN;
        nValidPermutationsBankVsPop = 0;
        betaBankMinusPopCILow = NaN;
        betaBankMinusPopCIHigh = NaN;

        logLikelihood = NaN;
        nModelParticipants = 0;
        referenceBalloonColor = "";

        if status == "fitted"

            [countingProcessData.patientStratum, patientLevels] = ...
                findgroups(countingProcessData.patientID);

            if analysisType == "BR"
                % Separate baseline hazards for every participant and for
                % each transition, while keeping one combined model.
                strata = findgroups( ...
                    countingProcessData.patientID, ...
                    countingProcessData.transitionType);
            else
                strata = countingProcessData.patientStratum;
            end

            [X, predictorNames, referenceBalloonColor] = ...
                buildPredictorMatrix(countingProcessData, analysisType);

            T = [countingProcessData.tStart, ...
                countingProcessData.tStop];
            censoring = logical(countingProcessData.censored);

            validRows = ...
                all(isfinite(X), 2) & ...
                all(isfinite(T), 2) & ...
                T(:, 1) >= 0 & ...
                T(:, 2) > T(:, 1) & ...
                isfinite(strata);

            X = X(validRows, :);
            T = T(validRows, :);
            censoring = censoring(validRows);
            strata = strata(validRows);
            countingProcessData = countingProcessData(validRows, :);

            nCountingRows = height(countingProcessData);
            nModelParticipants = ...
                length(unique(countingProcessData.patientID));
            nEndpointEvents = sum( ...
                countingProcessData.eventAtStop == 1);

            nEventsOutsideWindow = sum( ...
                countingProcessData.eventAtStop == 1 & ...
                countingProcessData.postIED == 0);

            nEventsInsideWindow = sum( ...
                countingProcessData.eventAtStop == 1 & ...
                countingProcessData.postIED == 1);

            if analysisType == "BR"
                bankTransition = ...
                    countingProcessData.transitionType == "bank";
                popTransition = ...
                    countingProcessData.transitionType == "pop";

                nBankEvents = sum( ...
                    countingProcessData.eventAtStop == 1 & ...
                    bankTransition);
                nPopEvents = sum( ...
                    countingProcessData.eventAtStop == 1 & ...
                    popTransition);

                nBankEventsOutsideWindow = sum( ...
                    countingProcessData.eventAtStop == 1 & ...
                    bankTransition & ...
                    countingProcessData.postIED == 0);
                nBankEventsInsideWindow = sum( ...
                    countingProcessData.eventAtStop == 1 & ...
                    bankTransition & ...
                    countingProcessData.postIED == 1);

                nPopEventsOutsideWindow = sum( ...
                    countingProcessData.eventAtStop == 1 & ...
                    popTransition & ...
                    countingProcessData.postIED == 0);
                nPopEventsInsideWindow = sum( ...
                    countingProcessData.eventAtStop == 1 & ...
                    popTransition & ...
                    countingProcessData.postIED == 1);
            end

            timeOutsideWindowSeconds = sum( ...
                (countingProcessData.tStop - ...
                 countingProcessData.tStart) .* ...
                (countingProcessData.postIED == 0), ...
                'omitnan');

            timeInsideWindowSeconds = sum( ...
                (countingProcessData.tStop - ...
                 countingProcessData.tStart) .* ...
                (countingProcessData.postIED == 1), ...
                'omitnan');

            if nModelParticipants < minimumParticipantsWithCoverage
                status = "skipped: insufficient model participants";
            elseif timeInsideWindowSeconds <= 0
                status = "skipped: no area-specific exposed time";
            elseif nEventsInsideWindow < ...
                    minimumEndpointEventsInsideWindow
                status = "skipped: no endpoint events inside area-specific windows";
            elseif nEventsOutsideWindow < ...
                    minimumEndpointEventsOutsideWindow
                status = "skipped: no endpoint events outside area-specific windows";
            elseif analysisType == "BR" && ...
                    nBankEventsInsideWindow < ...
                    minimumEndpointEventsInsideWindow
                status = "skipped: no bank events inside area-specific windows";
            elseif analysisType == "BR" && ...
                    nBankEventsOutsideWindow < ...
                    minimumEndpointEventsOutsideWindow
                status = "skipped: no bank events outside area-specific windows";
            elseif analysisType == "BR" && ...
                    nPopEventsInsideWindow < ...
                    minimumEndpointEventsInsideWindow
                status = "skipped: no pop events inside area-specific windows";
            elseif analysisType == "BR" && ...
                    nPopEventsOutsideWindow < ...
                    minimumEndpointEventsOutsideWindow
                status = "skipped: no pop events outside area-specific windows";
            elseif size(X, 1) <= size(X, 2)
                status = "skipped: insufficient rows for predictor matrix";
            end

        end

        if status == "fitted"

            try
                coxOptions = statset('coxphfit');
                coxOptions.Display = 'off';
                coxOptions.MaxIter = 1000;
                coxOptions.MaxFunEvals = 5000;

                [beta, logLikelihood, ...
                    baselineCumulativeHazard, stats] = coxphfit( ...
                        X, ...
                        T, ...
                        'Censoring', censoring, ...
                        'Strata', strata, ...
                        'Ties', 'efron', ...
                        'Baseline', 0, ...
                        'Options', coxOptions);

                [clusterRobustCovariance, clusterRobustSE, ...
                    clusterRobustZ, clusterRobustP] = ...
                    computeClusterRobustInference( ...
                        stats, beta, ...
                        countingProcessData.patientStratum);

                betaPrimary = beta(1);
                robustSEPrimary = clusterRobustSE(1);
                robustZPrimary = clusterRobustZ(1);
                pValuePrimary = clusterRobustP(1);

                betaCILow = betaPrimary - 1.96 * robustSEPrimary;
                betaCIHigh = betaPrimary + 1.96 * robustSEPrimary;

                hazardRatio = exp(betaPrimary);
                hazardRatioCILow = exp(betaCILow);
                hazardRatioCIHigh = exp(betaCIHigh);

                if analysisType == "BR"
                    % Predictor 1 is the IED effect on bank hazard.
                    % Predictor 2 is the IED effect on pop hazard.
                    betaPop = beta(2);
                    robustSEPop = clusterRobustSE(2);
                    robustZPop = clusterRobustZ(2);
                    pValuePop = clusterRobustP(2);

                    betaPopCILow = ...
                        betaPop - 1.96 * robustSEPop;
                    betaPopCIHigh = ...
                        betaPop + 1.96 * robustSEPop;

                    hazardRatioPop = exp(betaPop);
                    hazardRatioPopCILow = exp(betaPopCILow);
                    hazardRatioPopCIHigh = exp(betaPopCIHigh);

                    % Direct test of whether the bank and pop IED
                    % coefficients are different in this one model.
                    betaBankMinusPop = betaPrimary - betaPop;
                    varianceBankMinusPop = ...
                        clusterRobustCovariance(1, 1) + ...
                        clusterRobustCovariance(2, 2) - ...
                        2 * clusterRobustCovariance(1, 2);

                    robustSEBankMinusPop = sqrt( ...
                        max(varianceBankMinusPop, 0));

                    if robustSEBankMinusPop > 0 && ...
                            isfinite(robustSEBankMinusPop)
                        robustZBankMinusPop = ...
                            betaBankMinusPop / robustSEBankMinusPop;
                        pValueBankVsPop = 2 * normcdf( ...
                            -abs(robustZBankMinusPop), 0, 1);
                        betaBankMinusPopCILow = ...
                            betaBankMinusPop - ...
                            1.96 * robustSEBankMinusPop;
                        betaBankMinusPopCIHigh = ...
                            betaBankMinusPop + ...
                            1.96 * robustSEBankMinusPop;
                    end
                end

                safeAreaNameBase = ...
                    matlab.lang.makeValidName(char(anatomicalArea));
                safeAreaName = safeAreaNameBase;
                duplicateNumber = 1;

                while isfield(areaModels, safeAreaName)
                    duplicateNumber = duplicateNumber + 1;
                    safeAreaName = sprintf('%s_%d', ...
                        safeAreaNameBase, duplicateNumber);
                end

                areaModels.(safeAreaName) = struct( ...
                    'anatomicalArea', anatomicalArea, ...
                    'beta', beta, ...
                    'predictorNames', predictorNames, ...
                    'logLikelihood', logLikelihood, ...
                    'baselineCumulativeHazard', ...
                        baselineCumulativeHazard, ...
                    'stats', stats, ...
                    'clusterRobustCovariance', ...
                        clusterRobustCovariance, ...
                    'clusterRobustSE', clusterRobustSE, ...
                    'clusterRobustZ', clusterRobustZ, ...
                    'clusterRobustP', clusterRobustP, ...
                    'patientLevels', patientLevels, ...
                    'analysisType', analysisType, ...
                    'referenceBalloonColor', ...
                        referenceBalloonColor);

            catch modelError
                status = "failed: " + string(modelError.message);
            end

        end

        if status == "fitted"
            fprintf(['Running %d within-trial circular IED-time ' ...
                'permutations for %s...\n'], ...
                settings.numberOfPermutations, anatomicalArea);

            [permutationPValuePrimary, ...
             permutationPValuePop, ...
             permutationPValueBankVsPop, ...
             nValidPermutationsPrimary, ...
             nValidPermutationsPop, ...
             nValidPermutationsBankVsPop] = ...
                runAreaPermutationTest( ...
                    participants, anatomicalArea, analysisType, ...
                    postIEDWindowSeconds, settings, ...
                    robustZPrimary, robustZPop, ...
                    robustZBankMinusPop);
        end

        newRow = table( ...
            anatomicalArea, ...
            status, ...
            nParticipantsWithCoverage, ...
            nParticipantsWithIED, ...
            nModelParticipants, ...
            nValidTrials, ...
            nIEDsInArea, ...
            nCountingRows, ...
            nEndpointEvents, ...
            nEventsOutsideWindow, ...
            nEventsInsideWindow, ...
            timeOutsideWindowSeconds, ...
            timeInsideWindowSeconds, ...
            referenceBalloonColor, ...
            betaPrimary, ...
            robustSEPrimary, ...
            robustZPrimary, ...
            pValuePrimary, ...
            permutationPValuePrimary, ...
            nValidPermutationsPrimary, ...
            betaCILow, ...
            betaCIHigh, ...
            hazardRatio, ...
            hazardRatioCILow, ...
            hazardRatioCIHigh, ...
            false, ...
            nBankEvents, ...
            nPopEvents, ...
            nBankEventsOutsideWindow, ...
            nBankEventsInsideWindow, ...
            nPopEventsOutsideWindow, ...
            nPopEventsInsideWindow, ...
            betaPop, ...
            robustSEPop, ...
            robustZPop, ...
            pValuePop, ...
            permutationPValuePop, ...
            nValidPermutationsPop, ...
            betaPopCILow, ...
            betaPopCIHigh, ...
            hazardRatioPop, ...
            hazardRatioPopCILow, ...
            hazardRatioPopCIHigh, ...
            false, ...
            betaBankMinusPop, ...
            robustSEBankMinusPop, ...
            robustZBankMinusPop, ...
            pValueBankVsPop, ...
            permutationPValueBankVsPop, ...
            nValidPermutationsBankVsPop, ...
            betaBankMinusPopCILow, ...
            betaBankMinusPopCIHigh, ...
            false, ...
            'VariableNames', areaResults.Properties.VariableNames);

        areaResults = [areaResults; newRow]; 

        fprintf('Status: %s\n', status);
        fprintf('Coverage participants: %d\n', ...
            nParticipantsWithCoverage);
        fprintf('Participants with area IEDs: %d\n', ...
            nParticipantsWithIED);
        fprintf('Area IEDs: %d\n', nIEDsInArea);

        if status == "fitted"
            if analysisType == "BR"
                fprintf([ ...
                    'Bank: log(HR) = %.6f, HR = %.6f, ' ...
                    '95%% CI = [%.6f, %.6f], robust p = %.6g, ' ...
                    'permutation p = %.6g (%d valid)\n'], ...
                    betaPrimary, hazardRatio, hazardRatioCILow, ...
                    hazardRatioCIHigh, pValuePrimary, ...
                    permutationPValuePrimary, ...
                    nValidPermutationsPrimary);
                fprintf([ ...
                    'Pop:  log(HR) = %.6f, HR = %.6f, ' ...
                    '95%% CI = [%.6f, %.6f], robust p = %.6g, ' ...
                    'permutation p = %.6g (%d valid)\n'], ...
                    betaPop, hazardRatioPop, hazardRatioPopCILow, ...
                    hazardRatioPopCIHigh, pValuePop, ...
                    permutationPValuePop, nValidPermutationsPop);
                fprintf([ ...
                    'Bank minus pop log(HR) = %.6f, ' ...
                    '95%% CI = [%.6f, %.6f], robust p = %.6g, ' ...
                    'permutation p = %.6g (%d valid)\n'], ...
                    betaBankMinusPop, betaBankMinusPopCILow, ...
                    betaBankMinusPopCIHigh, pValueBankVsPop, ...
                    permutationPValueBankVsPop, ...
                    nValidPermutationsBankVsPop);
            else
                fprintf([ ...
                    'log(HR) = %.6f, HR = %.6f, ' ...
                    '95%% CI = [%.6f, %.6f], robust p = %.6g, ' ...
                    'permutation p = %.6g (%d valid)\n'], ...
                    betaPrimary, hazardRatio, hazardRatioCILow, ...
                    hazardRatioCIHigh, pValuePrimary, ...
                    permutationPValuePrimary, ...
                    nValidPermutationsPrimary);
            end
        end

    end

    %% Final hard removal of excluded labels

    excludedResultRows = ...
        isExcludedAreaLabel(areaResults.anatomicalArea);

    if any(excludedResultRows)
        fprintf([ ...
            '\nHard-removing %d NaC/white-matter/lateral-ventricle result rows ' ...
            'before saving and plotting.\n'], ...
            sum(excludedResultRows));
        areaResults(excludedResultRows, :) = [];
    end

    %% Uncorrected permutation significance

    fittedRows = areaResults.status == "fitted" & ...
        isfinite(areaResults.permutationPValue);

    if any(fittedRows)
        areaResults.significantUncorrected(fittedRows) = ...
            areaResults.permutationPValue(fittedRows) < 0.05;
    end

    if analysisType == "BR"
        fittedPopRows = areaResults.status == "fitted" & ...
            isfinite(areaResults.permutationPValuePop);
        fittedDifferenceRows = areaResults.status == "fitted" & ...
            isfinite(areaResults.permutationPValueBankVsPop);

        areaResults.significantPopUncorrected(fittedPopRows) = ...
            areaResults.permutationPValuePop(fittedPopRows) < 0.05;

        areaResults.significantBankVsPopUncorrected( ...
            fittedDifferenceRows) = ...
            areaResults.permutationPValueBankVsPop( ...
                fittedDifferenceRows) < 0.05;
    end

    areaResults = sortrows( ...
        areaResults, {'status', 'permutationPValue'}, ...
        {'ascend', 'ascend'});

end

function [permutationPValuePrimary, permutationPValuePop, ...
    permutationPValueBankVsPop, nValidPrimary, nValidPop, ...
    nValidBankVsPop] = runAreaPermutationTest( ...
        participants, anatomicalArea, analysisType, ...
        postIEDWindowSeconds, settings, observedRobustZPrimary, ...
        observedRobustZPop, observedRobustZBankMinusPop)

    numberOfPermutations = settings.numberOfPermutations;
    minimumValidPermutations = settings.minimumValidPermutations;

    permutedRobustZPrimary = NaN(numberOfPermutations, 1);
    permutedRobustZPop = NaN(numberOfPermutations, 1);
    permutedRobustZBankMinusPop = ...
        NaN(numberOfPermutations, 1);

    coxOptions = statset('coxphfit');
    coxOptions.Display = 'off';
    coxOptions.MaxIter = 1000;
    coxOptions.MaxFunEvals = 5000;

    for permutationNumber = 1:numberOfPermutations

        permutedData = buildPermutedAreaCountingProcessData( ...
            participants, anatomicalArea, analysisType, ...
            postIEDWindowSeconds);

        if isempty(permutedData)
            continue;
        end

        [permutedData.patientStratum, ~] = ...
            findgroups(permutedData.patientID);

        if analysisType == "BR"
            strata = findgroups( ...
                permutedData.patientID, ...
                permutedData.transitionType);
        else
            strata = permutedData.patientStratum;
        end

        try
            [X, ~, ~] = buildPredictorMatrix( ...
                permutedData, analysisType);
        catch
            continue;
        end

        T = [permutedData.tStart, permutedData.tStop];
        censoring = logical(permutedData.censored);

        validRows = ...
            all(isfinite(X), 2) & ...
            all(isfinite(T), 2) & ...
            T(:, 1) >= 0 & ...
            T(:, 2) > T(:, 1) & ...
            isfinite(strata);

        X = X(validRows, :);
        T = T(validRows, :);
        censoring = censoring(validRows);
        strata = strata(validRows);
        permutedData = permutedData(validRows, :);

        if isempty(X) || size(X, 1) <= size(X, 2)
            continue;
        end

        eventAtStop = permutedData.eventAtStop == 1;
        insideWindow = permutedData.postIED == 1;

        if analysisType == "BR"
            bankRows = permutedData.transitionType == "bank";
            popRows = permutedData.transitionType == "pop";

            hasRequiredEvents = ...
                any(eventAtStop & bankRows & insideWindow) && ...
                any(eventAtStop & bankRows & ~insideWindow) && ...
                any(eventAtStop & popRows & insideWindow) && ...
                any(eventAtStop & popRows & ~insideWindow);
        else
            hasRequiredEvents = ...
                any(eventAtStop & insideWindow) && ...
                any(eventAtStop & ~insideWindow);
        end

        if ~hasRequiredEvents
            continue;
        end

        try
            [betaPermutation, ~, ~, statsPermutation] = coxphfit( ...
                X, ...
                T, ...
                'Censoring', censoring, ...
                'Strata', strata, ...
                'Ties', 'efron', ...
                'Baseline', 0, ...
                'Options', coxOptions);

            [robustCovariancePermutation, ~, ...
                robustZPermutation, ~] = ...
                computeClusterRobustInference( ...
                    statsPermutation, betaPermutation, ...
                    permutedData.patientStratum);

            if ~isempty(robustZPermutation) && ...
                    isfinite(robustZPermutation(1))
                permutedRobustZPrimary(permutationNumber) = ...
                    robustZPermutation(1);
            end

            if analysisType == "BR" && ...
                    length(robustZPermutation) >= 2 && ...
                    isfinite(robustZPermutation(2))
                permutedRobustZPop(permutationNumber) = ...
                    robustZPermutation(2);

                betaDifferencePermutation = ...
                    betaPermutation(1) - betaPermutation(2);
                varianceDifferencePermutation = ...
                    robustCovariancePermutation(1, 1) + ...
                    robustCovariancePermutation(2, 2) - ...
                    2 * robustCovariancePermutation(1, 2);
                seDifferencePermutation = sqrt( ...
                    max(varianceDifferencePermutation, 0));

                if isfinite(seDifferencePermutation) && ...
                        seDifferencePermutation > 0
                    permutedRobustZBankMinusPop( ...
                        permutationNumber) = ...
                        betaDifferencePermutation / ...
                        seDifferencePermutation;
                end
            end
        catch
            % Failed permutation fits remain NaN and are not counted.
        end

        if mod(permutationNumber, 100) == 0
            fprintf('  completed %d/%d permutations\n', ...
                permutationNumber, numberOfPermutations);
        end

    end

    validPrimary = isfinite(permutedRobustZPrimary);
    validPop = isfinite(permutedRobustZPop);
    validBankVsPop = isfinite( ...
        permutedRobustZBankMinusPop);

    nValidPrimary = sum(validPrimary);
    nValidPop = sum(validPop);
    nValidBankVsPop = sum(validBankVsPop);

    permutationPValuePrimary = NaN;
    permutationPValuePop = NaN;
    permutationPValueBankVsPop = NaN;

    if isfinite(observedRobustZPrimary) && ...
            nValidPrimary >= minimumValidPermutations
        permutationPValuePrimary = ...
            (1 + sum(abs( ...
                permutedRobustZPrimary(validPrimary)) >= ...
                abs(observedRobustZPrimary))) / ...
            (nValidPrimary + 1);
    end

    if analysisType == "BR"
        if isfinite(observedRobustZPop) && ...
                nValidPop >= minimumValidPermutations
            permutationPValuePop = ...
                (1 + sum(abs( ...
                    permutedRobustZPop(validPop)) >= ...
                    abs(observedRobustZPop))) / ...
                (nValidPop + 1);
        end

        if isfinite(observedRobustZBankMinusPop) && ...
                nValidBankVsPop >= minimumValidPermutations
            permutationPValueBankVsPop = ...
                (1 + sum(abs( ...
                    permutedRobustZBankMinusPop( ...
                        validBankVsPop)) >= ...
                    abs(observedRobustZBankMinusPop))) / ...
                (nValidBankVsPop + 1);
        end
    end

end

function permutedData = buildPermutedAreaCountingProcessData( ...
    participants, anatomicalArea, analysisType, ...
    postIEDWindowSeconds)

    permutedData = emptyCountingProcessTable();

    for pt = 1:length(participants)

        P = participants(pt);
        areaLocalChannels = find( ...
            P.selectedAreaLabels == anatomicalArea);

        if isempty(areaLocalChannels)
            continue;
        end

        areaIEDoccurrence = filterIEDsToArea( ...
            P.IEDoccurrence, areaLocalChannels);

        validTrialNumbers = find(P.validTrials);

        if isempty(validTrialNumbers)
            continue;
        end

        for tt = 1:length(validTrialNumbers)

            trialNumber = validTrialNumbers(tt);
            durationSeconds = P.durationSeconds(trialNumber);

            % Apply one random circular shift to every IED timestamp in
            % this trial. This keeps the trial's IED count and the
            % temporal spacing between its IEDs unchanged.
            shiftedTrialIEDoccurrence = ...
                circularShiftIEDsWithinTrial( ...
                    areaIEDoccurrence, trialNumber, ...
                    durationSeconds, P.samplingFrequencyHz);

            if analysisType == "BR"
                bankObserved = P.BankedTrials(trialNumber) == 1;
                popObserved = P.BankedTrials(trialNumber) == 0;

                bankRows = makePostIEDWindowRows( ...
                    P.patientID, ...
                    trialNumber, ...
                    durationSeconds, ...
                    shiftedTrialIEDoccurrence, ...
                    P.samplingFrequencyHz, ...
                    P.balloonColorCode(trialNumber), ...
                    bankObserved, ...
                    postIEDWindowSeconds, ...
                    "bank");

                popRows = makePostIEDWindowRows( ...
                    P.patientID, ...
                    trialNumber, ...
                    durationSeconds, ...
                    shiftedTrialIEDoccurrence, ...
                    P.samplingFrequencyHz, ...
                    P.balloonColorCode(trialNumber), ...
                    popObserved, ...
                    postIEDWindowSeconds, ...
                    "pop");

                trialRows = [bankRows; popRows];
            else
                trialRows = makePostIEDWindowRows( ...
                    P.patientID, ...
                    trialNumber, ...
                    durationSeconds, ...
                    shiftedTrialIEDoccurrence, ...
                    P.samplingFrequencyHz, ...
                    P.balloonColorCode(trialNumber), ...
                    true, ...
                    postIEDWindowSeconds, ...
                    "single");
            end

            permutedData = [permutedData; trialRows];
        end
    end

end

function shiftedTrialIEDoccurrence = ...
    circularShiftIEDsWithinTrial( ...
        areaIEDoccurrence, trialNumber, durationSeconds, ...
        samplingFrequencyHz)

    if isempty(areaIEDoccurrence) || ...
            size(areaIEDoccurrence, 2) < 3 || ...
            ~isfinite(durationSeconds) || durationSeconds <= 0 || ...
            ~isfinite(samplingFrequencyHz) || ...
            samplingFrequencyHz <= 0
        shiftedTrialIEDoccurrence = ...
            zeros(0, size(areaIEDoccurrence, 2));
        return;
    end

    % makePostIEDWindowRows uses sample/samplingFrequencyHz and requires
    % the IED time to be strictly smaller than the trial duration.
    maximumValidSample = ...
        ceil(durationSeconds * samplingFrequencyHz) - 1;

    if maximumValidSample < 1
        shiftedTrialIEDoccurrence = ...
            zeros(0, size(areaIEDoccurrence, 2));
        return;
    end

    trialRows = ...
        isfinite(areaIEDoccurrence(:, 1)) & ...
        round(areaIEDoccurrence(:, 1)) == trialNumber & ...
        isfinite(areaIEDoccurrence(:, 3)) & ...
        areaIEDoccurrence(:, 3) >= 1 & ...
        areaIEDoccurrence(:, 3) <= maximumValidSample;

    shiftedTrialIEDoccurrence = ...
        areaIEDoccurrence(trialRows, :);

    if isempty(shiftedTrialIEDoccurrence)
        return;
    end

    % One common integer-sample shift preserves duplicate IEDs and the
    % circular spacing between all IEDs within this trial.
    shiftInSamples = randi(maximumValidSample) - 1;
    originalSamples = round( ...
        shiftedTrialIEDoccurrence(:, 3));
    shiftedSamples = mod( ...
        originalSamples - 1 + shiftInSamples, ...
        maximumValidSample) + 1;

    shiftedTrialIEDoccurrence(:, 1) = trialNumber;
    shiftedTrialIEDoccurrence(:, 3) = shiftedSamples;

end

function [ITResults, RTResults, BRResults] = ...
    applyFDRWithinAreaAcrossOutcomes( ...
        ITResults, RTResults, BRResults, fdrAlpha)

    % Correct the permutation p-values. PR is the pop coefficient from
    % the combined BR/PR competing-transition model.
    ITResults.qValueAcrossIT_RT_BR_PR = NaN(height(ITResults), 1);
    ITResults.significantFDRAcrossIT_RT_BR_PR = ...
        false(height(ITResults), 1);

    RTResults.qValueAcrossIT_RT_BR_PR = NaN(height(RTResults), 1);
    RTResults.significantFDRAcrossIT_RT_BR_PR = ...
        false(height(RTResults), 1);

    BRResults.qValueBankAcrossIT_RT_BR_PR = NaN(height(BRResults), 1);
    BRResults.significantBankFDRAcrossIT_RT_BR_PR = ...
        false(height(BRResults), 1);

    BRResults.qValuePopAcrossIT_RT_BR_PR = NaN(height(BRResults), 1);
    BRResults.significantPopFDRAcrossIT_RT_BR_PR = ...
        false(height(BRResults), 1);

    allAreas = unique([ ...
        ITResults.anatomicalArea; ...
        RTResults.anatomicalArea; ...
        BRResults.anatomicalArea], ...
        'stable');

    for aa = 1:length(allAreas)

        areaName = allAreas(aa);
        rawPValues = zeros(0, 1);
        resultSource = strings(0, 1);
        resultRow = zeros(0, 1);

        itRow = find(ITResults.anatomicalArea == areaName, 1);
        if ~isempty(itRow) && ...
                ITResults.status(itRow) == "fitted" && ...
                isfinite(ITResults.permutationPValue(itRow))
            rawPValues(end + 1, 1) = ...
                ITResults.permutationPValue(itRow);
            resultSource(end + 1, 1) = "IT";
            resultRow(end + 1, 1) = itRow;
        end

        rtRow = find(RTResults.anatomicalArea == areaName, 1);
        if ~isempty(rtRow) && ...
                RTResults.status(rtRow) == "fitted" && ...
                isfinite(RTResults.permutationPValue(rtRow))
            rawPValues(end + 1, 1) = ...
                RTResults.permutationPValue(rtRow);
            resultSource(end + 1, 1) = "RT";
            resultRow(end + 1, 1) = rtRow;
        end

        brRow = find(BRResults.anatomicalArea == areaName, 1);
        if ~isempty(brRow) && BRResults.status(brRow) == "fitted"
            if isfinite(BRResults.permutationPValue(brRow))
                rawPValues(end + 1, 1) = ...
                    BRResults.permutationPValue(brRow);
                resultSource(end + 1, 1) = "BR";
                resultRow(end + 1, 1) = brRow;
            end

            if isfinite(BRResults.permutationPValuePop(brRow))
                rawPValues(end + 1, 1) = ...
                    BRResults.permutationPValuePop(brRow);
                resultSource(end + 1, 1) = "PR";
                resultRow(end + 1, 1) = brRow;
            end
        end

        if isempty(rawPValues)
            continue;
        end

        correctedQValues = benjaminiHochbergQValues(rawPValues);

        for jj = 1:length(correctedQValues)
            switch resultSource(jj)
                case "IT"
                    row = resultRow(jj);
                    ITResults.qValueAcrossIT_RT_BR_PR(row) = ...
                        correctedQValues(jj);
                    ITResults.significantFDRAcrossIT_RT_BR_PR(row) = ...
                        correctedQValues(jj) < fdrAlpha;

                case "RT"
                    row = resultRow(jj);
                    RTResults.qValueAcrossIT_RT_BR_PR(row) = ...
                        correctedQValues(jj);
                    RTResults.significantFDRAcrossIT_RT_BR_PR(row) = ...
                        correctedQValues(jj) < fdrAlpha;

                case "BR"
                    row = resultRow(jj);
                    BRResults.qValueBankAcrossIT_RT_BR_PR(row) = ...
                        correctedQValues(jj);
                    BRResults.significantBankFDRAcrossIT_RT_BR_PR(row) = ...
                        correctedQValues(jj) < fdrAlpha;

                case "PR"
                    row = resultRow(jj);
                    BRResults.qValuePopAcrossIT_RT_BR_PR(row) = ...
                        correctedQValues(jj);
                    BRResults.significantPopFDRAcrossIT_RT_BR_PR(row) = ...
                        correctedQValues(jj) < fdrAlpha;
            end
        end

    end

    fprintf('\n============================================================\n');
    fprintf(['BH-FDR correction of permutation p-values finished ' ...
        'within each area across IT, RT, BR, and PR.\n']);
    fprintf('FDR threshold: q < %.3f\n', fdrAlpha);
    fprintf('Significant IT effects: %d\n', ...
        sum(ITResults.significantFDRAcrossIT_RT_BR_PR));
    fprintf('Significant RT effects: %d\n', ...
        sum(RTResults.significantFDRAcrossIT_RT_BR_PR));
    fprintf('Significant BR effects: %d\n', ...
        sum(BRResults.significantBankFDRAcrossIT_RT_BR_PR));
    fprintf('Significant PR effects: %d\n', ...
        sum(BRResults.significantPopFDRAcrossIT_RT_BR_PR));

end

function qValues = benjaminiHochbergQValues(pValues)

    pValues = pValues(:);
    numberOfTests = length(pValues);

    [sortedPValues, sortOrder] = sort(pValues, 'ascend');
    sortedQValues = sortedPValues .* numberOfTests ./ ...
        (1:numberOfTests)';

    % Enforce monotonic BH adjusted p-values without requiring mafdr.
    for ii = numberOfTests - 1:-1:1
        sortedQValues(ii) = min( ...
            sortedQValues(ii), sortedQValues(ii + 1));
    end

    sortedQValues = min(max(sortedQValues, 0), 1);

    qValues = NaN(numberOfTests, 1);
    qValues(sortOrder) = sortedQValues;

end

function saveCorrectedAreaCSV( ...
    outputFolderName, analysisType, areaResults)

    resultsOutputFile = fullfile(outputFolderName, ...
        char(analysisType + "_brain_area_cox_results.csv"));

    writetable(areaResults, resultsOutputFile);

end



function results = initializeAreaResultsTable()

    results = table( ...
        strings(0, 1), ...  % anatomicalArea
        strings(0, 1), ...  % status
        zeros(0, 1), ...    % nParticipantsWithCoverage
        zeros(0, 1), ...    % nParticipantsWithIED
        zeros(0, 1), ...    % nModelParticipants
        zeros(0, 1), ...    % nValidTrials
        zeros(0, 1), ...    % nIEDsInArea
        zeros(0, 1), ...    % nCountingRows
        zeros(0, 1), ...    % nEndpointEvents
        zeros(0, 1), ...    % nEventsOutsideWindow
        zeros(0, 1), ...    % nEventsInsideWindow
        zeros(0, 1), ...    % timeOutsideWindowSeconds
        zeros(0, 1), ...    % timeInsideWindowSeconds
        strings(0, 1), ...  % referenceBalloonColor
        zeros(0, 1), ...    % beta_logHazard
        zeros(0, 1), ...    % clusterRobustSE
        zeros(0, 1), ...    % clusterRobustZ
        zeros(0, 1), ...    % pValue
        zeros(0, 1), ...    % permutationPValue
        zeros(0, 1), ...    % nValidPermutations
        zeros(0, 1), ...    % betaCILow
        zeros(0, 1), ...    % betaCIHigh
        zeros(0, 1), ...    % hazardRatio
        zeros(0, 1), ...    % hazardRatioCILow
        zeros(0, 1), ...    % hazardRatioCIHigh
        false(0, 1), ...    % significantUncorrected
        zeros(0, 1), ...    % nBankEvents
        zeros(0, 1), ...    % nPopEvents
        zeros(0, 1), ...    % nBankEventsOutsideWindow
        zeros(0, 1), ...    % nBankEventsInsideWindow
        zeros(0, 1), ...    % nPopEventsOutsideWindow
        zeros(0, 1), ...    % nPopEventsInsideWindow
        zeros(0, 1), ...    % betaPop_logHazard
        zeros(0, 1), ...    % clusterRobustSEPop
        zeros(0, 1), ...    % clusterRobustZPop
        zeros(0, 1), ...    % pValuePop
        zeros(0, 1), ...    % permutationPValuePop
        zeros(0, 1), ...    % nValidPermutationsPop
        zeros(0, 1), ...    % betaPopCILow
        zeros(0, 1), ...    % betaPopCIHigh
        zeros(0, 1), ...    % hazardRatioPop
        zeros(0, 1), ...    % hazardRatioPopCILow
        zeros(0, 1), ...    % hazardRatioPopCIHigh
        false(0, 1), ...    % significantPopUncorrected
        zeros(0, 1), ...    % betaBankMinusPop
        zeros(0, 1), ...    % clusterRobustSEBankMinusPop
        zeros(0, 1), ...    % clusterRobustZBankMinusPop
        zeros(0, 1), ...    % pValueBankVsPop
        zeros(0, 1), ...    % permutationPValueBankVsPop
        zeros(0, 1), ...    % nValidPermutationsBankVsPop
        zeros(0, 1), ...    % betaBankMinusPopCILow
        zeros(0, 1), ...    % betaBankMinusPopCIHigh
        false(0, 1), ...    % significantBankVsPopUncorrected
        'VariableNames', { ...
            'anatomicalArea', ...
            'status', ...
            'nParticipantsWithCoverage', ...
            'nParticipantsWithIED', ...
            'nModelParticipants', ...
            'nValidTrials', ...
            'nIEDsInArea', ...
            'nCountingRows', ...
            'nEndpointEvents', ...
            'nEventsOutsideWindow', ...
            'nEventsInsideWindow', ...
            'timeOutsideWindowSeconds', ...
            'timeInsideWindowSeconds', ...
            'referenceBalloonColor', ...
            'beta_logHazard', ...
            'clusterRobustSE', ...
            'clusterRobustZ', ...
            'pValue', ...
            'permutationPValue', ...
            'nValidPermutations', ...
            'betaCILow', ...
            'betaCIHigh', ...
            'hazardRatio', ...
            'hazardRatioCILow', ...
            'hazardRatioCIHigh', ...
            'significantUncorrected', ...
            'nBankEvents', ...
            'nPopEvents', ...
            'nBankEventsOutsideWindow', ...
            'nBankEventsInsideWindow', ...
            'nPopEventsOutsideWindow', ...
            'nPopEventsInsideWindow', ...
            'betaPop_logHazard', ...
            'clusterRobustSEPop', ...
            'clusterRobustZPop', ...
            'pValuePop', ...
            'permutationPValuePop', ...
            'nValidPermutationsPop', ...
            'betaPopCILow', ...
            'betaPopCIHigh', ...
            'hazardRatioPop', ...
            'hazardRatioPopCILow', ...
            'hazardRatioPopCIHigh', ...
            'significantPopUncorrected', ...
            'betaBankMinusPop', ...
            'clusterRobustSEBankMinusPop', ...
            'clusterRobustZBankMinusPop', ...
            'pValueBankVsPop', ...
            'permutationPValueBankVsPop', ...
            'nValidPermutationsBankVsPop', ...
            'betaBankMinusPopCILow', ...
            'betaBankMinusPopCIHigh', ...
            'significantBankVsPopUncorrected'});

end

function labels = getSelectedChannelLabels( ...
    anatomicalLocs, selectedChans, nSelectedChannels)

    labels = convertLabelsToString(anatomicalLocs);
    labels = labels(:);

    if length(labels) >= max(selectedChans)
        labels = labels(selectedChans);
    elseif length(labels) == nSelectedChannels
        % anatomicalLocs was already restricted to selected channels.
    else
        error(['Cannot map anatomicalLocs to selected channels. ' ...
            'Labels = %d, selected channels = %d, maximum channel = %d.'], ...
            length(labels), nSelectedChannels, max(selectedChans));
    end

end

function labels = convertLabelsToString(rawLabels)

    if isstring(rawLabels)
        labels = rawLabels;
    elseif iscell(rawLabels)
        labels = strings(numel(rawLabels), 1);
        for ii = 1:numel(rawLabels)
            value = rawLabels{ii};
            if isempty(value)
                labels(ii) = "";
            elseif iscell(value) && numel(value) == 1
                labels(ii) = string(value{1});
            else
                labels(ii) = string(value);
            end
        end
    elseif ischar(rawLabels)
        labels = string(cellstr(rawLabels));
    elseif iscategorical(rawLabels)
        labels = string(rawLabels);
    else
        labels = string(rawLabels);
    end

    labels = labels(:);

end

function labels = cleanAreaLabels(labels, combineLeftAndRight)

    labels = strip(string(labels));
    labels(ismissing(labels) | strlength(labels) == 0) = "Unknown";

    if combineLeftAndRight
        labels = regexprep(labels, ...
            '^\s*\(?\s*(Left|Right|LH|RH|L|R)\s*\)?[_\-\s]+', ...
            '', 'ignorecase');

        labels = regexprep(labels, ...
            '[_\-\s]+\(?\s*(Left|Right|LH|RH|L|R)\s*\)?\s*$', ...
            '', 'ignorecase');

        labels = regexprep(labels, ...
            '^\s*(Left|Right)\s+hemisphere[_\-\s]+', ...
            '', 'ignorecase');

        labels = regexprep(labels, ...
            '[_\-\s]+(Left|Right)\s+hemisphere\s*$', ...
            '', 'ignorecase');

        labels = regexprep(labels, '[_\-]+', ' ');
        labels = regexprep(labels, '\s+', ' ');
        labels = strip(labels);
        labels(strlength(labels) == 0) = "Unknown";
    end

end

function excludedRows = isExcludedAreaLabel(labels)

    normalizedLabels = lower(strip(string(labels)));
    normalizedLabels = regexprep(normalizedLabels, '[_\-]+', ' ');
    normalizedLabels = regexprep(normalizedLabels, '\s+', ' ');

    % Remove EVERY label containing NaC, including NaC60, L-NaC12, etc.
    isNaC = ...
        contains(normalizedLabels, "nac") | ...
        contains(normalizedLabels, "nucleus accumbens") | ...
        contains(normalizedLabels, "accumbens");

    % Create compact labels so separators and capitalization do not matter.
    compactLabels = regexprep(normalizedLabels, '[^a-z0-9]', '');

    % Remove white-matter labels, including WM, WM60, white_matter, etc.
    isWhiteMatter = ...
        contains(normalizedLabels, "white matter") | ...
        contains(compactLabels, "whitematter") | ...
        startsWith(compactLabels, "wm");

    % Remove lateral-ventricle labels without case sensitivity.
    % This includes forms such as:
    % Lateral Ventricle, lateral_ventricle, LATERAL-VENTRICLE, etc.
    isLateralVentricle = ...
        contains(normalizedLabels, "lateral ventricle") | ...
        contains(compactLabels, "lateralventricle");

    excludedRows = isNaC | isWhiteMatter | isLateralVentricle;

end

function samplingFrequencyHz = getSamplingFrequency( ...
    LFPIED, defaultSamplingFrequencyHz)

    if isfield(LFPIED, 'Fs') && ...
            isscalar(LFPIED.Fs) && ...
            isfinite(LFPIED.Fs) && ...
            LFPIED.Fs > 0
        samplingFrequencyHz = double(LFPIED.Fs);
    else
        samplingFrequencyHz = defaultSamplingFrequencyHz;
    end

end

function balloonColorCode = mapBalloonColorCode(balloonType)

    balloonType = double(balloonType(:));
    balloonColorCode = NaN(size(balloonType));

    validRows = ...
        isfinite(balloonType) & ...
        ismember(round(balloonType), [1 2 3 11 12 13]);

    balloonColorCode(validRows) = ...
        mod(round(balloonType(validRows)) - 1, 10) + 1;

end

function areaIEDoccurrence = filterIEDsToArea( ...
    IEDoccurrence, areaLocalChannels)

    if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 3
        areaIEDoccurrence = zeros(0, 3);
        return;
    end

    localChannelIndex = round(IEDoccurrence(:, 2));

    keepRows = ...
        isfinite(localChannelIndex) & ...
        ismember(localChannelIndex, areaLocalChannels);

    areaIEDoccurrence = IEDoccurrence(keepRows, :);

end

function validRows = getValidAreaIEDRows( ...
    areaIEDoccurrence, validTrialMask)

    if isempty(areaIEDoccurrence) || size(areaIEDoccurrence, 2) < 3
        validRows = false(0, 1);
        return;
    end

    trialNumber = round(areaIEDoccurrence(:, 1));
    nTrials = length(validTrialMask);

    validRows = ...
        isfinite(trialNumber) & ...
        trialNumber >= 1 & ...
        trialNumber <= nTrials & ...
        isfinite(areaIEDoccurrence(:, 3)) & ...
        areaIEDoccurrence(:, 3) >= 1;

    validIndices = find(validRows);

    if ~isempty(validIndices)
        validRows(validIndices) = validTrialMask(trialNumber(validIndices));
    end

end

function countingProcessData = emptyCountingProcessTable()

    countingProcessData = table( ...
        strings(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        false(0, 1), ...
        false(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        strings(0, 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'tStart', ...
            'tStop', ...
            'censored', ...
            'eventAtStop', ...
            'postIED', ...
            'activeIEDWindowCount', ...
            'timeSinceMostRecentIED_seconds', ...
            'balloonColorCode', ...
            'samplingFrequencyHz', ...
            'transitionType'});

end

function trialRows = makePostIEDWindowRows( ...
    patientID, trialNumber, durationSeconds, IEDoccurrence, ...
    samplingFrequencyHz, balloonColorCode, finalEventObserved, ...
    postIEDWindowSeconds, transitionType)

    if isempty(IEDoccurrence) || size(IEDoccurrence, 2) < 3
        IEDtimes = [];
    else
        validIEDRows = ...
            isfinite(IEDoccurrence(:, 1)) & ...
            isfinite(IEDoccurrence(:, 3)) & ...
            round(IEDoccurrence(:, 1)) == trialNumber & ...
            IEDoccurrence(:, 3) >= 1;

        sampleIndices = double(IEDoccurrence(validIEDRows, 3));
        IEDtimes = sampleIndices ./ samplingFrequencyHz;

        IEDtimes = IEDtimes( ...
            isfinite(IEDtimes) & ...
            IEDtimes > 0 & ...
            IEDtimes < durationSeconds);

        % Keep every IED occurrence, including duplicate times.
        IEDtimes = sort(IEDtimes);
    end

    if isempty(IEDtimes)
        breakTimes = [0; durationSeconds];
    else
        windowEndTimes = min( ...
            IEDtimes + postIEDWindowSeconds, durationSeconds);

        breakTimes = unique([ ...
            0; IEDtimes(:); windowEndTimes(:); durationSeconds], ...
            'sorted');
    end

    breakTimes = breakTimes( ...
        isfinite(breakTimes) & ...
        breakTimes >= 0 & ...
        breakTimes <= durationSeconds);

    breakTimes = unique(breakTimes, 'sorted');

    if length(breakTimes) < 2
        breakTimes = [0; durationSeconds];
    end

    tStart = breakTimes(1:end-1);
    tStop = breakTimes(2:end);

    validIntervals = tStop > tStart;
    tStart = tStart(validIntervals);
    tStop = tStop(validIntervals);

    intervalMidpoint = (tStart + tStop) ./ 2;

    postIED = zeros(length(tStart), 1);
    activeIEDWindowCount = zeros(length(tStart), 1);
    timeSinceMostRecentIED = NaN(length(tStart), 1);

    for kk = 1:length(tStart)

        if isempty(IEDtimes)
            continue;
        end

        activeWindows = ...
            intervalMidpoint(kk) >= IEDtimes & ...
            intervalMidpoint(kk) <= ...
                (IEDtimes + postIEDWindowSeconds);

        activeIEDWindowCount(kk) = sum(activeWindows);
        postIED(kk) = double(any(activeWindows));

        priorIEDtimes = IEDtimes(IEDtimes < intervalMidpoint(kk));

        if ~isempty(priorIEDtimes)
            timeSinceMostRecentIED(kk) = ...
                intervalMidpoint(kk) - max(priorIEDtimes);
        end

    end

    censored = true(length(tStart), 1);
    eventAtStop = false(length(tStart), 1);

    if finalEventObserved
        censored(end) = false;
        eventAtStop(end) = true;
    end

    trialRows = table( ...
        repmat(patientID, length(tStart), 1), ...
        repmat(trialNumber, length(tStart), 1), ...
        tStart, ...
        tStop, ...
        censored, ...
        eventAtStop, ...
        postIED, ...
        activeIEDWindowCount, ...
        timeSinceMostRecentIED, ...
        repmat(balloonColorCode, length(tStart), 1), ...
        repmat(samplingFrequencyHz, length(tStart), 1), ...
        repmat(string(transitionType), length(tStart), 1), ...
        'VariableNames', { ...
            'patientID', ...
            'trialNumber', ...
            'tStart', ...
            'tStop', ...
            'censored', ...
            'eventAtStop', ...
            'postIED', ...
            'activeIEDWindowCount', ...
            'timeSinceMostRecentIED_seconds', ...
            'balloonColorCode', ...
            'samplingFrequencyHz', ...
            'transitionType'});

end

function [X, predictorNames, referenceColorName] = ...
    buildPredictorMatrix(countingProcessData, analysisType)

    % Binary occurrence predictor: 1 anywhere inside at least one active
    % post-IED window and 0 outside all post-IED windows.
    postIEDOccurrence = double(countingProcessData.postIED);

    if analysisType == "BR"
        bankTransition = double( ...
            countingProcessData.transitionType == "bank");
        popTransition = double( ...
            countingProcessData.transitionType == "pop");

        X = [ ...
            postIEDOccurrence .* bankTransition, ...
            postIEDOccurrence .* popTransition];

        predictorNames = [ ...
            "post_area_ied_occurrence_bank_hazard"; ...
            "post_area_ied_occurrence_pop_hazard"];
    else
        X = postIEDOccurrence;
        predictorNames = ...
            "post_area_ied_occurrence_within_selected_window";
    end

    observedColors = unique( ...
        countingProcessData.balloonColorCode, 'sorted');

    observedColors = observedColors(ismember(observedColors, [1 2 3]));

    if isempty(observedColors)
        error('No valid balloon colors were found.');
    end

    if ismember(1, observedColors)
        referenceColor = 1;
    else
        referenceColor = observedColors(1);
    end

    colorNames = ["yellow", "orange", "red"];
    referenceColorName = colorNames(referenceColor);

    comparisonColors = observedColors(observedColors ~= referenceColor);

    for cc = 1:length(comparisonColors)
        colorCode = comparisonColors(cc);
        colorDummy = double( ...
            countingProcessData.balloonColorCode == colorCode);

        if analysisType == "BR"
            X(:, end + 1) = colorDummy .* bankTransition;
            predictorNames(end + 1, 1) = ...
                colorNames(colorCode) + "_vs_" + ...
                colorNames(referenceColor) + "_bank_hazard";

            X(:, end + 1) = colorDummy .* popTransition;
            predictorNames(end + 1, 1) = ...
                colorNames(colorCode) + "_vs_" + ...
                colorNames(referenceColor) + "_pop_hazard";
        else
            X(:, end + 1) = colorDummy;
            predictorNames(end + 1, 1) = ...
                colorNames(colorCode) + "_vs_" + ...
                colorNames(referenceColor);
        end
    end

end

function [robustCovariance, robustSE, robustZ, robustP] = ...
    computeClusterRobustInference(stats, beta, clusterID)

    beta = beta(:);
    nPredictors = length(beta);
    clusterID = clusterID(:);

    uniqueClusters = unique(clusterID(isfinite(clusterID)));
    nClusters = length(uniqueClusters);

    canUseClusterScores = ...
        isfield(stats, 'scores') && ...
        size(stats.scores, 1) == length(clusterID) && ...
        size(stats.scores, 2) == nPredictors;

    if nClusters < 2 || ~canUseClusterScores
        robustCovariance = stats.covb;
        robustSE = stats.se(:);
        robustZ = stats.z(:);
        robustP = stats.p(:);
        return;
    end

    clusterScoreSums = zeros(nClusters, nPredictors);

    for gg = 1:nClusters
        rows = clusterID == uniqueClusters(gg);
        thisClusterScores = stats.scores(rows, :);
        thisClusterScores(~isfinite(thisClusterScores)) = 0;
        clusterScoreSums(gg, :) = sum(thisClusterScores, 1);
    end

    meat = clusterScoreSums' * clusterScoreSums;
    bread = stats.covb;

    robustCovariance = bread * meat * bread;
    robustCovariance = ...
        (nClusters / (nClusters - 1)) .* robustCovariance;

    robustSE = sqrt(max(diag(robustCovariance), 0));

    zeroSERows = robustSE <= 0 | ~isfinite(robustSE);
    robustSE(zeroSERows) = stats.se(zeroSERows);

    robustZ = beta ./ robustSE;
    robustP = 2 .* normcdf(-abs(robustZ), 0, 1);

end

function plotSeparateAreaForestPlots( ...
    ITResults, RTResults, BRResults, ...
    colorIT, colorRT, colorBR, colorPop, markerAlpha, ...
    settings, itOutputPDF, rtOutputPDF, brOutputPDF)

    numberOfITAreas = max(countPlottableAreas(ITResults), 1);
    numberOfRTAreas = max(countPlottableAreas(RTResults), 1);
    numberOfBRAreas = max(countPlottableCompetingAreas(BRResults), 1);

    standardFigureWidth = 1700;
    itFigureHeight = max(650, 48 * numberOfITAreas + 250);
    rtFigureHeight = max(650, 48 * numberOfRTAreas + 250);

    % IT figure
    figIT = figure('Visible', 'off', 'Color', 'w');
    set(figIT, 'Position', ...
        [80 80 standardFigureWidth itFigureHeight]);

    layoutIT = tiledlayout(figIT, 1, 1, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    axIT = nexttile(layoutIT);
    plotAreaForestPanel( ...
        axIT, ITResults, colorIT, markerAlpha, ...
        "Inflation time", "IT", ...
        settings.postIEDWindowMillisecondsIT);

    exportgraphics(figIT, itOutputPDF, 'ContentType', 'vector');
    close(figIT);

    % RT figure
    figRT = figure('Visible', 'off', 'Color', 'w');
    set(figRT, 'Position', ...
        [80 80 standardFigureWidth rtFigureHeight]);

    layoutRT = tiledlayout(figRT, 1, 1, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    axRT = nexttile(layoutRT);
    plotAreaForestPanel( ...
        axRT, RTResults, colorRT, markerAlpha, ...
        "Response time", "RT", ...
        settings.postIEDWindowMillisecondsRT);

    exportgraphics(figRT, rtOutputPDF, 'ContentType', 'vector');
    close(figRT);

    % BR figure is deliberately long horizontally.
    brFigureWidth = 3000;
    brFigureHeight = max(600, 42 * numberOfBRAreas + 200);

    figBR = figure('Visible', 'off', 'Color', 'w');
    set(figBR, 'Position', ...
        [80 80 brFigureWidth brFigureHeight]);

    layoutBR = tiledlayout(figBR, 1, 1, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    axBR = nexttile(layoutBR);
    plotCompetingRiskForestPanel( ...
        axBR, BRResults, colorBR, colorPop, markerAlpha, ...
        settings.postIEDWindowMillisecondsBR);

    exportgraphics(figBR, brOutputPDF, 'ContentType', 'vector');
    close(figBR);

end

function numberOfAreas = countPlottableCompetingAreas(areaResults)

    plotRows = getCompetingForestPlotRows(areaResults);
    numberOfAreas = sum(plotRows);

end

function numberOfAreas = countPlottableAreas(areaResults)

    plotRows = getForestPlotRows(areaResults);
    numberOfAreas = sum(plotRows);

end

function plotAreaForestPanel( ...
    ax, areaResults, panelColor, markerAlpha, ...
    descriptiveTitle, abbreviation, postIEDWindowMilliseconds)

    plotRows = getForestPlotRows(areaResults);
    plotData = areaResults(plotRows, :);

    hold(ax, 'on');

    xline(ax, 0, '--', ...
        'LineWidth', 1.2, ...
        'Color', [0.25 0.25 0.25]);

    if isempty(plotData)
        ax.XLim = [-1 1];
        ax.YLim = [0 1];
        ax.YTick = [];
        text(ax, 0, 0.5, ...
        'No areas with permutation BH-FDR q < 0.05 across IT/RT/BR/PR', ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontSize', 11);
    else
        plotData = sortrows( ...
            plotData, 'beta_logHazard', 'ascend');
        nAreas = height(plotData);

        for ii = 1:nAreas
            plot(ax, ...
                [plotData.betaCILow(ii), plotData.betaCIHigh(ii)], ...
                [ii, ii], ...
                '-', ...
                'Color', panelColor, ...
                'LineWidth', 1.5);
        end

        scatter(ax, ...
            plotData.beta_logHazard, ...
            (1:nAreas)', ...
            65, ...
            panelColor, ...
            'filled', ...
            'MarkerFaceAlpha', markerAlpha, ...
            'MarkerEdgeColor', 'none');

        ax.YTick = 1:nAreas;

        % Keep the area and both counts in one tick label. Embedded line
        % breaks can be split into separate tick labels by some releases.
        areaTickLabels = strings(nAreas, 1);
        for ii = 1:nAreas
            areaTickLabels(ii) = sprintf( ...
                '%s  |  IED: %d  |  covered: %d', ...
                char(plotData.anatomicalArea(ii)), ...
                plotData.nParticipantsWithIED(ii), ...
                plotData.nParticipantsWithCoverage(ii));
        end
        ax.YTickLabel = cellstr(areaTickLabels);
        ax.YLim = [0.4, nAreas + 0.6];
    end

    ax.TickLabelInterpreter = 'none';
    ax.TickDir = 'out';
    % Set the axes font directly for compatibility across MATLAB releases.
    ax.FontSize = 9;

    xlabel(ax, ...
        'Log hazard ratio: post-IED window versus outside window');

    title(ax, {char(descriptiveTitle), ...
        sprintf('%s - %d-ms post-IED window', ...
            char(abbreviation), postIEDWindowMilliseconds), ...
        'Permutation BH-FDR across IT/RT/BR/PR within area'}, ...
        'FontSize', 12, ...
        'FontWeight', 'bold');

    box(ax, 'off');
    grid(ax, 'off');

end

function plotCompetingRiskForestPanel( ...
    ax, areaResults, bankColor, popColor, markerAlpha, ...
    postIEDWindowMilliseconds)

    plotRows = getCompetingForestPlotRows(areaResults);
    plotData = areaResults(plotRows, :);

    hold(ax, 'on');

    xline(ax, 0, '--', ...
        'LineWidth', 1.2, ...
        'Color', [0.25 0.25 0.25]);

    if isempty(plotData)
        ax.XLim = [-1 1];
        ax.YLim = [0 1];
        ax.YTick = [];
        text(ax, 0, 0.5, ...
        'No BR or PR effects with permutation BH-FDR q < 0.05', ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontSize', 11);
    else
        plotData = sortrows( ...
            plotData, 'beta_logHazard', 'ascend');
        nAreas = height(plotData);

        bankY = (1:nAreas)' + 0.12;
        popY = (1:nAreas)' - 0.12;

        allConfidenceValues = [ ...
            plotData.betaCILow; ...
            plotData.betaCIHigh; ...
            plotData.betaPopCILow; ...
            plotData.betaPopCIHigh; ...
            0];

        allConfidenceValues = ...
            allConfidenceValues(isfinite(allConfidenceValues));

        minimumX = min(allConfidenceValues);
        maximumX = max(allConfidenceValues);
        xRange = maximumX - minimumX;

        if ~isfinite(xRange) || xRange <= 0
            xRange = 1;
        end

        starOffset = 0.015 * xRange;
        leftPadding = 0.06 * xRange;
        rightPadding = 0.20 * xRange;

        for ii = 1:nAreas
            plot(ax, ...
                [plotData.betaCILow(ii), plotData.betaCIHigh(ii)], ...
                [bankY(ii), bankY(ii)], ...
                '-', ...
                'Color', bankColor, ...
                'LineWidth', 1.5);

            plot(ax, ...
                [plotData.betaPopCILow(ii), ...
                 plotData.betaPopCIHigh(ii)], ...
                [popY(ii), popY(ii)], ...
                '-', ...
                'Color', popColor, ...
                'LineWidth', 1.5);
        end

        bankPoint = scatter(ax, ...
            plotData.beta_logHazard, ...
            bankY, ...
            65, ...
            bankColor, ...
            'o', ...
            'filled', ...
            'MarkerFaceAlpha', markerAlpha, ...
            'MarkerEdgeColor', 'none');

        popPoint = scatter(ax, ...
            plotData.betaPop_logHazard, ...
            popY, ...
            65, ...
            popColor, ...
            'd', ...
            'filled', ...
            'MarkerFaceAlpha', markerAlpha, ...
            'MarkerEdgeColor', 'none');

        % A star beside a point means that the BR or PR coefficient
        % survives BH-FDR across IT, RT, BR, and PR within this area.
        for ii = 1:nAreas

            if plotData.significantBankFDRAcrossIT_RT_BR_PR(ii)
                text(ax, ...
                    plotData.beta_logHazard(ii) + starOffset, ...
                    bankY(ii), ...
                    '*', ...
                    'Color', bankColor, ...
                    'FontSize', 14, ...
                    'FontWeight', 'bold', ...
                    'HorizontalAlignment', 'left', ...
                    'VerticalAlignment', 'middle');
            end

            if plotData.significantPopFDRAcrossIT_RT_BR_PR(ii)
                text(ax, ...
                    plotData.betaPop_logHazard(ii) + starOffset, ...
                    popY(ii), ...
                    '*', ...
                    'Color', popColor, ...
                    'FontSize', 14, ...
                    'FontWeight', 'bold', ...
                    'HorizontalAlignment', 'left', ...
                    'VerticalAlignment', 'middle');
            end

        end

        ax.YTick = 1:nAreas;

        areaTickLabels = strings(nAreas, 1);
        for ii = 1:nAreas
            areaTickLabels(ii) = sprintf( ...
                '%s  |  IED: %d  |  covered: %d', ...
                char(plotData.anatomicalArea(ii)), ...
                plotData.nParticipantsWithIED(ii), ...
                plotData.nParticipantsWithCoverage(ii));
        end

        ax.YTickLabel = cellstr(areaTickLabels);
        ax.YLim = [0.4, nAreas + 0.6];
        ax.XLim = [ ...
            minimumX - leftPadding, ...
            maximumX + rightPadding];

        legend(ax, [bankPoint, popPoint], ...
            {'bank hazard', 'pop hazard'}, ...
            'Location', 'best', ...
            'Box', 'off');
    end

    ax.TickLabelInterpreter = 'none';
    ax.TickDir = 'out';
    ax.FontSize = 9;

    xlabel(ax, ...
        'Log hazard ratio: post-IED window versus outside window');

    title(ax, { ...
        'Bank and pop competing transitions', ...
        sprintf('BR - %d-ms post-IED window', ...
            postIEDWindowMilliseconds), ...
        'Both coefficients come from one combined Cox model', ...
        'Permutation BH-FDR across IT/RT/BR/PR within area', ...
        '* = q < 0.05'}, ...
        'FontSize', 12, ...
        'FontWeight', 'bold');

    box(ax, 'off');
    grid(ax, 'off');

end

function plotRows = getCompetingForestPlotRows(areaResults)

    anySignificantEffect = ...
        areaResults.significantBankFDRAcrossIT_RT_BR_PR | ...
        areaResults.significantPopFDRAcrossIT_RT_BR_PR;

    plotRows = ...
        ~isExcludedAreaLabel(areaResults.anatomicalArea) & ...
        areaResults.status == "fitted" & ...
        anySignificantEffect & ...
        isfinite(areaResults.beta_logHazard) & ...
        isfinite(areaResults.betaCILow) & ...
        isfinite(areaResults.betaCIHigh) & ...
        isfinite(areaResults.betaPop_logHazard) & ...
        isfinite(areaResults.betaPopCILow) & ...
        isfinite(areaResults.betaPopCIHigh);

end

function plotRows = getForestPlotRows(areaResults)

    plotRows = ...
        ~isExcludedAreaLabel(areaResults.anatomicalArea) & ...
        areaResults.status == "fitted" & ...
        areaResults.significantFDRAcrossIT_RT_BR_PR & ...
        isfinite(areaResults.beta_logHazard) & ...
        isfinite(areaResults.betaCILow) & ...
        isfinite(areaResults.betaCIHigh);

end
