% Participant-stratified Cox models comparing left- and right-hemisphere
% IED occurrence x expected reward interactions
%
% Both hemisphere-specific post-IED indicators and both interactions with
% expected reward are entered together in the same Cox model. Therefore,
% left effects are adjusted for right effects and vice versa. The primary
% direct comparison is beta(left IED x reward) - beta(right IED x reward).
%
% Hemisphere is read from LFPIED.anatomicalLocs_wHemisphere. Labels are
% expected to end in _L or _R (for example, area_L and area_R).
%
% Author: Nill

clear;
clc;
close all;

inputFolderName_LFPIED = ...
    'D:\Nill\data\BART\0_0_new_IED_new_area_labels\IED1_find_number_of_IEDs\';

modelFolderName = ...
    'D:\Nill\data\BART\0_0_new_IED_new_area_labels\context_modeling\param_recovery_1_modeling\';

outputFolderName = ...
    'D:\Nill\code\BART\IED\0_0_new_IED_new_area_labels\IED8_3_Cox_expected_reward_occurrence_LR_hemi\';

if ~exist(outputFolderName, 'dir')
    mkdir(outputFolderName);
end

samplingFrequency = 1000;
maximumRT = 20;
numberOfPermutations = 1000;
randomSeed = 42;

colorIT = [0.847 0.333 0.153];
colorRT = [0.204 0.459 0.702];
colorBR = [0.250 0.600 0.250];
colorPR = [0.494 0.184 0.556];

leftColor = [0.121 0.466 0.705];
rightColor = [0.839 0.153 0.157];

configs(1).code = 'IT';
configs(1).durationField = 'ITs';
configs(1).iedField = 'IED_occurance_IT';
configs(1).bankedOnly = false;
configs(1).poppedOnly = false;
configs(1).windowMilliseconds = 1000;
configs(1).color = colorIT;
configs(1).hazardName = 'action';

configs(2).code = 'RT';
configs(2).durationField = 'RTs';
configs(2).iedField = 'IED_occurance_RT';
configs(2).bankedOnly = false;
configs(2).poppedOnly = false;
configs(2).windowMilliseconds = 500;
configs(2).color = colorRT;
configs(2).hazardName = 'response';

configs(3).code = 'BR';
configs(3).durationField = 'ITs';
configs(3).iedField = 'IED_occurance_IT';
configs(3).bankedOnly = true;
configs(3).poppedOnly = false;
configs(3).windowMilliseconds = 1000;
configs(3).color = colorBR;
configs(3).hazardName = 'banking';

configs(4).code = 'PR';
configs(4).durationField = 'ITs';
configs(4).iedField = 'IED_occurance_IT';
configs(4).bankedOnly = false;
configs(4).poppedOnly = true;
configs(4).windowMilliseconds = 1000;
configs(4).color = colorPR;
configs(4).hazardName = 'popping';

%% Run IT, RT, BR, and PR

results = cell(length(configs), 1);

for analysisIndex = 1:length(configs)
    fprintf('\n\nRUNNING %s EXPECTED-REWARD HEMISPHERE ANALYSIS\n', ...
        configs(analysisIndex).code);

    results{analysisIndex} = runHemisphereExpectedRewardCoxAnalysis( ...
        inputFolderName_LFPIED, modelFolderName, configs(analysisIndex), ...
        samplingFrequency, maximumRT, numberOfPermutations, ...
        randomSeed + analysisIndex - 1);
end

%% Save compact results tables

hemisphereResultsAll = table();
contrastResultsAll = table();

for analysisIndex = 1:length(configs)
    thisHemisphereTable = results{analysisIndex}.hemisphereResults;
    thisHemisphereTable.outcome = repmat( ...
        string(configs(analysisIndex).code), ...
        height(thisHemisphereTable), 1);
    thisHemisphereTable = movevars( ...
        thisHemisphereTable, 'outcome', 'Before', 1);
    hemisphereResultsAll = [hemisphereResultsAll; thisHemisphereTable];

    thisContrastTable = results{analysisIndex}.contrastResults;
    thisContrastTable.outcome = string(configs(analysisIndex).code);
    thisContrastTable = movevars( ...
        thisContrastTable, 'outcome', 'Before', 1);
    contrastResultsAll = [contrastResultsAll; thisContrastTable];
end

writetable(hemisphereResultsAll, fullfile(outputFolderName, ...
    'IT_RT_BR_PR_expected_reward_left_right_hemisphere_results.csv'));

writetable(contrastResultsAll, fullfile(outputFolderName, ...
    'IT_RT_BR_PR_expected_reward_left_minus_right_contrasts.csv'));

%% Left/right visualization

combinedFigure = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [80 40 1500 1900]);

layout = tiledlayout(combinedFigure, 4, 2, ...
    'Padding', 'compact', 'TileSpacing', 'compact');

sgtitle(layout, [ ...
    'Left versus right hemisphere IED x expected reward: ' ...
    'RT 500-ms; IT, BR, and PR 1000-ms windows'], ...
    'FontName', 'Arial', 'FontSize', 16, 'FontWeight', 'bold');

for analysisIndex = 1:length(configs)
    plotHemisphereExpectedRewardForest(nexttile(layout), ...
        results{analysisIndex}, configs(analysisIndex), ...
        leftColor, rightColor);

    plotHemisphereExpectedRewardCurves(nexttile(layout), ...
        results{analysisIndex}, configs(analysisIndex), ...
        leftColor, rightColor);
end

combinedPDFOutputFile = fullfile(outputFolderName, ...
    'IT_RT_BR_PR_expected_reward_left_right_comparison_4x2.pdf');

exportgraphics(combinedFigure, combinedPDFOutputFile, ...
    'ContentType', 'vector');
close(combinedFigure);

fprintf('\nDone.\n');
fprintf('Hemisphere results CSV:\n%s\n', fullfile(outputFolderName, ...
    'IT_RT_BR_PR_expected_reward_left_right_hemisphere_results.csv'));
fprintf('Left-minus-right contrast CSV:\n%s\n', fullfile(outputFolderName, ...
    'IT_RT_BR_PR_expected_reward_left_minus_right_contrasts.csv'));
fprintf('Comparison PDF:\n%s\n', combinedPDFOutputFile);


%% Cox analysis for one outcome

function result = runHemisphereExpectedRewardCoxAnalysis( ...
    inputFolder, modelFolder, config, ...
    defaultSamplingFrequency, maximumRT, numberOfPermutations, randomSeed)

    code = config.code;
    windowMilliseconds = config.windowMilliseconds;
    windowSeconds = windowMilliseconds / 1000;

    fileList = dir(fullfile(inputFolder, '*.LFPIED.mat'));
    modelFiles = dir(fullfile(modelFolder, '*TDdataParamRecovery.mat'));

    if isempty(fileList)
        error('No .LFPIED.mat files were found in %s.', inputFolder);
    end

    countingProcessData = table();
    trialSummary = table();
    permutationTrialData = table();

    coverageLeftPatients = strings(0, 1);
    coverageRightPatients = strings(0, 1);
    IEDLeftPatients = strings(0, 1);
    IEDRightPatients = strings(0, 1);
    totalLeftIEDs = 0;
    totalRightIEDs = 0;

    for pt = 1:length(fileList)

        fileName = fileList(pt).name;
        fileParts = strsplit(fileName, '.');
        patientID = string(fileParts{1});
        fprintf('%s: processing patient %s\n', code, char(patientID));

        loadedData = load(fullfile(inputFolder, fileName));

        if ~isfield(loadedData, 'LFPIED')
            fprintf('Skipped %s: LFPIED structure was not found.\n', ...
                char(patientID));
            continue;
        end

        LFPIED = loadedData.LFPIED;

        modelFile = findModelFile(modelFiles, patientID);

        if strlength(modelFile) == 0
            fprintf('Skipped %s: no expected-reward file.\n', ...
                char(patientID));
            continue;
        end

        modelData = load(fullfile(modelFolder, modelFile));

        if ~isfield(modelData, 'TDdataParamRecovery') || ...
                ~isfield(modelData.TDdataParamRecovery, 'bestApIdx') || ...
                ~isfield(modelData.TDdataParamRecovery, 'bestAnIdx') || ...
                ~isfield(modelData.TDdataParamRecovery, 'expectedReward')
            fprintf(['Skipped %s: bestApIdx, bestAnIdx, or ' ...
                'expectedReward was missing.\n'], char(patientID));
            continue;
        end

        TD = modelData.TDdataParamRecovery;
        expectedRewards = squeeze(TD.expectedReward( ...
            round(TD.bestApIdx), round(TD.bestAnIdx), :));
        expectedRewards = double(expectedRewards(:));

        requiredFields = { ...
            'RTs', config.durationField, config.iedField, ...
            'isControl', 'balloonType', 'selectedChans', ...
            'anatomicalLocs_wHemisphere'};

        if config.bankedOnly || config.poppedOnly
            requiredFields{end + 1} = 'BankedTrials';
        end

        missingFields = requiredFields( ...
            ~cellfun(@(fieldName) isfield(LFPIED, fieldName), ...
            requiredFields));

        if ~isempty(missingFields)
            fprintf('Skipped %s: missing %s.\n', char(patientID), ...
                strjoin(missingFields, ', '));
            continue;
        end

        selectedChans = round(double(LFPIED.selectedChans(:)));
        selectedChans = selectedChans( ...
            isfinite(selectedChans) & selectedChans >= 1);
        nSelectedChannels = length(selectedChans);

        if nSelectedChannels == 0
            fprintf('Skipped %s: no selected channels.\n', ...
                char(patientID));
            continue;
        end

        selectedLabels = getSelectedChannelLabels( ...
            LFPIED.anatomicalLocs_wHemisphere, ...
            selectedChans, nSelectedChannels);

        [leftChannelMask, rightChannelMask] = ...
            getHemisphereChannelMasks(selectedLabels);

        leftLocalChannels = find(leftChannelMask);
        rightLocalChannels = find(rightChannelMask);

        if ~isempty(leftLocalChannels)
            coverageLeftPatients(end + 1, 1) = patientID;
        end

        if ~isempty(rightLocalChannels)
            coverageRightPatients(end + 1, 1) = patientID;
        end

        if isempty(leftLocalChannels) && isempty(rightLocalChannels)
            fprintf(['Skipped %s: none of the selected labels ended ' ...
                'in _L or _R.\n'], char(patientID));
            continue;
        end

        RTs = double(LFPIED.RTs(:));
        durations = double(LFPIED.(config.durationField));
        durations = durations(:);
        isControl = double(LFPIED.isControl(:));
        balloonColor = round(double(LFPIED.balloonType(:)));
        balloonColor = mod(balloonColor - 1, 10) + 1;
        IEDoccurrence = double(LFPIED.(config.iedField));

        samplingFrequency = defaultSamplingFrequency;
        if isfield(LFPIED, 'Fs') && isscalar(LFPIED.Fs) && ...
                isfinite(LFPIED.Fs) && LFPIED.Fs > 0
            samplingFrequency = double(LFPIED.Fs);
        end

        if isempty(IEDoccurrence)
            IEDoccurrence = zeros(0, 3);
        elseif size(IEDoccurrence, 2) < 3
            fprintf(['Skipped %s: %s must contain at least trial, ' ...
                'channel, and IED-time columns.\n'], ...
                char(patientID), config.iedField);
            continue;
        end

        vectorLengths = [length(RTs), length(durations), ...
            length(isControl), length(balloonColor), ...
            length(expectedRewards)];

        if config.bankedOnly || config.poppedOnly
            bankedTrials = double(LFPIED.BankedTrials(:));
            vectorLengths(end + 1) = length(bankedTrials);
        else
            bankedTrials = NaN(length(durations), 1);
        end

        nTrials = min(vectorLengths);
        RTs = RTs(1:nTrials);
        durations = durations(1:nTrials);
        isControl = isControl(1:nTrials);
        balloonColor = balloonColor(1:nTrials);
        bankedTrials = bankedTrials(1:nTrials);
        expectedRewards = expectedRewards(1:nTrials);

        patientHasLeftIED = false;
        patientHasRightIED = false;

        for trial = 1:nTrials

            duration = durations(trial);

            keepTrial = isControl(trial) == 0 && ...
                RTs(trial) > 0 && RTs(trial) <= maximumRT && ...
                isfinite(duration) && duration > 0 && ...
                isfinite(expectedRewards(trial)) && ...
                ismember(balloonColor(trial), [1 2 3]);

            if config.bankedOnly || config.poppedOnly
                keepTrial = keepTrial && ...
                    ismember(bankedTrials(trial), [0 1]);

                if config.bankedOnly
                    eventObserved = bankedTrials(trial) == 1;
                else
                    eventObserved = bankedTrials(trial) == 0;
                end
            else
                eventObserved = true;
            end

            if ~keepTrial
                continue;
            end

            trialRows = isfinite(IEDoccurrence(:, 1)) & ...
                round(IEDoccurrence(:, 1)) == trial;

            leftRows = trialRows & ...
                isfinite(IEDoccurrence(:, 2)) & ...
                ismember(round(IEDoccurrence(:, 2)), leftLocalChannels);

            rightRows = trialRows & ...
                isfinite(IEDoccurrence(:, 2)) & ...
                ismember(round(IEDoccurrence(:, 2)), rightLocalChannels);

            leftIEDtimes = getValidIEDTimes( ...
                IEDoccurrence(leftRows, :), ...
                duration, samplingFrequency);

            rightIEDtimes = getValidIEDTimes( ...
                IEDoccurrence(rightRows, :), ...
                duration, samplingFrequency);

            totalLeftIEDs = totalLeftIEDs + length(leftIEDtimes);
            totalRightIEDs = totalRightIEDs + length(rightIEDtimes);
            patientHasLeftIED = patientHasLeftIED || ~isempty(leftIEDtimes);
            patientHasRightIED = patientHasRightIED || ~isempty(rightIEDtimes);

            [tStart, tStop, postIEDLeft, postIEDRight, ...
                activeLeftWindowCount, activeRightWindowCount] = ...
                buildHemisphereIntervals(duration, leftIEDtimes, ...
                rightIEDtimes, windowSeconds);

            nRows = length(tStart);
            censored = true(nRows, 1);
            eventAtStop = false(nRows, 1);

            if eventObserved
                censored(end) = false;
                eventAtStop(end) = true;
            end

            currentRows = table( ...
                repmat(patientID, nRows, 1), ...
                repmat(trial, nRows, 1), ...
                tStart, tStop, censored, eventAtStop, ...
                postIEDLeft, postIEDRight, ...
                activeLeftWindowCount, activeRightWindowCount, ...
                repmat(balloonColor(trial), nRows, 1), ...
                repmat(expectedRewards(trial), nRows, 1), ...
                repmat(samplingFrequency, nRows, 1), ...
                'VariableNames', { ...
                'patientID', 'trialNumber', 'tStart', 'tStop', ...
                'censored', 'eventAtStop', ...
                'postIEDLeft', 'postIEDRight', ...
                'activeLeftIEDWindowCount', ...
                'activeRightIEDWindowCount', ...
                'balloonColorCode', 'expectedReward', ...
                'samplingFrequencyHz'});

            countingProcessData = [countingProcessData; currentRows];

            rowDuration = tStop - tStart;
            currentSummary = table( ...
                patientID, trial, duration, expectedRewards(trial), ...
                double(eventObserved), ...
                length(leftIEDtimes), length(rightIEDtimes), ...
                sum(rowDuration .* postIEDLeft), ...
                sum(rowDuration .* postIEDRight), ...
                double(eventObserved && postIEDLeft(end) == 1), ...
                double(eventObserved && postIEDRight(end) == 1), ...
                balloonColor(trial), samplingFrequency, ...
                'VariableNames', { ...
                'patientID', 'trialNumber', 'durationSeconds', ...
                'expectedReward', 'eventObserved', ...
                'nLeftIEDs', 'nRightIEDs', ...
                'leftPostIEDExposureSeconds', ...
                'rightPostIEDExposureSeconds', ...
                'eventInLeftPostIEDWindow', ...
                'eventInRightPostIEDWindow', ...
                'balloonColorCode', 'samplingFrequencyHz'});

            trialSummary = [trialSummary; currentSummary];

            currentPermutationTrial = table( ...
                patientID, trial, duration, double(eventObserved), ...
                balloonColor(trial), expectedRewards(trial), ...
                {leftIEDtimes}, {rightIEDtimes}, ...
                'VariableNames', { ...
                'patientID', 'trialNumber', 'durationSeconds', ...
                'eventObserved', 'balloonColorCode', 'expectedReward', ...
                'leftIEDtimes_seconds', 'rightIEDtimes_seconds'});

            permutationTrialData = ...
                [permutationTrialData; currentPermutationTrial];
        end

        if patientHasLeftIED
            IEDLeftPatients(end + 1, 1) = patientID;
        end

        if patientHasRightIED
            IEDRightPatients(end + 1, 1) = patientID;
        end
    end

    if isempty(countingProcessData)
        error('%s: no valid counting-process data were created.', code);
    end

    if ~any(countingProcessData.postIEDLeft == 1)
        error('%s: no valid left-hemisphere post-IED exposure.', code);
    end

    if ~any(countingProcessData.postIEDRight == 1)
        error('%s: no valid right-hemisphere post-IED exposure.', code);
    end

    [countingProcessData.patientStratum, patientLevels] = ...
        findgroups(countingProcessData.patientID);

    permutationTrialData.patientStratum = ...
        findgroups(permutationTrialData.patientID);

    leftIED = double(countingProcessData.postIEDLeft);
    rightIED = double(countingProcessData.postIEDRight);
    expectedReward = double(countingProcessData.expectedReward);

    X = [ ...
        leftIED, rightIED, expectedReward, ...
        double(countingProcessData.balloonColorCode == 2), ...
        double(countingProcessData.balloonColorCode == 3), ...
        leftIED .* expectedReward, ...
        rightIED .* expectedReward];

    predictorNames = [ ...
        "left_post_ied_indicator"; ...
        "right_post_ied_indicator"; ...
        "expected_reward"; ...
        "orange_vs_yellow"; ...
        "red_vs_yellow"; ...
        "left_post_ied_x_expected_reward"; ...
        "right_post_ied_x_expected_reward"];

    leftIndex = 1;
    rightIndex = 2;
    rewardIndex = 3;
    leftInteractionIndex = 6;
    rightInteractionIndex = 7;

    T = [countingProcessData.tStart, countingProcessData.tStop];
    censoring = countingProcessData.censored;
    strata = countingProcessData.patientStratum;

    options = statset('coxphfit');
    options.Display = 'final';
    options.MaxIter = 1000;
    options.MaxFunEvals = 5000;

    [beta, logLikelihood, baselineCumulativeHazard, stats] = ...
        coxphfit(X, T, ...
        'Censoring', censoring, ...
        'Strata', strata, ...
        'Ties', 'efron', ...
        'Baseline', 0, ...
        'Options', options);

    patientNumbers = unique(strata);
    clusterScores = zeros(length(patientNumbers), length(beta));

    for patientIndex = 1:length(patientNumbers)
        clusterScores(patientIndex, :) = sum( ...
            stats.scores(strata == patientNumbers(patientIndex), :), 1);
    end

    robustCovariance = stats.covb * ...
        (clusterScores' * clusterScores) * stats.covb;

    if length(patientNumbers) > 1
        robustCovariance = robustCovariance * ...
            length(patientNumbers) / (length(patientNumbers) - 1);
    end

    robustSE = sqrt(max(diag(robustCovariance), 0));
    betaLow = beta - 1.96 * robustSE;
    betaHigh = beta + 1.96 * robustSE;
    hazardRatio = exp(beta);
    hazardRatioLow = exp(betaLow);
    hazardRatioHigh = exp(betaHigh);

    mainContrastVector = zeros(length(beta), 1);
    mainContrastVector(leftIndex) = 1;
    mainContrastVector(rightIndex) = -1;

    interactionContrastVector = zeros(length(beta), 1);
    interactionContrastVector(leftInteractionIndex) = 1;
    interactionContrastVector(rightInteractionIndex) = -1;

    mainContrast = summarizeLinearContrast( ...
        beta, robustCovariance, mainContrastVector);
    interactionContrast = summarizeLinearContrast( ...
        beta, robustCovariance, interactionContrastVector);

    %% Within-participant, within-color trial permutation test

    permutationLeftMainBeta = NaN(numberOfPermutations, 1);
    permutationRightMainBeta = NaN(numberOfPermutations, 1);
    permutationLeftInteractionBeta = NaN(numberOfPermutations, 1);
    permutationRightInteractionBeta = NaN(numberOfPermutations, 1);
    permutationMainContrast = NaN(numberOfPermutations, 1);
    permutationInteractionContrast = NaN(numberOfPermutations, 1);
    permutationSucceeded = false(numberOfPermutations, 1);

    permutationGroups = findgroups( ...
        permutationTrialData.patientID, ...
        permutationTrialData.balloonColorCode);

    rng(randomSeed);
    permutationOptions = options;
    permutationOptions.Display = 'off';

    fprintf('%s: running %d permutations...\n', ...
        code, numberOfPermutations);

    for permutation = 1:numberOfPermutations
        shuffledTrials = permutationTrialData;

        for group = 1:max(permutationGroups)
            groupRows = find(permutationGroups == group);
            sourceRows = groupRows(randperm(length(groupRows)));

            shuffledTrials.durationSeconds(groupRows) = ...
                permutationTrialData.durationSeconds(sourceRows);
            shuffledTrials.eventObserved(groupRows) = ...
                permutationTrialData.eventObserved(sourceRows);
            shuffledTrials.expectedReward(groupRows) = ...
                permutationTrialData.expectedReward(sourceRows);
        end

        [permutedX, permutedT, permutedCensoring, permutedStrata] = ...
            buildShuffledHemisphereCoxData( ...
            shuffledTrials, windowSeconds);

        try
            permutationBeta = coxphfit( ...
                permutedX, permutedT, ...
                'Censoring', permutedCensoring, ...
                'Strata', permutedStrata, ...
                'Ties', 'efron', ...
                'Baseline', 0, ...
                'Options', permutationOptions);

            permutationLeftMainBeta(permutation) = ...
                permutationBeta(leftIndex);
            permutationRightMainBeta(permutation) = ...
                permutationBeta(rightIndex);
            permutationLeftInteractionBeta(permutation) = ...
                permutationBeta(leftInteractionIndex);
            permutationRightInteractionBeta(permutation) = ...
                permutationBeta(rightInteractionIndex);
            permutationMainContrast(permutation) = ...
                permutationBeta(leftIndex) - permutationBeta(rightIndex);
            permutationInteractionContrast(permutation) = ...
                permutationBeta(leftInteractionIndex) - ...
                permutationBeta(rightInteractionIndex);
            permutationSucceeded(permutation) = true;
        catch permutationError
            fprintf('%s permutation %d failed: %s\n', ...
                code, permutation, permutationError.message);
        end

        if mod(permutation, 100) == 0 || ...
                permutation == numberOfPermutations
            fprintf('%s permutation progress: %d/%d\n', ...
                code, permutation, numberOfPermutations);
        end
    end

    validRows = permutationSucceeded;
    permutationPLeftMain = calculatePermutationP( ...
        permutationLeftMainBeta(validRows), beta(leftIndex));
    permutationPRightMain = calculatePermutationP( ...
        permutationRightMainBeta(validRows), beta(rightIndex));
    permutationPLeftInteraction = calculatePermutationP( ...
        permutationLeftInteractionBeta(validRows), ...
        beta(leftInteractionIndex));
    permutationPRightInteraction = calculatePermutationP( ...
        permutationRightInteractionBeta(validRows), ...
        beta(rightInteractionIndex));

    % These two outcome-shuffle contrast values are global-null sensitivity
    % measures. The formal left = right tests are the clustered Wald p-values.
    permutationPMainContrast = calculatePermutationP( ...
        permutationMainContrast(validRows), mainContrast.beta);
    permutationPInteractionContrast = calculatePermutationP( ...
        permutationInteractionContrast(validRows), ...
        interactionContrast.beta);

    permutationPAll = NaN(length(beta), 1);
    permutationPAll(leftIndex) = permutationPLeftMain;
    permutationPAll(rightIndex) = permutationPRightMain;
    permutationPAll(leftInteractionIndex) = ...
        permutationPLeftInteraction;
    permutationPAll(rightInteractionIndex) = ...
        permutationPRightInteraction;

    coxResults = table( ...
        predictorNames, beta(:), stats.se(:), stats.z(:), stats.p(:), ...
        robustSE(:), permutationPAll, betaLow(:), betaHigh(:), ...
        hazardRatio(:), hazardRatioLow(:), hazardRatioHigh(:), ...
        'VariableNames', { ...
        'predictor', 'beta_logHazard', 'modelBasedSE', ...
        'modelBasedZ', 'modelBasedPValue', 'clusterRobustSE', ...
        'permutationPValue', 'betaCILow', 'betaCIHigh', ...
        'hazardRatio', 'hazardRatioCILow', 'hazardRatioCIHigh'});

    nCoverage = [ ...
        length(unique(coverageLeftPatients)); ...
        length(unique(coverageRightPatients))];
    nWithIED = [ ...
        length(unique(IEDLeftPatients)); ...
        length(unique(IEDRightPatients))];
    nIEDs = [totalLeftIEDs; totalRightIEDs];

    hemisphereResults = table( ...
        ["Left"; "Right"], ...
        beta([leftIndex; rightIndex]), ...
        robustSE([leftIndex; rightIndex]), ...
        stats.p([leftIndex; rightIndex]), ...
        [permutationPLeftMain; permutationPRightMain], ...
        betaLow([leftIndex; rightIndex]), ...
        betaHigh([leftIndex; rightIndex]), ...
        hazardRatio([leftIndex; rightIndex]), ...
        hazardRatioLow([leftIndex; rightIndex]), ...
        hazardRatioHigh([leftIndex; rightIndex]), ...
        beta([leftInteractionIndex; rightInteractionIndex]), ...
        robustSE([leftInteractionIndex; rightInteractionIndex]), ...
        stats.p([leftInteractionIndex; rightInteractionIndex]), ...
        [permutationPLeftInteraction; permutationPRightInteraction], ...
        betaLow([leftInteractionIndex; rightInteractionIndex]), ...
        betaHigh([leftInteractionIndex; rightInteractionIndex]), ...
        hazardRatio([leftInteractionIndex; rightInteractionIndex]), ...
        hazardRatioLow([leftInteractionIndex; rightInteractionIndex]), ...
        hazardRatioHigh([leftInteractionIndex; rightInteractionIndex]), ...
        nCoverage, nWithIED, nIEDs, ...
        'VariableNames', { ...
        'hemisphere', ...
        'beta_IED', 'clusterRobustSE_IED', ...
        'modelBasedPValue_IED', 'permutationPValue_IED', ...
        'betaCILow_IED', 'betaCIHigh_IED', ...
        'hazardRatio_IED', 'hazardRatioCILow_IED', ...
        'hazardRatioCIHigh_IED', ...
        'beta_IEDxExpectedReward', ...
        'clusterRobustSE_IEDxExpectedReward', ...
        'modelBasedPValue_IEDxExpectedReward', ...
        'permutationPValue_IEDxExpectedReward', ...
        'betaCILow_IEDxExpectedReward', ...
        'betaCIHigh_IEDxExpectedReward', ...
        'hazardRatio_IEDxExpectedReward', ...
        'hazardRatioCILow_IEDxExpectedReward', ...
        'hazardRatioCIHigh_IEDxExpectedReward', ...
        'nParticipantsWithCoverage', ...
        'nParticipantsWithIED', 'nIEDs'});

    contrastResults = table( ...
        mainContrast.beta, mainContrast.se, mainContrast.z, ...
        mainContrast.p, permutationPMainContrast, ...
        mainContrast.betaLow, mainContrast.betaHigh, ...
        mainContrast.hr, mainContrast.hrLow, mainContrast.hrHigh, ...
        interactionContrast.beta, interactionContrast.se, ...
        interactionContrast.z, interactionContrast.p, ...
        permutationPInteractionContrast, ...
        interactionContrast.betaLow, interactionContrast.betaHigh, ...
        interactionContrast.hr, interactionContrast.hrLow, ...
        interactionContrast.hrHigh, sum(validRows), ...
        'VariableNames', { ...
        'betaLeftMinusRight_IED', 'clusterRobustSE_IED', ...
        'clusterRobustZ_IED', 'clusterRobustPValue_IED', ...
        'outcomeShufflePermutationPValue_IED', ...
        'betaCILow_IED', 'betaCIHigh_IED', ...
        'hazardRatioLeftDividedByRight_IED', ...
        'hazardRatioRatioCILow_IED', ...
        'hazardRatioRatioCIHigh_IED', ...
        'betaLeftMinusRight_IEDxExpectedReward', ...
        'clusterRobustSE_IEDxExpectedReward', ...
        'clusterRobustZ_IEDxExpectedReward', ...
        'clusterRobustPValue_IEDxExpectedReward', ...
        'outcomeShufflePermutationPValue_IEDxExpectedReward', ...
        'betaCILow_IEDxExpectedReward', ...
        'betaCIHigh_IEDxExpectedReward', ...
        'hazardRatioLeftDividedByRight_IEDxExpectedReward', ...
        'hazardRatioRatioCILow_IEDxExpectedReward', ...
        'hazardRatioRatioCIHigh_IEDxExpectedReward', ...
        'nValidPermutations'});

    permutationResults = table( ...
        (1:numberOfPermutations)', ...
        permutationLeftMainBeta, permutationRightMainBeta, ...
        permutationLeftInteractionBeta, ...
        permutationRightInteractionBeta, ...
        permutationMainContrast, permutationInteractionContrast, ...
        permutationSucceeded, ...
        'VariableNames', { ...
        'permutationIndex', 'permutedLeftIEDBeta', ...
        'permutedRightIEDBeta', ...
        'permutedLeftIEDxExpectedRewardBeta', ...
        'permutedRightIEDxExpectedRewardBeta', ...
        'permutedLeftMinusRightIEDBeta', ...
        'permutedLeftMinusRightInteractionBeta', ...
        'fitSucceeded'});

    modelEffectTable = makeHemisphereExpectedRewardCurves( ...
        beta, robustCovariance, predictorNames, ...
        trialSummary.expectedReward);

    expectedRewardSlopeOutsideIED = beta(rewardIndex);
    expectedRewardSlopeLeftIED = ...
        beta(rewardIndex) + beta(leftInteractionIndex);
    expectedRewardSlopeRightIED = ...
        beta(rewardIndex) + beta(rightInteractionIndex);

    fprintf('\n%s: %d-ms left/right IED x expected-reward Cox model\n', ...
        code, windowMilliseconds);
    fprintf('Participants analyzed: %d\n', length(patientLevels));
    fprintf('Trials: %d\n', height(trialSummary));
    fprintf('Left coverage / with IED / IEDs: %d / %d / %d\n', ...
        nCoverage(1), nWithIED(1), nIEDs(1));
    fprintf('Right coverage / with IED / IEDs: %d / %d / %d\n', ...
        nCoverage(2), nWithIED(2), nIEDs(2));
    fprintf('Log likelihood: %.6f\n', logLikelihood);
    fprintf(['Left-right interaction contrast: beta = %.6f, ' ...
        'clustered p = %.6g, outcome-shuffle p = %.6g\n'], ...
        interactionContrast.beta, interactionContrast.p, ...
        permutationPInteractionContrast);
    disp(coxResults);
    disp(hemisphereResults);
    disp(contrastResults);

    result.code = code;
    result.countingProcessData = countingProcessData;
    result.trialSummary = trialSummary;
    result.coxResults = coxResults;
    result.hemisphereResults = hemisphereResults;
    result.contrastResults = contrastResults;
    result.modelEffectTable = modelEffectTable;
    result.beta = beta;
    result.logLikelihood = logLikelihood;
    result.baselineCumulativeHazard = baselineCumulativeHazard;
    result.stats = stats;
    result.clusterRobustCovariance = robustCovariance;
    result.clusterRobustSE = robustSE;
    result.predictorNames = predictorNames;
    result.patientLevels = patientLevels;
    result.expectedRewardSlopeOutsideIED = ...
        expectedRewardSlopeOutsideIED;
    result.expectedRewardSlopeLeftIED = ...
        expectedRewardSlopeLeftIED;
    result.expectedRewardSlopeRightIED = ...
        expectedRewardSlopeRightIED;
    result.permutationResults = permutationResults;
    result.numberOfPermutations = numberOfPermutations;
    result.numberOfValidPermutations = sum(validRows);
    result.permutationRandomSeed = randomSeed;
end


%% Find one participant's expected-reward model file

function modelFile = findModelFile(modelFiles, patientID)

    names = string({modelFiles.name});
    matches = contains(lower(names), lower(patientID));

    if ~any(matches)
        modelFile = "";
    else
        matchingNames = names(matches);
        [~, shortestMatch] = min(strlength(matchingNames));
        modelFile = matchingNames(shortestMatch);
    end
end


%% Read labels for the selected channels

function labels = getSelectedChannelLabels( ...
    anatomicalLocs, selectedChans, nSelectedChannels)

    labels = convertLabelsToString(anatomicalLocs);
    labels = labels(:);

    if length(labels) >= max(selectedChans)
        labels = labels(selectedChans);
    elseif length(labels) == nSelectedChannels
        % anatomicalLocs_wHemisphere was already selected-channel restricted.
    else
        error(['Cannot map anatomicalLocs_wHemisphere to selected channels. ' ...
            'Labels = %d, selected channels = %d, maximum channel = %d.'], ...
            length(labels), nSelectedChannels, max(selectedChans));
    end
end


function labels = convertLabelsToString(rawLabels)

    if isstring(rawLabels)
        labels = rawLabels;
    elseif iscell(rawLabels)
        labels = strings(numel(rawLabels), 1);

        for labelIndex = 1:numel(rawLabels)
            value = rawLabels{labelIndex};

            if isempty(value)
                labels(labelIndex) = "";
            elseif iscell(value) && numel(value) == 1
                labels(labelIndex) = string(value{1});
            else
                labels(labelIndex) = string(value);
            end
        end
    elseif ischar(rawLabels)
        labels = string(cellstr(rawLabels));
    elseif iscategorical(rawLabels)
        labels = string(rawLabels);
    else
        labels = string(rawLabels);
    end

    labels = strip(labels(:));
end


%% Identify _L and _R channel labels

function [leftMask, rightMask] = getHemisphereChannelMasks(labels)

    labels = upper(strip(string(labels)));
    labels(ismissing(labels)) = "";

    % The requested format is area_L or area_R. Hyphen/space endings are
    % also accepted so that small atlas-format differences do not discard
    % otherwise valid labels.
    leftMask = ~cellfun('isempty', regexp(cellstr(labels), ...
        '[_\-\s]L$', 'once'));
    rightMask = ~cellfun('isempty', regexp(cellstr(labels), ...
        '[_\-\s]R$', 'once'));

    leftMask = leftMask(:);
    rightMask = rightMask(:);
end


%% Convert one hemisphere's IED rows to valid within-trial times

function IEDtimes = getValidIEDTimes( ...
    hemisphereIEDRows, duration, samplingFrequency)

    if isempty(hemisphereIEDRows) || size(hemisphereIEDRows, 2) < 3
        IEDtimes = zeros(0, 1);
        return;
    end

    IEDtimes = double(hemisphereIEDRows(:, 3)) / samplingFrequency;
    IEDtimes = IEDtimes( ...
        isfinite(IEDtimes) & IEDtimes > 0 & IEDtimes < duration);
    IEDtimes = sort(IEDtimes(:));
end


%% Build start-stop intervals using both hemispheres

function [tStart, tStop, postIEDLeft, postIEDRight, ...
    activeLeftWindowCount, activeRightWindowCount] = ...
    buildHemisphereIntervals(duration, leftIEDtimes, ...
    rightIEDtimes, windowSeconds)

    leftWindowEnds = min(leftIEDtimes + windowSeconds, duration);
    rightWindowEnds = min(rightIEDtimes + windowSeconds, duration);

    breakTimes = unique([ ...
        0; leftIEDtimes; leftWindowEnds; ...
        rightIEDtimes; rightWindowEnds; duration]);

    tStart = breakTimes(1:end-1);
    tStop = breakTimes(2:end);
    midpoint = (tStart + tStop) / 2;

    postIEDLeft = zeros(length(midpoint), 1);
    postIEDRight = zeros(length(midpoint), 1);
    activeLeftWindowCount = zeros(length(midpoint), 1);
    activeRightWindowCount = zeros(length(midpoint), 1);

    for IEDindex = 1:length(leftIEDtimes)
        insideWindow = midpoint >= leftIEDtimes(IEDindex) & ...
            midpoint <= leftIEDtimes(IEDindex) + windowSeconds;
        postIEDLeft(insideWindow) = 1;
        activeLeftWindowCount(insideWindow) = ...
            activeLeftWindowCount(insideWindow) + 1;
    end

    for IEDindex = 1:length(rightIEDtimes)
        insideWindow = midpoint >= rightIEDtimes(IEDindex) & ...
            midpoint <= rightIEDtimes(IEDindex) + windowSeconds;
        postIEDRight(insideWindow) = 1;
        activeRightWindowCount(insideWindow) = ...
            activeRightWindowCount(insideWindow) + 1;
    end
end


%% Rebuild Cox data after shuffling trial outcomes/durations/reward

function [X, T, censoring, strata] = ...
    buildShuffledHemisphereCoxData(trialData, windowSeconds)

    nTrials = height(trialData);
    Xcells = cell(nTrials, 1);
    Tcells = cell(nTrials, 1);
    censoringCells = cell(nTrials, 1);
    strataCells = cell(nTrials, 1);

    for trialIndex = 1:nTrials
        duration = trialData.durationSeconds(trialIndex);

        leftIEDtimes = trialData.leftIEDtimes_seconds{trialIndex};
        rightIEDtimes = trialData.rightIEDtimes_seconds{trialIndex};
        leftIEDtimes = leftIEDtimes(leftIEDtimes < duration);
        rightIEDtimes = rightIEDtimes(rightIEDtimes < duration);

        [tStart, tStop, postIEDLeft, postIEDRight] = ...
            buildHemisphereIntervals(duration, leftIEDtimes, ...
            rightIEDtimes, windowSeconds);

        color = trialData.balloonColorCode(trialIndex);
        reward = trialData.expectedReward(trialIndex);
        nRows = length(tStart);

        Xcells{trialIndex} = [ ...
            postIEDLeft, postIEDRight, ...
            repmat(reward, nRows, 1), ...
            repmat(double(color == 2), nRows, 1), ...
            repmat(double(color == 3), nRows, 1), ...
            postIEDLeft .* reward, ...
            postIEDRight .* reward];

        Tcells{trialIndex} = [tStart, tStop];

        trialCensoring = true(nRows, 1);
        if trialData.eventObserved(trialIndex) == 1
            trialCensoring(end) = false;
        end
        censoringCells{trialIndex} = trialCensoring;

        strataCells{trialIndex} = repmat( ...
            trialData.patientStratum(trialIndex), nRows, 1);
    end

    X = vertcat(Xcells{:});
    T = vertcat(Tcells{:});
    censoring = vertcat(censoringCells{:});
    strata = vertcat(strataCells{:});
end


function permutationP = calculatePermutationP( ...
    validPermutationStatistics, observedStatistic)

    if isempty(validPermutationStatistics)
        permutationP = NaN;
        return;
    end

    permutationP = (1 + sum( ...
        abs(validPermutationStatistics) >= abs(observedStatistic))) / ...
        (length(validPermutationStatistics) + 1);
end


%% Summarize a participant-clustered linear contrast

function summary = summarizeLinearContrast(beta, covariance, contrast)

    summary.beta = contrast' * beta;
    contrastVariance = contrast' * covariance * contrast;
    summary.se = sqrt(max(contrastVariance, 0));
    summary.z = summary.beta / summary.se;
    summary.p = 2 * normcdf(-abs(summary.z));
    summary.betaLow = summary.beta - 1.96 * summary.se;
    summary.betaHigh = summary.beta + 1.96 * summary.se;
    summary.hr = exp(summary.beta);
    summary.hrLow = exp(summary.betaLow);
    summary.hrHigh = exp(summary.betaHigh);
end


%% Expected-reward curves for outside, left, and right post-IED states

function effectTable = makeHemisphereExpectedRewardCurves( ...
    beta, covariance, predictorNames, observedReward)

    observedReward = observedReward(isfinite(observedReward));
    rewardGrid = linspace(min(observedReward), max(observedReward), 120)';
    referenceReward = mean(observedReward);

    leftIndex = find(predictorNames == ...
        "left_post_ied_indicator", 1);
    rightIndex = find(predictorNames == ...
        "right_post_ied_indicator", 1);
    rewardIndex = find(predictorNames == "expected_reward", 1);
    leftInteractionIndex = find(predictorNames == ...
        "left_post_ied_x_expected_reward", 1);
    rightInteractionIndex = find(predictorNames == ...
        "right_post_ied_x_expected_reward", 1);

    nGrid = length(rewardGrid);
    logOutside = zeros(nGrid, 1);
    logLeft = zeros(nGrid, 1);
    logRight = zeros(nGrid, 1);
    seOutside = zeros(nGrid, 1);
    seLeft = zeros(nGrid, 1);
    seRight = zeros(nGrid, 1);

    for rewardNumber = 1:nGrid
        rewardValue = rewardGrid(rewardNumber);

        outsideContrast = zeros(length(beta), 1);
        outsideContrast(rewardIndex) = ...
            rewardValue - referenceReward;

        leftContrast = outsideContrast;
        leftContrast(leftIndex) = 1;
        leftContrast(leftInteractionIndex) = rewardValue;

        rightContrast = outsideContrast;
        rightContrast(rightIndex) = 1;
        rightContrast(rightInteractionIndex) = rewardValue;

        logOutside(rewardNumber) = outsideContrast' * beta;
        logLeft(rewardNumber) = leftContrast' * beta;
        logRight(rewardNumber) = rightContrast' * beta;

        seOutside(rewardNumber) = sqrt(max( ...
            outsideContrast' * covariance * outsideContrast, 0));
        seLeft(rewardNumber) = sqrt(max( ...
            leftContrast' * covariance * leftContrast, 0));
        seRight(rewardNumber) = sqrt(max( ...
            rightContrast' * covariance * rightContrast, 0));
    end

    effectTable = table( ...
        rewardGrid, ...
        exp(logOutside), ...
        exp(logOutside - 1.96 * seOutside), ...
        exp(logOutside + 1.96 * seOutside), ...
        exp(logLeft), ...
        exp(logLeft - 1.96 * seLeft), ...
        exp(logLeft + 1.96 * seLeft), ...
        exp(logRight), ...
        exp(logRight - 1.96 * seRight), ...
        exp(logRight + 1.96 * seRight), ...
        repmat(referenceReward, nGrid, 1), ...
        'VariableNames', { ...
        'expectedReward', ...
        'relativeHazardOutsideIED', ...
        'relativeHazardOutsideIEDCILow', ...
        'relativeHazardOutsideIEDCIHigh', ...
        'relativeHazardLeftIED', ...
        'relativeHazardLeftIEDCILow', ...
        'relativeHazardLeftIEDCIHigh', ...
        'relativeHazardRightIED', ...
        'relativeHazardRightIEDCILow', ...
        'relativeHazardRightIEDCIHigh', ...
        'referenceExpectedReward'});
end


%% Paired left/right main and interaction coefficients

function plotHemisphereExpectedRewardForest(ax, result, config, ...
    leftColor, rightColor)

    plotData = result.hemisphereResults;
    contrast = result.contrastResults;

    betaValues = [ ...
        plotData.beta_IED(1); ...
        plotData.beta_IED(2); ...
        plotData.beta_IEDxExpectedReward(1); ...
        plotData.beta_IEDxExpectedReward(2)];

    lowValues = [ ...
        plotData.betaCILow_IED(1); ...
        plotData.betaCILow_IED(2); ...
        plotData.betaCILow_IEDxExpectedReward(1); ...
        plotData.betaCILow_IEDxExpectedReward(2)];

    highValues = [ ...
        plotData.betaCIHigh_IED(1); ...
        plotData.betaCIHigh_IED(2); ...
        plotData.betaCIHigh_IEDxExpectedReward(1); ...
        plotData.betaCIHigh_IEDxExpectedReward(2)];

    permutationPValues = [ ...
        plotData.permutationPValue_IED(1); ...
        plotData.permutationPValue_IED(2); ...
        plotData.permutationPValue_IEDxExpectedReward(1); ...
        plotData.permutationPValue_IEDxExpectedReward(2)];

    y = (1:4)';
    colors = [leftColor; rightColor; leftColor; rightColor];
    markers = {'o', 'o', 's', 's'};

    hold(ax, 'on');

    for row = 1:4
        errorbar(ax, betaValues(row), y(row), ...
            betaValues(row) - lowValues(row), ...
            highValues(row) - betaValues(row), ...
            'horizontal', markers{row}, 'LineWidth', 1.6, ...
            'MarkerSize', 7, 'MarkerFaceColor', colors(row, :), ...
            'MarkerEdgeColor', colors(row, :), ...
            'Color', colors(row, :));
    end

    xline(ax, 0, '--', 'Color', [0.42 0.42 0.42]);

    labels = { ...
        'Left IED main effect (reward = 0)'; ...
        'Right IED main effect (reward = 0)'; ...
        'Left IED x expected reward'; ...
        'Right IED x expected reward'};

    set(ax, 'YTick', y, 'YTickLabel', labels, 'YDir', 'reverse', ...
        'FontName', 'Arial', 'FontSize', 9.5, ...
        'TickDir', 'out', 'TickLabelInterpreter', 'none');

    plotLimits = [lowValues; highValues; 0];
    plotLimits = plotLimits(isfinite(plotLimits));
    padding = max(0.10, 0.14 * (max(plotLimits) - min(plotLimits)));
    xlim(ax, [min(plotLimits) - padding, max(plotLimits) + padding]);
    ylim(ax, [0.5 4.5]);

    for row = 1:4
        if isfinite(permutationPValues(row)) && ...
                permutationPValues(row) < 0.05
            text(ax, highValues(row) + 0.03 * diff(xlim(ax)), row, '*', ...
                'FontSize', 15, 'FontWeight', 'bold');
        end
    end

    xlabel(ax, 'log-hazard coefficient with robust 95% CI');
    title(ax, sprintf('%s: left/right mechanistic estimates', ...
        config.code), 'FontWeight', 'bold');

    resultText = sprintf([ ...
        'Interaction difference (L - R) = %.3f\n' ...
        'robust p = %.3g\noutcome-shuffle p = %.3g'], ...
        contrast.betaLeftMinusRight_IEDxExpectedReward, ...
        contrast.clusterRobustPValue_IEDxExpectedReward, ...
        contrast.outcomeShufflePermutationPValue_IEDxExpectedReward);

    text(ax, 0.98, 0.04, resultText, 'Units', 'normalized', ...
        'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right', ...
        'FontName', 'Arial', 'FontSize', 8.5, ...
        'BackgroundColor', 'w', 'EdgeColor', [0.82 0.82 0.82], ...
        'Margin', 4);

    box(ax, 'off');
    hold(ax, 'off');
end


%% Adjusted expected-reward curves for the three exposure states

function plotHemisphereExpectedRewardCurves(ax, result, config, ...
    leftColor, rightColor)

    curve = result.modelEffectTable;
    contrast = result.contrastResults;
    x = curve.expectedReward;

    leftLight = 0.78 * [1 1 1] + 0.22 * leftColor;
    rightLight = 0.78 * [1 1 1] + 0.22 * rightColor;

    hold(ax, 'on');

    fill(ax, [x; flipud(x)], ...
        [curve.relativeHazardOutsideIEDCILow; ...
        flipud(curve.relativeHazardOutsideIEDCIHigh)], ...
        [0.78 0.78 0.78], 'EdgeColor', 'none', ...
        'FaceAlpha', 0.25, 'HandleVisibility', 'off');

    fill(ax, [x; flipud(x)], ...
        [curve.relativeHazardLeftIEDCILow; ...
        flipud(curve.relativeHazardLeftIEDCIHigh)], ...
        leftLight, 'EdgeColor', 'none', ...
        'FaceAlpha', 0.38, 'HandleVisibility', 'off');

    fill(ax, [x; flipud(x)], ...
        [curve.relativeHazardRightIEDCILow; ...
        flipud(curve.relativeHazardRightIEDCIHigh)], ...
        rightLight, 'EdgeColor', 'none', ...
        'FaceAlpha', 0.38, 'HandleVisibility', 'off');

    yline(ax, 1, '--', 'Color', [0.45 0.45 0.45], ...
        'HandleVisibility', 'off');
    xline(ax, curve.referenceExpectedReward(1), ':', ...
        'Color', [0.55 0.55 0.55], 'HandleVisibility', 'off');

    outsideLine = plot(ax, x, curve.relativeHazardOutsideIED, '--', ...
        'LineWidth', 2, 'Color', [0.25 0.25 0.25], ...
        'DisplayName', 'outside both post-IED windows');
    leftLine = plot(ax, x, curve.relativeHazardLeftIED, '-', ...
        'LineWidth', 2.2, 'Color', leftColor, ...
        'DisplayName', 'left post-IED only');
    rightLine = plot(ax, x, curve.relativeHazardRightIED, '-', ...
        'LineWidth', 2.2, 'Color', rightColor, ...
        'DisplayName', 'right post-IED only');

    set(ax, 'YScale', 'log', 'FontName', 'Arial', ...
        'FontSize', 10, 'TickDir', 'out');
    xlabel(ax, 'expected reward');
    ylabel(ax, sprintf('relative %s hazard', config.hazardName));
    title(ax, sprintf('%s: adjusted expected-reward effects', ...
        config.code), 'FontWeight', 'bold');

    resultText = sprintf([ ...
        'reward slope outside = %.3f\n' ...
        'reward slope after left IED = %.3f\n' ...
        'reward slope after right IED = %.3f\n' ...
        'L-R interaction p = %.3g'], ...
        result.expectedRewardSlopeOutsideIED, ...
        result.expectedRewardSlopeLeftIED, ...
        result.expectedRewardSlopeRightIED, ...
        contrast.clusterRobustPValue_IEDxExpectedReward);

    text(ax, 0.98, 0.96, resultText, 'Units', 'normalized', ...
        'VerticalAlignment', 'top', 'HorizontalAlignment', 'right', ...
        'FontName', 'Arial', 'FontSize', 8.5, ...
        'BackgroundColor', 'w', 'EdgeColor', [0.82 0.82 0.82], ...
        'Margin', 5);

    legend(ax, [outsideLine leftLine rightLine], ...
        'Location', 'best', 'Box', 'off', 'FontSize', 8);

    box(ax, 'off');
    hold(ax, 'off');
end
