% Participant-stratified Cox models comparing left- and right-hemisphere
% IED occurrence x Niv learning-asymmetry interactions
%
% Both hemisphere-specific post-IED indicators and both interactions with
% Niv are entered together in the same Cox model. Therefore,
% left effects are adjusted for right effects and vice versa. The primary
% direct comparison is beta(left IED x Niv) - beta(right IED x Niv).
%
% Hemisphere is read from LFPIED.anatomicalLocs_wHemisphere. Labels are
% expected to end in _L or _R (for example, area_L and area_R).
%
% Author: Nill

clear;
clc;
close all;

inputFolderName_LFPIED = ...
    'D:\Nill\data\BART\0_0_new_IED_new_area_labels\IED1_find_number_of_IEDs\';

nivParameterFile = ...
    'D:\Nill\code\BART\IED\0_0_new_IED_new_area_labels\context_modeling\param_recovery_4_param_recovery\alpha_comparison.csv';

outputFolderName = ...
    'D:\Nill\code\BART\IED\0_0_new_IED_new_area_labels\IED9_3_Cox_niv_param_occurrence_LR_hemi\';

if ~exist(outputFolderName, 'dir')
    mkdir(outputFolderName);
end

samplingFrequency = 1000;
maximumRT = 20;
numberOfPermutations = 1000;
numberOfNivCurvePoints = 200;
randomSeed = 42;

colorIT = [0.847 0.333 0.153];
colorRT = [0.204 0.459 0.702];
colorBR = [0.250 0.600 0.250];
colorPR = [0.494 0.184 0.556];

leftColor = [0.121 0.466 0.705];
rightColor = [0.839 0.153 0.157];

configs(1).code = 'IT';
configs(1).durationField = 'ITs';
configs(1).iedField = 'IED_occurance_IT';
configs(1).bankedOnly = false;
configs(1).poppedOnly = false;
configs(1).windowMilliseconds = 1000;
configs(1).color = colorIT;
configs(1).hazardName = 'action';

configs(2).code = 'RT';
configs(2).durationField = 'RTs';
configs(2).iedField = 'IED_occurance_RT';
configs(2).bankedOnly = false;
configs(2).poppedOnly = false;
configs(2).windowMilliseconds = 500;
configs(2).color = colorRT;
configs(2).hazardName = 'response';

configs(3).code = 'BR';
configs(3).durationField = 'ITs';
configs(3).iedField = 'IED_occurance_IT';
configs(3).bankedOnly = true;
configs(3).poppedOnly = false;
configs(3).windowMilliseconds = 1000;
configs(3).color = colorBR;
configs(3).hazardName = 'banking';

configs(4).code = 'PR';
configs(4).durationField = 'ITs';
configs(4).iedField = 'IED_occurance_IT';
configs(4).bankedOnly = false;
configs(4).poppedOnly = true;
configs(4).windowMilliseconds = 1000;
configs(4).color = colorPR;
configs(4).hazardName = 'popping';

%% Read and save the Niv parameters

[nivTable, nivMean, nivSD] = readNivTable(nivParameterFile);

fprintf('Loaded Niv parameters for %d participants\n', height(nivTable));
fprintf('Mean Niv = %.6f, SD = %.6f\n', nivMean, nivSD);

writetable(nivTable, fullfile(outputFolderName, ...
    'niv_parameters_used.csv'));

nivFigure = plotNivParameters(nivTable);
nivFigureOutputFile = fullfile(outputFolderName, ...
    'Niv_alpha_plus_alpha_minus_participant_visualization.pdf');
exportgraphics(nivFigure, nivFigureOutputFile, 'ContentType', 'vector');
close(nivFigure);

%% Run IT, RT, BR, and PR

results = cell(length(configs), 1);

for analysisIndex = 1:length(configs)
    fprintf('\n\nRUNNING %s NIV HEMISPHERE ANALYSIS\n', ...
        configs(analysisIndex).code);

    results{analysisIndex} = runHemisphereNivCoxAnalysis( ...
        inputFolderName_LFPIED, configs(analysisIndex), nivTable, ...
        nivMean, nivSD, samplingFrequency, maximumRT, ...
        numberOfNivCurvePoints, numberOfPermutations, ...
        randomSeed + analysisIndex - 1);
end

%% Save compact results tables

hemisphereResultsAll = table();
contrastResultsAll = table();

for analysisIndex = 1:length(configs)
    thisHemisphereTable = results{analysisIndex}.hemisphereResults;
    thisHemisphereTable.outcome = repmat( ...
        string(configs(analysisIndex).code), ...
        height(thisHemisphereTable), 1);
    thisHemisphereTable = movevars( ...
        thisHemisphereTable, 'outcome', 'Before', 1);
    hemisphereResultsAll = [hemisphereResultsAll; thisHemisphereTable];

    thisContrastTable = results{analysisIndex}.contrastResults;
    thisContrastTable.outcome = string(configs(analysisIndex).code);
    thisContrastTable = movevars( ...
        thisContrastTable, 'outcome', 'Before', 1);
    contrastResultsAll = [contrastResultsAll; thisContrastTable];
end

writetable(hemisphereResultsAll, fullfile(outputFolderName, ...
    'IT_RT_BR_PR_niv_left_right_hemisphere_results.csv'));

writetable(contrastResultsAll, fullfile(outputFolderName, ...
    'IT_RT_BR_PR_niv_left_minus_right_contrasts.csv'));

%% Left/right visualization

combinedFigure = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [80 40 1500 1900]);

layout = tiledlayout(combinedFigure, 4, 2, ...
    'Padding', 'compact', 'TileSpacing', 'compact');

sgtitle(layout, [ ...
    'Left versus right hemisphere IED x Niv: ' ...
    'RT 500-ms; IT, BR, and PR 1000-ms windows'], ...
    'FontName', 'Arial', 'FontSize', 16, 'FontWeight', 'bold');

for analysisIndex = 1:length(configs)
    plotHemisphereNivForest(nexttile(layout), ...
        results{analysisIndex}, configs(analysisIndex), ...
        leftColor, rightColor);

    plotHemisphereNivCurves(nexttile(layout), ...
        results{analysisIndex}, configs(analysisIndex), ...
        leftColor, rightColor);
end

combinedPDFOutputFile = fullfile(outputFolderName, ...
    'IT_RT_BR_PR_niv_left_right_comparison_4x2.pdf');

exportgraphics(combinedFigure, combinedPDFOutputFile, ...
    'ContentType', 'vector');
close(combinedFigure);

fprintf('\nDone.\n');
fprintf('Hemisphere results CSV:\n%s\n', fullfile(outputFolderName, ...
    'IT_RT_BR_PR_niv_left_right_hemisphere_results.csv'));
fprintf('Left-minus-right contrast CSV:\n%s\n', fullfile(outputFolderName, ...
    'IT_RT_BR_PR_niv_left_minus_right_contrasts.csv'));
fprintf('Comparison PDF:\n%s\n', combinedPDFOutputFile);
fprintf('Niv parameter PDF:\n%s\n', nivFigureOutputFile);


%% Cox analysis for one outcome

function result = runHemisphereNivCoxAnalysis( ...
    inputFolder, config, nivTable, nivMean, nivSD, ...
    defaultSamplingFrequency, maximumRT, numberOfCurvePoints, ...
    numberOfPermutations, randomSeed)

    code = config.code;
    windowMilliseconds = config.windowMilliseconds;
    windowSeconds = windowMilliseconds / 1000;

    fileList = dir(fullfile(inputFolder, '*.LFPIED.mat'));

    if isempty(fileList)
        error('No .LFPIED.mat files were found in %s.', inputFolder);
    end

    countingProcessData = table();
    trialSummary = table();
    permutationTrialData = table();

    coverageLeftPatients = strings(0, 1);
    coverageRightPatients = strings(0, 1);
    IEDLeftPatients = strings(0, 1);
    IEDRightPatients = strings(0, 1);
    totalLeftIEDs = 0;
    totalRightIEDs = 0;

    for pt = 1:length(fileList)

        fileName = fileList(pt).name;
        fileParts = strsplit(fileName, '.');
        patientID = string(fileParts{1});
        fprintf('%s: processing patient %s\n', code, char(patientID));

        loadedData = load(fullfile(inputFolder, fileName));

        if ~isfield(loadedData, 'LFPIED')
            fprintf('Skipped %s: LFPIED structure was not found.\n', ...
                char(patientID));
            continue;
        end

        LFPIED = loadedData.LFPIED;

        nivRow = find(nivTable.normalizedPatientID == ...
            normalizeID(patientID), 1);

        if isempty(nivRow)
            fprintf('Skipped %s: no Niv parameters.\n', ...
                char(patientID));
            continue;
        end

        alphaPlus = nivTable.alphaPlus(nivRow);
        alphaMinus = nivTable.alphaMinus(nivRow);
        nivRaw = nivTable.nivAsymmetryRaw(nivRow);
        nivZ = nivTable.nivAsymmetryZ(nivRow);

        fprintf('%s: patient %s, Niv = %.4f\n', ...
            code, char(patientID), nivRaw);

        requiredFields = { ...
            'RTs', config.durationField, config.iedField, ...
            'isControl', 'balloonType', 'selectedChans', ...
            'anatomicalLocs_wHemisphere'};

        if config.bankedOnly || config.poppedOnly
            requiredFields{end + 1} = 'BankedTrials';
        end

        missingFields = requiredFields( ...
            ~cellfun(@(fieldName) isfield(LFPIED, fieldName), ...
            requiredFields));

        if ~isempty(missingFields)
            fprintf('Skipped %s: missing %s.\n', char(patientID), ...
                strjoin(missingFields, ', '));
            continue;
        end

        selectedChans = round(double(LFPIED.selectedChans(:)));
        selectedChans = selectedChans( ...
            isfinite(selectedChans) & selectedChans >= 1);
        nSelectedChannels = length(selectedChans);

        if nSelectedChannels == 0
            fprintf('Skipped %s: no selected channels.\n', ...
                char(patientID));
            continue;
        end

        selectedLabels = getSelectedChannelLabels( ...
            LFPIED.anatomicalLocs_wHemisphere, ...
            selectedChans, nSelectedChannels);

        [leftChannelMask, rightChannelMask] = ...
            getHemisphereChannelMasks(selectedLabels);

        leftLocalChannels = find(leftChannelMask);
        rightLocalChannels = find(rightChannelMask);

        if ~isempty(leftLocalChannels)
            coverageLeftPatients(end + 1, 1) = patientID;
        end

        if ~isempty(rightLocalChannels)
            coverageRightPatients(end + 1, 1) = patientID;
        end

        if isempty(leftLocalChannels) && isempty(rightLocalChannels)
            fprintf(['Skipped %s: none of the selected labels ended ' ...
                'in _L or _R.\n'], char(patientID));
            continue;
        end

        RTs = double(LFPIED.RTs(:));
        durations = double(LFPIED.(config.durationField));
        durations = durations(:);
        isControl = double(LFPIED.isControl(:));
        balloonColor = round(double(LFPIED.balloonType(:)));
        balloonColor = mod(balloonColor - 1, 10) + 1;
        IEDoccurrence = double(LFPIED.(config.iedField));

        samplingFrequency = defaultSamplingFrequency;
        if isfield(LFPIED, 'Fs') && isscalar(LFPIED.Fs) && ...
                isfinite(LFPIED.Fs) && LFPIED.Fs > 0
            samplingFrequency = double(LFPIED.Fs);
        end

        if isempty(IEDoccurrence)
            IEDoccurrence = zeros(0, 3);
        elseif size(IEDoccurrence, 2) < 3
            fprintf(['Skipped %s: %s must contain at least trial, ' ...
                'channel, and IED-time columns.\n'], ...
                char(patientID), config.iedField);
            continue;
        end

        vectorLengths = [length(RTs), length(durations), ...
            length(isControl), length(balloonColor)];

        if config.bankedOnly || config.poppedOnly
            bankedTrials = double(LFPIED.BankedTrials(:));
            vectorLengths(end + 1) = length(bankedTrials);
        else
            bankedTrials = NaN(length(durations), 1);
        end

        nTrials = min(vectorLengths);
        RTs = RTs(1:nTrials);
        durations = durations(1:nTrials);
        isControl = isControl(1:nTrials);
        balloonColor = balloonColor(1:nTrials);
        bankedTrials = bankedTrials(1:nTrials);

        patientHasLeftIED = false;
        patientHasRightIED = false;

        for trial = 1:nTrials

            duration = durations(trial);

            keepTrial = isControl(trial) == 0 && ...
                RTs(trial) > 0 && RTs(trial) <= maximumRT && ...
                isfinite(duration) && duration > 0 && ...
                ismember(balloonColor(trial), [1 2 3]);

            if config.bankedOnly || config.poppedOnly
                keepTrial = keepTrial && ...
                    ismember(bankedTrials(trial), [0 1]);

                if config.bankedOnly
                    eventObserved = bankedTrials(trial) == 1;
                else
                    eventObserved = bankedTrials(trial) == 0;
                end
            else
                eventObserved = true;
            end

            if ~keepTrial
                continue;
            end

            trialRows = isfinite(IEDoccurrence(:, 1)) & ...
                round(IEDoccurrence(:, 1)) == trial;

            leftRows = trialRows & ...
                isfinite(IEDoccurrence(:, 2)) & ...
                ismember(round(IEDoccurrence(:, 2)), leftLocalChannels);

            rightRows = trialRows & ...
                isfinite(IEDoccurrence(:, 2)) & ...
                ismember(round(IEDoccurrence(:, 2)), rightLocalChannels);

            leftIEDtimes = getValidIEDTimes( ...
                IEDoccurrence(leftRows, :), ...
                duration, samplingFrequency);

            rightIEDtimes = getValidIEDTimes( ...
                IEDoccurrence(rightRows, :), ...
                duration, samplingFrequency);

            totalLeftIEDs = totalLeftIEDs + length(leftIEDtimes);
            totalRightIEDs = totalRightIEDs + length(rightIEDtimes);
            patientHasLeftIED = patientHasLeftIED || ~isempty(leftIEDtimes);
            patientHasRightIED = patientHasRightIED || ~isempty(rightIEDtimes);

            [tStart, tStop, postIEDLeft, postIEDRight, ...
                activeLeftWindowCount, activeRightWindowCount] = ...
                buildHemisphereIntervals(duration, leftIEDtimes, ...
                rightIEDtimes, windowSeconds);

            nRows = length(tStart);
            censored = true(nRows, 1);
            eventAtStop = false(nRows, 1);

            if eventObserved
                censored(end) = false;
                eventAtStop(end) = true;
            end

            currentRows = table( ...
                repmat(patientID, nRows, 1), ...
                repmat(trial, nRows, 1), ...
                tStart, tStop, censored, eventAtStop, ...
                postIEDLeft, postIEDRight, ...
                activeLeftWindowCount, activeRightWindowCount, ...
                repmat(balloonColor(trial), nRows, 1), ...
                repmat(samplingFrequency, nRows, 1), ...
                repmat(alphaPlus, nRows, 1), ...
                repmat(alphaMinus, nRows, 1), ...
                repmat(nivRaw, nRows, 1), ...
                repmat(nivZ, nRows, 1), ...
                'VariableNames', { ...
                'patientID', 'trialNumber', 'tStart', 'tStop', ...
                'censored', 'eventAtStop', ...
                'postIEDLeft', 'postIEDRight', ...
                'activeLeftIEDWindowCount', ...
                'activeRightIEDWindowCount', ...
                'balloonColorCode', 'samplingFrequencyHz', ...
                'alphaPlus', 'alphaMinus', ...
                'nivAsymmetryRaw', 'nivAsymmetryZ'});

            countingProcessData = [countingProcessData; currentRows];

            rowDuration = tStop - tStart;
            currentSummary = table( ...
                patientID, trial, duration, double(eventObserved), ...
                length(leftIEDtimes), length(rightIEDtimes), ...
                sum(rowDuration .* postIEDLeft), ...
                sum(rowDuration .* postIEDRight), ...
                double(eventObserved && postIEDLeft(end) == 1), ...
                double(eventObserved && postIEDRight(end) == 1), ...
                balloonColor(trial), samplingFrequency, ...
                alphaPlus, alphaMinus, nivRaw, nivZ, ...
                'VariableNames', { ...
                'patientID', 'trialNumber', 'durationSeconds', ...
                'eventObserved', ...
                'nLeftIEDs', 'nRightIEDs', ...
                'leftPostIEDExposureSeconds', ...
                'rightPostIEDExposureSeconds', ...
                'eventInLeftPostIEDWindow', ...
                'eventInRightPostIEDWindow', ...
                'balloonColorCode', 'samplingFrequencyHz', ...
                'alphaPlus', 'alphaMinus', ...
                'nivAsymmetryRaw', 'nivAsymmetryZ'});

            trialSummary = [trialSummary; currentSummary];

            currentPermutationTrial = table( ...
                patientID, trial, duration, double(eventObserved), ...
                balloonColor(trial), nivZ, ...
                {leftIEDtimes}, {rightIEDtimes}, ...
                'VariableNames', { ...
                'patientID', 'trialNumber', 'durationSeconds', ...
                'eventObserved', 'balloonColorCode', 'nivAsymmetryZ', ...
                'leftIEDtimes_seconds', 'rightIEDtimes_seconds'});

            permutationTrialData = ...
                [permutationTrialData; currentPermutationTrial];
        end

        if patientHasLeftIED
            IEDLeftPatients(end + 1, 1) = patientID;
        end

        if patientHasRightIED
            IEDRightPatients(end + 1, 1) = patientID;
        end
    end

    if isempty(countingProcessData)
        error('%s: no valid counting-process data were created.', code);
    end

    if ~any(countingProcessData.postIEDLeft == 1)
        error('%s: no valid left-hemisphere post-IED exposure.', code);
    end

    if ~any(countingProcessData.postIEDRight == 1)
        error('%s: no valid right-hemisphere post-IED exposure.', code);
    end

    [countingProcessData.patientStratum, patientLevels] = ...
        findgroups(countingProcessData.patientID);

    permutationTrialData.patientStratum = ...
        findgroups(permutationTrialData.patientID);

    leftIED = double(countingProcessData.postIEDLeft);
    rightIED = double(countingProcessData.postIEDRight);
    nivZRows = double(countingProcessData.nivAsymmetryZ);

    X = [ ...
        leftIED, rightIED, ...
        leftIED .* nivZRows, ...
        rightIED .* nivZRows, ...
        double(countingProcessData.balloonColorCode == 2), ...
        double(countingProcessData.balloonColorCode == 3)];

    predictorNames = [ ...
        "left_post_ied_indicator"; ...
        "right_post_ied_indicator"; ...
        "left_post_ied_x_niv_z"; ...
        "right_post_ied_x_niv_z"; ...
        "orange_vs_yellow"; ...
        "red_vs_yellow"];

    leftIndex = 1;
    rightIndex = 2;
    leftInteractionIndex = 3;
    rightInteractionIndex = 4;

    T = [countingProcessData.tStart, countingProcessData.tStop];
    censoring = countingProcessData.censored;
    strata = countingProcessData.patientStratum;

    options = statset('coxphfit');
    options.Display = 'final';
    options.MaxIter = 1000;
    options.MaxFunEvals = 5000;

    [beta, logLikelihood, baselineCumulativeHazard, stats] = ...
        coxphfit(X, T, ...
        'Censoring', censoring, ...
        'Strata', strata, ...
        'Ties', 'efron', ...
        'Baseline', 0, ...
        'Options', options);

    patientNumbers = unique(strata);
    clusterScores = zeros(length(patientNumbers), length(beta));

    for patientIndex = 1:length(patientNumbers)
        clusterScores(patientIndex, :) = sum( ...
            stats.scores(strata == patientNumbers(patientIndex), :), 1);
    end

    robustCovariance = stats.covb * ...
        (clusterScores' * clusterScores) * stats.covb;

    if length(patientNumbers) > 1
        robustCovariance = robustCovariance * ...
            length(patientNumbers) / (length(patientNumbers) - 1);
    end

    robustSE = sqrt(max(diag(robustCovariance), 0));
    betaLow = beta - 1.96 * robustSE;
    betaHigh = beta + 1.96 * robustSE;
    hazardRatio = exp(beta);
    hazardRatioLow = exp(betaLow);
    hazardRatioHigh = exp(betaHigh);

    mainContrastVector = zeros(length(beta), 1);
    mainContrastVector(leftIndex) = 1;
    mainContrastVector(rightIndex) = -1;

    interactionContrastVector = zeros(length(beta), 1);
    interactionContrastVector(leftInteractionIndex) = 1;
    interactionContrastVector(rightInteractionIndex) = -1;

    mainContrast = summarizeLinearContrast( ...
        beta, robustCovariance, mainContrastVector);
    interactionContrast = summarizeLinearContrast( ...
        beta, robustCovariance, interactionContrastVector);

    %% Within-participant, within-color trial permutation test

    permutationLeftMainBeta = NaN(numberOfPermutations, 1);
    permutationRightMainBeta = NaN(numberOfPermutations, 1);
    permutationLeftInteractionBeta = NaN(numberOfPermutations, 1);
    permutationRightInteractionBeta = NaN(numberOfPermutations, 1);
    permutationMainContrast = NaN(numberOfPermutations, 1);
    permutationInteractionContrast = NaN(numberOfPermutations, 1);
    permutationSucceeded = false(numberOfPermutations, 1);

    permutationGroups = findgroups( ...
        permutationTrialData.patientID, ...
        permutationTrialData.balloonColorCode);

    rng(randomSeed);
    permutationOptions = options;
    permutationOptions.Display = 'off';

    fprintf('%s: running %d permutations...\n', ...
        code, numberOfPermutations);

    for permutation = 1:numberOfPermutations
        shuffledTrials = permutationTrialData;

        for group = 1:max(permutationGroups)
            groupRows = find(permutationGroups == group);
            sourceRows = groupRows(randperm(length(groupRows)));

            shuffledTrials.durationSeconds(groupRows) = ...
                permutationTrialData.durationSeconds(sourceRows);
            shuffledTrials.eventObserved(groupRows) = ...
                permutationTrialData.eventObserved(sourceRows);
        end

        [permutedX, permutedT, permutedCensoring, permutedStrata] = ...
            buildShuffledHemisphereCoxData( ...
            shuffledTrials, windowSeconds);

        try
            permutationBeta = coxphfit( ...
                permutedX, permutedT, ...
                'Censoring', permutedCensoring, ...
                'Strata', permutedStrata, ...
                'Ties', 'efron', ...
                'Baseline', 0, ...
                'Options', permutationOptions);

            permutationLeftMainBeta(permutation) = ...
                permutationBeta(leftIndex);
            permutationRightMainBeta(permutation) = ...
                permutationBeta(rightIndex);
            permutationLeftInteractionBeta(permutation) = ...
                permutationBeta(leftInteractionIndex);
            permutationRightInteractionBeta(permutation) = ...
                permutationBeta(rightInteractionIndex);
            permutationMainContrast(permutation) = ...
                permutationBeta(leftIndex) - permutationBeta(rightIndex);
            permutationInteractionContrast(permutation) = ...
                permutationBeta(leftInteractionIndex) - ...
                permutationBeta(rightInteractionIndex);
            permutationSucceeded(permutation) = true;
        catch permutationError
            fprintf('%s permutation %d failed: %s\n', ...
                code, permutation, permutationError.message);
        end

        if mod(permutation, 100) == 0 || ...
                permutation == numberOfPermutations
            fprintf('%s permutation progress: %d/%d\n', ...
                code, permutation, numberOfPermutations);
        end
    end

    validRows = permutationSucceeded;
    permutationPLeftMain = calculatePermutationP( ...
        permutationLeftMainBeta(validRows), beta(leftIndex));
    permutationPRightMain = calculatePermutationP( ...
        permutationRightMainBeta(validRows), beta(rightIndex));
    permutationPLeftInteraction = calculatePermutationP( ...
        permutationLeftInteractionBeta(validRows), ...
        beta(leftInteractionIndex));
    permutationPRightInteraction = calculatePermutationP( ...
        permutationRightInteractionBeta(validRows), ...
        beta(rightInteractionIndex));

    % These two outcome-shuffle contrast values are global-null sensitivity
    % measures. The formal left = right tests are the clustered Wald p-values.
    permutationPMainContrast = calculatePermutationP( ...
        permutationMainContrast(validRows), mainContrast.beta);
    permutationPInteractionContrast = calculatePermutationP( ...
        permutationInteractionContrast(validRows), ...
        interactionContrast.beta);

    permutationPAll = NaN(length(beta), 1);
    permutationPAll(leftIndex) = permutationPLeftMain;
    permutationPAll(rightIndex) = permutationPRightMain;
    permutationPAll(leftInteractionIndex) = ...
        permutationPLeftInteraction;
    permutationPAll(rightInteractionIndex) = ...
        permutationPRightInteraction;

    coxResults = table( ...
        predictorNames, beta(:), stats.se(:), stats.z(:), stats.p(:), ...
        robustSE(:), permutationPAll, betaLow(:), betaHigh(:), ...
        hazardRatio(:), hazardRatioLow(:), hazardRatioHigh(:), ...
        'VariableNames', { ...
        'predictor', 'beta_logHazard', 'modelBasedSE', ...
        'modelBasedZ', 'modelBasedPValue', 'clusterRobustSE', ...
        'permutationPValue', 'betaCILow', 'betaCIHigh', ...
        'hazardRatio', 'hazardRatioCILow', 'hazardRatioCIHigh'});

    nCoverage = [ ...
        length(unique(coverageLeftPatients)); ...
        length(unique(coverageRightPatients))];
    nWithIED = [ ...
        length(unique(IEDLeftPatients)); ...
        length(unique(IEDRightPatients))];
    nIEDs = [totalLeftIEDs; totalRightIEDs];

    hemisphereResults = table( ...
        ["Left"; "Right"], ...
        beta([leftIndex; rightIndex]), ...
        robustSE([leftIndex; rightIndex]), ...
        stats.p([leftIndex; rightIndex]), ...
        [permutationPLeftMain; permutationPRightMain], ...
        betaLow([leftIndex; rightIndex]), ...
        betaHigh([leftIndex; rightIndex]), ...
        hazardRatio([leftIndex; rightIndex]), ...
        hazardRatioLow([leftIndex; rightIndex]), ...
        hazardRatioHigh([leftIndex; rightIndex]), ...
        beta([leftInteractionIndex; rightInteractionIndex]), ...
        robustSE([leftInteractionIndex; rightInteractionIndex]), ...
        stats.p([leftInteractionIndex; rightInteractionIndex]), ...
        [permutationPLeftInteraction; permutationPRightInteraction], ...
        betaLow([leftInteractionIndex; rightInteractionIndex]), ...
        betaHigh([leftInteractionIndex; rightInteractionIndex]), ...
        hazardRatio([leftInteractionIndex; rightInteractionIndex]), ...
        hazardRatioLow([leftInteractionIndex; rightInteractionIndex]), ...
        hazardRatioHigh([leftInteractionIndex; rightInteractionIndex]), ...
        nCoverage, nWithIED, nIEDs, ...
        'VariableNames', { ...
        'hemisphere', ...
        'beta_IED', 'clusterRobustSE_IED', ...
        'modelBasedPValue_IED', 'permutationPValue_IED', ...
        'betaCILow_IED', 'betaCIHigh_IED', ...
        'hazardRatio_IED', 'hazardRatioCILow_IED', ...
        'hazardRatioCIHigh_IED', ...
        'beta_IEDxNiv', ...
        'clusterRobustSE_IEDxNiv', ...
        'modelBasedPValue_IEDxNiv', ...
        'permutationPValue_IEDxNiv', ...
        'betaCILow_IEDxNiv', ...
        'betaCIHigh_IEDxNiv', ...
        'hazardRatio_IEDxNiv', ...
        'hazardRatioCILow_IEDxNiv', ...
        'hazardRatioCIHigh_IEDxNiv', ...
        'nParticipantsWithCoverage', ...
        'nParticipantsWithIED', 'nIEDs'});

    contrastResults = table( ...
        mainContrast.beta, mainContrast.se, mainContrast.z, ...
        mainContrast.p, permutationPMainContrast, ...
        mainContrast.betaLow, mainContrast.betaHigh, ...
        mainContrast.hr, mainContrast.hrLow, mainContrast.hrHigh, ...
        interactionContrast.beta, interactionContrast.se, ...
        interactionContrast.z, interactionContrast.p, ...
        permutationPInteractionContrast, ...
        interactionContrast.betaLow, interactionContrast.betaHigh, ...
        interactionContrast.hr, interactionContrast.hrLow, ...
        interactionContrast.hrHigh, sum(validRows), ...
        'VariableNames', { ...
        'betaLeftMinusRight_IED', 'clusterRobustSE_IED', ...
        'clusterRobustZ_IED', 'clusterRobustPValue_IED', ...
        'outcomeShufflePermutationPValue_IED', ...
        'betaCILow_IED', 'betaCIHigh_IED', ...
        'hazardRatioLeftDividedByRight_IED', ...
        'hazardRatioRatioCILow_IED', ...
        'hazardRatioRatioCIHigh_IED', ...
        'betaLeftMinusRight_IEDxNiv', ...
        'clusterRobustSE_IEDxNiv', ...
        'clusterRobustZ_IEDxNiv', ...
        'clusterRobustPValue_IEDxNiv', ...
        'outcomeShufflePermutationPValue_IEDxNiv', ...
        'betaCILow_IEDxNiv', ...
        'betaCIHigh_IEDxNiv', ...
        'hazardRatioLeftDividedByRight_IEDxNiv', ...
        'hazardRatioRatioCILow_IEDxNiv', ...
        'hazardRatioRatioCIHigh_IEDxNiv', ...
        'nValidPermutations'});

    permutationResults = table( ...
        (1:numberOfPermutations)', ...
        permutationLeftMainBeta, permutationRightMainBeta, ...
        permutationLeftInteractionBeta, ...
        permutationRightInteractionBeta, ...
        permutationMainContrast, permutationInteractionContrast, ...
        permutationSucceeded, ...
        'VariableNames', { ...
        'permutationIndex', 'permutedLeftIEDBeta', ...
        'permutedRightIEDBeta', ...
        'permutedLeftIEDxNivBeta', ...
        'permutedRightIEDxNivBeta', ...
        'permutedLeftMinusRightIEDBeta', ...
        'permutedLeftMinusRightInteractionBeta', ...
        'fitSucceeded'});

    patientNiv = unique(trialSummary(:, ...
        {'patientID', 'nivAsymmetryRaw', 'nivAsymmetryZ'}), ...
        'rows', 'stable');

    nivCurveTable = makeHemisphereNivCurves( ...
        beta, robustCovariance, predictorNames, ...
        patientNiv.nivAsymmetryRaw, nivMean, nivSD, ...
        numberOfCurvePoints);

    fprintf('\n%s: %d-ms left/right IED x Niv Cox model\n', ...
        code, windowMilliseconds);
    fprintf('Participants analyzed: %d\n', length(patientLevels));
    fprintf('Trials: %d\n', height(trialSummary));
    fprintf('Left coverage / with IED / IEDs: %d / %d / %d\n', ...
        nCoverage(1), nWithIED(1), nIEDs(1));
    fprintf('Right coverage / with IED / IEDs: %d / %d / %d\n', ...
        nCoverage(2), nWithIED(2), nIEDs(2));
    fprintf('Log likelihood: %.6f\n', logLikelihood);
    fprintf(['Left-right interaction contrast: beta = %.6f, ' ...
        'clustered p = %.6g, outcome-shuffle p = %.6g\n'], ...
        interactionContrast.beta, interactionContrast.p, ...
        permutationPInteractionContrast);
    disp(coxResults);
    disp(hemisphereResults);
    disp(contrastResults);

    result.code = code;
    result.countingProcessData = countingProcessData;
    result.trialSummary = trialSummary;
    result.coxResults = coxResults;
    result.hemisphereResults = hemisphereResults;
    result.contrastResults = contrastResults;
    result.nivCurveTable = nivCurveTable;
    result.observedPatientNiv = patientNiv;
    result.beta = beta;
    result.logLikelihood = logLikelihood;
    result.baselineCumulativeHazard = baselineCumulativeHazard;
    result.stats = stats;
    result.clusterRobustCovariance = robustCovariance;
    result.clusterRobustSE = robustSE;
    result.predictorNames = predictorNames;
    result.patientLevels = patientLevels;
    result.nivMean = nivMean;
    result.nivSD = nivSD;
    result.permutationResults = permutationResults;
    result.numberOfPermutations = numberOfPermutations;
    result.numberOfValidPermutations = sum(validRows);
    result.permutationRandomSeed = randomSeed;
end


%% Read labels for the selected channels

function labels = getSelectedChannelLabels( ...
    anatomicalLocs, selectedChans, nSelectedChannels)

    labels = convertLabelsToString(anatomicalLocs);
    labels = labels(:);

    if length(labels) >= max(selectedChans)
        labels = labels(selectedChans);
    elseif length(labels) == nSelectedChannels
        % anatomicalLocs_wHemisphere was already selected-channel restricted.
    else
        error(['Cannot map anatomicalLocs_wHemisphere to selected channels. ' ...
            'Labels = %d, selected channels = %d, maximum channel = %d.'], ...
            length(labels), nSelectedChannels, max(selectedChans));
    end
end


function labels = convertLabelsToString(rawLabels)

    if isstring(rawLabels)
        labels = rawLabels;
    elseif iscell(rawLabels)
        labels = strings(numel(rawLabels), 1);

        for labelIndex = 1:numel(rawLabels)
            value = rawLabels{labelIndex};

            if isempty(value)
                labels(labelIndex) = "";
            elseif iscell(value) && numel(value) == 1
                labels(labelIndex) = string(value{1});
            else
                labels(labelIndex) = string(value);
            end
        end
    elseif ischar(rawLabels)
        labels = string(cellstr(rawLabels));
    elseif iscategorical(rawLabels)
        labels = string(rawLabels);
    else
        labels = string(rawLabels);
    end

    labels = strip(labels(:));
end


%% Identify _L and _R channel labels

function [leftMask, rightMask] = getHemisphereChannelMasks(labels)

    labels = upper(strip(string(labels)));
    labels(ismissing(labels)) = "";

    % The requested format is area_L or area_R. Hyphen/space endings are
    % also accepted so that small atlas-format differences do not discard
    % otherwise valid labels.
    leftMask = ~cellfun('isempty', regexp(cellstr(labels), ...
        '[_\-\s]L$', 'once'));
    rightMask = ~cellfun('isempty', regexp(cellstr(labels), ...
        '[_\-\s]R$', 'once'));

    leftMask = leftMask(:);
    rightMask = rightMask(:);
end


%% Convert one hemisphere's IED rows to valid within-trial times

function IEDtimes = getValidIEDTimes( ...
    hemisphereIEDRows, duration, samplingFrequency)

    if isempty(hemisphereIEDRows) || size(hemisphereIEDRows, 2) < 3
        IEDtimes = zeros(0, 1);
        return;
    end

    IEDtimes = double(hemisphereIEDRows(:, 3)) / samplingFrequency;
    IEDtimes = IEDtimes( ...
        isfinite(IEDtimes) & IEDtimes > 0 & IEDtimes < duration);
    IEDtimes = sort(IEDtimes(:));
end


%% Build start-stop intervals using both hemispheres

function [tStart, tStop, postIEDLeft, postIEDRight, ...
    activeLeftWindowCount, activeRightWindowCount] = ...
    buildHemisphereIntervals(duration, leftIEDtimes, ...
    rightIEDtimes, windowSeconds)

    leftWindowEnds = min(leftIEDtimes + windowSeconds, duration);
    rightWindowEnds = min(rightIEDtimes + windowSeconds, duration);

    breakTimes = unique([ ...
        0; leftIEDtimes; leftWindowEnds; ...
        rightIEDtimes; rightWindowEnds; duration]);

    tStart = breakTimes(1:end-1);
    tStop = breakTimes(2:end);
    midpoint = (tStart + tStop) / 2;

    postIEDLeft = zeros(length(midpoint), 1);
    postIEDRight = zeros(length(midpoint), 1);
    activeLeftWindowCount = zeros(length(midpoint), 1);
    activeRightWindowCount = zeros(length(midpoint), 1);

    for IEDindex = 1:length(leftIEDtimes)
        insideWindow = midpoint >= leftIEDtimes(IEDindex) & ...
            midpoint <= leftIEDtimes(IEDindex) + windowSeconds;
        postIEDLeft(insideWindow) = 1;
        activeLeftWindowCount(insideWindow) = ...
            activeLeftWindowCount(insideWindow) + 1;
    end

    for IEDindex = 1:length(rightIEDtimes)
        insideWindow = midpoint >= rightIEDtimes(IEDindex) & ...
            midpoint <= rightIEDtimes(IEDindex) + windowSeconds;
        postIEDRight(insideWindow) = 1;
        activeRightWindowCount(insideWindow) = ...
            activeRightWindowCount(insideWindow) + 1;
    end
end


%% Rebuild Cox data after shuffling trial outcomes/durations

function [X, T, censoring, strata] = ...
    buildShuffledHemisphereCoxData(trialData, windowSeconds)

    nTrials = height(trialData);
    Xcells = cell(nTrials, 1);
    Tcells = cell(nTrials, 1);
    censoringCells = cell(nTrials, 1);
    strataCells = cell(nTrials, 1);

    for trialIndex = 1:nTrials
        duration = trialData.durationSeconds(trialIndex);

        leftIEDtimes = trialData.leftIEDtimes_seconds{trialIndex};
        rightIEDtimes = trialData.rightIEDtimes_seconds{trialIndex};
        leftIEDtimes = leftIEDtimes(leftIEDtimes < duration);
        rightIEDtimes = rightIEDtimes(rightIEDtimes < duration);

        [tStart, tStop, postIEDLeft, postIEDRight] = ...
            buildHemisphereIntervals(duration, leftIEDtimes, ...
            rightIEDtimes, windowSeconds);

        color = trialData.balloonColorCode(trialIndex);
        nivZ = trialData.nivAsymmetryZ(trialIndex);
        nRows = length(tStart);

        Xcells{trialIndex} = [ ...
            postIEDLeft, postIEDRight, ...
            postIEDLeft .* nivZ, ...
            postIEDRight .* nivZ, ...
            repmat(double(color == 2), nRows, 1), ...
            repmat(double(color == 3), nRows, 1)];

        Tcells{trialIndex} = [tStart, tStop];

        trialCensoring = true(nRows, 1);
        if trialData.eventObserved(trialIndex) == 1
            trialCensoring(end) = false;
        end
        censoringCells{trialIndex} = trialCensoring;

        strataCells{trialIndex} = repmat( ...
            trialData.patientStratum(trialIndex), nRows, 1);
    end

    X = vertcat(Xcells{:});
    T = vertcat(Tcells{:});
    censoring = vertcat(censoringCells{:});
    strata = vertcat(strataCells{:});
end


function permutationP = calculatePermutationP( ...
    validPermutationStatistics, observedStatistic)

    if isempty(validPermutationStatistics)
        permutationP = NaN;
        return;
    end

    permutationP = (1 + sum( ...
        abs(validPermutationStatistics) >= abs(observedStatistic))) / ...
        (length(validPermutationStatistics) + 1);
end


%% Summarize a participant-clustered linear contrast

function summary = summarizeLinearContrast(beta, covariance, contrast)

    summary.beta = contrast' * beta;
    contrastVariance = contrast' * covariance * contrast;
    summary.se = sqrt(max(contrastVariance, 0));
    summary.z = summary.beta / summary.se;
    summary.p = 2 * normcdf(-abs(summary.z));
    summary.betaLow = summary.beta - 1.96 * summary.se;
    summary.betaHigh = summary.beta + 1.96 * summary.se;
    summary.hr = exp(summary.beta);
    summary.hrLow = exp(summary.betaLow);
    summary.hrHigh = exp(summary.betaHigh);
end


%% Left and right IED effects across the Niv range

function curveTable = makeHemisphereNivCurves( ...
    beta, covariance, predictorNames, observedNiv, ...
    nivMean, nivSD, numberOfPoints)

    observedNiv = observedNiv(isfinite(observedNiv));
    nivRaw = linspace(min(observedNiv), max(observedNiv), ...
        numberOfPoints)';
    nivZ = (nivRaw - nivMean) / nivSD;

    leftIndex = find(predictorNames == ...
        "left_post_ied_indicator", 1);
    rightIndex = find(predictorNames == ...
        "right_post_ied_indicator", 1);
    leftInteractionIndex = find(predictorNames == ...
        "left_post_ied_x_niv_z", 1);
    rightInteractionIndex = find(predictorNames == ...
        "right_post_ied_x_niv_z", 1);

    nGrid = length(nivRaw);
    logHRLeft = zeros(nGrid, 1);
    logHRRight = zeros(nGrid, 1);
    seLeft = zeros(nGrid, 1);
    seRight = zeros(nGrid, 1);

    for nivNumber = 1:nGrid
        leftContrast = zeros(length(beta), 1);
        leftContrast(leftIndex) = 1;
        leftContrast(leftInteractionIndex) = nivZ(nivNumber);

        rightContrast = zeros(length(beta), 1);
        rightContrast(rightIndex) = 1;
        rightContrast(rightInteractionIndex) = nivZ(nivNumber);

        logHRLeft(nivNumber) = leftContrast' * beta;
        logHRRight(nivNumber) = rightContrast' * beta;
        seLeft(nivNumber) = sqrt(max( ...
            leftContrast' * covariance * leftContrast, 0));
        seRight(nivNumber) = sqrt(max( ...
            rightContrast' * covariance * rightContrast, 0));
    end

    curveTable = table( ...
        nivRaw, nivZ, ...
        logHRLeft, seLeft, exp(logHRLeft), ...
        exp(logHRLeft - 1.96 * seLeft), ...
        exp(logHRLeft + 1.96 * seLeft), ...
        logHRRight, seRight, exp(logHRRight), ...
        exp(logHRRight - 1.96 * seRight), ...
        exp(logHRRight + 1.96 * seRight), ...
        'VariableNames', { ...
        'nivAsymmetryRaw', 'nivAsymmetryZ', ...
        'logHazardRatioLeftIED', 'standardErrorLeftIED', ...
        'hazardRatioLeftIED', 'hazardRatioLeftIEDCILow', ...
        'hazardRatioLeftIEDCIHigh', ...
        'logHazardRatioRightIED', 'standardErrorRightIED', ...
        'hazardRatioRightIED', 'hazardRatioRightIEDCILow', ...
        'hazardRatioRightIEDCIHigh'});
end


%% Paired left/right main and Niv-interaction coefficients

function plotHemisphereNivForest(ax, result, config, ...
    leftColor, rightColor)

    plotData = result.hemisphereResults;
    contrast = result.contrastResults;

    hazardRatioValues = [ ...
        plotData.hazardRatio_IED(1); plotData.hazardRatio_IED(2); ...
        plotData.hazardRatio_IEDxNiv(1); ...
        plotData.hazardRatio_IEDxNiv(2)];
    lowValues = [ ...
        plotData.hazardRatioCILow_IED(1); ...
        plotData.hazardRatioCILow_IED(2); ...
        plotData.hazardRatioCILow_IEDxNiv(1); ...
        plotData.hazardRatioCILow_IEDxNiv(2)];
    highValues = [ ...
        plotData.hazardRatioCIHigh_IED(1); ...
        plotData.hazardRatioCIHigh_IED(2); ...
        plotData.hazardRatioCIHigh_IEDxNiv(1); ...
        plotData.hazardRatioCIHigh_IEDxNiv(2)];
    permutationPValues = [ ...
        plotData.permutationPValue_IED(1); ...
        plotData.permutationPValue_IED(2); ...
        plotData.permutationPValue_IEDxNiv(1); ...
        plotData.permutationPValue_IEDxNiv(2)];

    y = (1:4)';
    colors = [leftColor; rightColor; leftColor; rightColor];
    markers = {'o', 'o', 's', 's'};

    hold(ax, 'on');

    for row = 1:4
        errorbar(ax, hazardRatioValues(row), y(row), ...
            hazardRatioValues(row) - lowValues(row), ...
            highValues(row) - hazardRatioValues(row), ...
            'horizontal', markers{row}, 'LineWidth', 1.6, ...
            'MarkerSize', 7, 'MarkerFaceColor', colors(row, :), ...
            'MarkerEdgeColor', colors(row, :), ...
            'Color', colors(row, :));
    end

    xline(ax, 1, '--', 'Color', [0.42 0.42 0.42]);

    labels = { ...
        'Left IED at mean Niv'; ...
        'Right IED at mean Niv'; ...
        'Left IED x Niv (1 SD)'; ...
        'Right IED x Niv (1 SD)'};

    set(ax, 'YTick', y, 'YTickLabel', labels, 'YDir', 'reverse', ...
        'FontName', 'Arial', 'FontSize', 9.5, ...
        'TickDir', 'out', 'TickLabelInterpreter', 'none', ...
        'XScale', 'log');

    plotLimits = [lowValues; highValues; 1];
    plotLimits = plotLimits(isfinite(plotLimits) & plotLimits > 0);
    xlim(ax, [0.85 * min(plotLimits), 1.18 * max(plotLimits)]);
    ylim(ax, [0.5 4.5]);

    for row = 1:4
        if isfinite(permutationPValues(row)) && ...
                permutationPValues(row) < 0.05
            xLimits = xlim(ax);
            starX = highValues(row) * ...
                (xLimits(2) / xLimits(1)) ^ 0.03;
            text(ax, starX, row, '*', ...
                'FontSize', 15, 'FontWeight', 'bold');
        end
    end

    xlabel(ax, 'Hazard Ratio (95% CI)');
    title(ax, config.code, 'FontWeight', 'bold');

    resultText = sprintf([ ...
        'Interaction HR ratio (L / R) = %.3f\n' ...
        'robust p = %.3g\noutcome-shuffle p = %.3g'], ...
        exp(contrast.betaLeftMinusRight_IEDxNiv), ...
        contrast.clusterRobustPValue_IEDxNiv, ...
        contrast.outcomeShufflePermutationPValue_IEDxNiv);

    text(ax, 0.98, 0.04, resultText, 'Units', 'normalized', ...
        'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right', ...
        'FontName', 'Arial', 'FontSize', 8.5, ...
        'BackgroundColor', 'w', 'EdgeColor', [0.82 0.82 0.82], ...
        'Margin', 4);

    box(ax, 'off');
    hold(ax, 'off');
end


%% Left and right IED hazard ratios across raw Niv asymmetry

function plotHemisphereNivCurves(ax, result, config, ...
    leftColor, rightColor)

    curve = result.nivCurveTable;
    contrast = result.contrastResults;
    x = curve.nivAsymmetryRaw;

    leftLight = 0.78 * [1 1 1] + 0.22 * leftColor;
    rightLight = 0.78 * [1 1 1] + 0.22 * rightColor;

    hold(ax, 'on');

    fill(ax, [x; flipud(x)], ...
        [curve.hazardRatioLeftIEDCILow; ...
        flipud(curve.hazardRatioLeftIEDCIHigh)], ...
        leftLight, 'EdgeColor', 'none', ...
        'FaceAlpha', 0.42, 'HandleVisibility', 'off');

    fill(ax, [x; flipud(x)], ...
        [curve.hazardRatioRightIEDCILow; ...
        flipud(curve.hazardRatioRightIEDCIHigh)], ...
        rightLight, 'EdgeColor', 'none', ...
        'FaceAlpha', 0.42, 'HandleVisibility', 'off');

    yline(ax, 1, '--', 'Color', [0.45 0.45 0.45], ...
        'HandleVisibility', 'off');
    xline(ax, 0, ':', 'Color', [0.55 0.55 0.55], ...
        'HandleVisibility', 'off');

    leftLine = plot(ax, x, curve.hazardRatioLeftIED, '-', ...
        'LineWidth', 2.3, 'Color', leftColor, ...
        'DisplayName', 'left-hemisphere IED');
    rightLine = plot(ax, x, curve.hazardRatioRightIED, '-', ...
        'LineWidth', 2.3, 'Color', rightColor, ...
        'DisplayName', 'right-hemisphere IED');

    participantNiv = result.observedPatientNiv.nivAsymmetryRaw;
    minimumCI = min([curve.hazardRatioLeftIEDCILow; ...
        curve.hazardRatioRightIEDCILow]);
    rugY = repmat(minimumCI, length(participantNiv), 1);
    scatter(ax, participantNiv, rugY, 13, [0.25 0.25 0.25], ...
        'filled', 'MarkerFaceAlpha', 0.30, ...
        'MarkerEdgeColor', 'none', 'HandleVisibility', 'off');

    set(ax, 'YScale', 'log', 'FontName', 'Arial', ...
        'FontSize', 10, 'TickDir', 'out');
    xlabel(ax, 'Niv Asymmetry: (alpha- - alpha+) / (alpha- + alpha+)');
    ylabel(ax, sprintf('HR for %s after IED vs outside window', ...
        config.hazardName));
    title(ax, config.code, 'FontWeight', 'bold');

    resultText = sprintf([ ...
        'Left IED x Niv HR = %.3f, p_{perm} = %.3g\n' ...
        'Right IED x Niv HR = %.3f, p_{perm} = %.3g\n' ...
        'L-R interaction p = %.3g'], ...
        result.hemisphereResults.hazardRatio_IEDxNiv(1), ...
        result.hemisphereResults.permutationPValue_IEDxNiv(1), ...
        result.hemisphereResults.hazardRatio_IEDxNiv(2), ...
        result.hemisphereResults.permutationPValue_IEDxNiv(2), ...
        contrast.clusterRobustPValue_IEDxNiv);

    text(ax, 0.98, 0.96, resultText, 'Units', 'normalized', ...
        'VerticalAlignment', 'top', 'HorizontalAlignment', 'right', ...
        'FontName', 'Arial', 'FontSize', 8.5, ...
        'BackgroundColor', 'w', 'EdgeColor', [0.82 0.82 0.82], ...
        'Margin', 5);

    legend(ax, [leftLine rightLine], 'Location', 'best', ...
        'Box', 'off', 'FontSize', 8);

    box(ax, 'off');
    hold(ax, 'off');
end


%% Read and standardize participant Niv values

function [nivTable, nivMean, nivSD] = readNivTable(nivFile)

    if ~exist(nivFile, 'file')
        error('Niv parameter CSV was not found: %s', nivFile);
    end

    raw = readtable(nivFile, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');

    requiredNames = ["ptID", "fit_alpha_plus", "fit_alpha_minus"];
    if ~all(ismember(requiredNames, string(raw.Properties.VariableNames)))
        error(['Niv CSV must contain ptID, fit_alpha_plus, ' ...
            'and fit_alpha_minus.']);
    end

    patientID = strip(string(raw.('ptID')));
    alphaPlus = str2double(string(raw.('fit_alpha_plus')));
    alphaMinus = str2double(string(raw.('fit_alpha_minus')));

    denominator = alphaMinus + alphaPlus;
    nivRaw = (alphaMinus - alphaPlus) ./ denominator;

    keep = strlength(patientID) > 0 & isfinite(alphaPlus) & ...
        isfinite(alphaMinus) & denominator > 0 & isfinite(nivRaw);

    patientID = patientID(keep);
    alphaPlus = alphaPlus(keep);
    alphaMinus = alphaMinus(keep);
    nivRaw = nivRaw(keep);
    normalizedPatientID = normalizeID(patientID);

    [~, firstRow] = unique(normalizedPatientID, 'stable');
    patientID = patientID(firstRow);
    normalizedPatientID = normalizedPatientID(firstRow);
    alphaPlus = alphaPlus(firstRow);
    alphaMinus = alphaMinus(firstRow);
    nivRaw = nivRaw(firstRow);

    nivMean = mean(nivRaw, 'omitnan');
    nivSD = std(nivRaw, 0, 'omitnan');

    if ~isfinite(nivSD) || nivSD <= eps
        error('Niv values have zero or invalid standard deviation.');
    end

    nivZ = (nivRaw - nivMean) / nivSD;

    nivTable = table(patientID, normalizedPatientID, ...
        alphaPlus, alphaMinus, nivRaw, nivZ, ...
        'VariableNames', { ...
        'patientID', 'normalizedPatientID', ...
        'alphaPlus', 'alphaMinus', ...
        'nivAsymmetryRaw', 'nivAsymmetryZ'});
end


function normalized = normalizeID(patientID)
    normalized = lower(strip(string(patientID)));
    normalized = regexprep(normalized, '[^a-z0-9]', '');
end


%% Participant Niv visualization

function fig = plotNivParameters(nivTable)

    alphaPlus = nivTable.alphaPlus;
    alphaMinus = nivTable.alphaMinus;
    nivRaw = nivTable.nivAsymmetryRaw;
    patientID = nivTable.patientID;

    maximumAbsoluteNiv = max(abs(nivRaw));
    colorLimits = [-maximumAbsoluteNiv maximumAbsoluteNiv];

    blue = [0.12 0.35 0.75];
    white = [0.97 0.97 0.97];
    red = [0.78 0.18 0.18];
    colorMap = [ ...
        linspace(blue(1), white(1), 128)', ...
        linspace(blue(2), white(2), 128)', ...
        linspace(blue(3), white(3), 128)'; ...
        linspace(white(1), red(1), 128)', ...
        linspace(white(2), red(2), 128)', ...
        linspace(white(3), red(3), 128)'];

    fig = figure('Visible', 'off', 'Color', 'w', ...
        'Position', [40 40 1800 1250]);
    set(fig, 'Colormap', colorMap);
    layout = tiledlayout(fig, 1, 2, ...
        'Padding', 'compact', 'TileSpacing', 'compact');

    ax1 = nexttile(layout);
    hold(ax1, 'on');
    axisLimit = 1.08 * max([alphaPlus; alphaMinus]);
    plot(ax1, [0 axisLimit], [0 axisLimit], '--', ...
        'Color', [0.35 0.35 0.35], 'LineWidth', 1.4);
    scatter(ax1, alphaPlus, alphaMinus, 92, nivRaw, 'filled', ...
        'MarkerFaceAlpha', 0.75, 'MarkerEdgeColor', 'none');
    set(ax1, 'CLim', colorLimits, 'TickDir', 'out', ...
        'FontName', 'Arial', 'FontSize', 10);
    xlim(ax1, [0 axisLimit]);
    ylim(ax1, [0 axisLimit]);
    axis(ax1, 'square');
    xlabel(ax1, 'Fitted positive learning rate, alpha+');
    ylabel(ax1, 'Fitted negative learning rate, alpha-');
    title(ax1, 'alpha+ versus alpha- by participant', ...
        'FontWeight', 'bold');
    colorbar(ax1);
    box(ax1, 'off');

    ax2 = nexttile(layout);
    [nivSorted, order] = sort(nivRaw);
    positions = (1:length(nivSorted))';
    scatter(ax2, nivSorted, positions, 62, nivSorted, 'filled', ...
        'MarkerFaceAlpha', 0.85, 'MarkerEdgeColor', 'none');
    xline(ax2, 0, '--', 'Color', [0.25 0.25 0.25]);
    set(ax2, 'CLim', colorLimits, 'YDir', 'reverse', ...
        'YTick', positions, 'YTickLabel', patientID(order), ...
        'TickLabelInterpreter', 'none', 'TickDir', 'out', ...
        'FontName', 'Arial', 'FontSize', 8);
    xlabel(ax2, 'Niv learning-rate asymmetry');
    ylabel(ax2, sprintf('Participants, n = %d', height(nivTable)));
    title(ax2, 'Participant-level Niv asymmetry', ...
        'FontWeight', 'bold');
    box(ax2, 'off');

    title(layout, 'Fitted learning rates and Niv asymmetry', ...
        'FontWeight', 'bold', 'FontSize', 17);
end
